import { describe, expect, it } from "vitest";
import { APP_LOCALES } from "@/lib/app-locale";
import { APP_COPY, getAppCopy } from "./app-copy";

describe("APP_COPY", () => {
  it("covers every supported application locale", () => {
    expect(Object.keys(APP_COPY).sort()).toEqual([...APP_LOCALES].sort());
  });

  it("returns complete, renderable static copy for each locale", () => {
    for (const locale of APP_LOCALES) {
      const copy = getAppCopy(locale);

      expect(copy).toBe(APP_COPY[locale]);

      const renderedCopy = [
        copy.common.cancel,
        copy.common.close,
        copy.nav.dashboard,
        copy.nav.tasks,
        copy.nav.settings,
        copy.nav.logIn,
        copy.nav.closeSettingsFirst,
        copy.home.title,
        copy.home.description,
        copy.home.startATask,
        copy.home.getStarted,
        copy.login.title,
        copy.login.emailLabel,
        copy.login.passwordLabel,
        copy.login.invalidCredentials,
        copy.login.submitting,
        copy.login.submit,
        copy.login.noAccount,
        copy.login.signUp,
        copy.signup.title,
        copy.signup.nameLabel,
        copy.signup.emailLabel,
        copy.signup.passwordLabel,
        copy.signup.invalidInput,
        copy.signup.emailInUse,
        copy.signup.genericError,
        copy.signup.automaticLoginFailed,
        copy.signup.submitting,
        copy.signup.submit,
        copy.signup.alreadyHaveAccount,
        copy.signup.logIn,
        copy.dashboard.welcome("Ana"),
        copy.dashboard.accountUnavailableTitle,
        copy.dashboard.accountUnavailableDescription,
        copy.dashboard.chartTitle,
        copy.dashboard.chartCaption({ count: 5 }),
        copy.dashboard.emptyTitle,
        copy.dashboard.emptyDescription,
        copy.dashboard.taskLegend({ number: 1 }),
        copy.dashboard.levelAxisLabel,
        copy.dashboard.attemptAxisLabel,
        copy.dashboard.recentCorrectionsTitle,
        copy.dashboard.viewAllCorrections,
        copy.dashboard.correctionHistoryTitle,
        copy.dashboard.noCorrectionHistoryTitle,
        copy.dashboard.noCorrectionHistoryDescription,
        copy.dashboard.limitedCorrectionDetails,
        copy.dashboard.backToCorrectionHistory,
        copy.dashboard.backToDashboard,
        copy.dashboard.attemptedOn({ date: "August 7, 2026" }),
        copy.walkthrough.takeATour,
        copy.walkthrough.stepProgress({ step: 1, total: 10 }),
        copy.walkthrough.next,
        copy.walkthrough.back,
        copy.walkthrough.skip,
        copy.walkthrough.finish,
        copy.walkthrough.dashboardWelcomeTitle,
        copy.walkthrough.dashboardWelcomeBody,
        copy.walkthrough.dashboardCorrectionsTitle,
        copy.walkthrough.dashboardCorrectionsBody,
        copy.walkthrough.settingsTitle,
        copy.walkthrough.settingsBody,
        copy.walkthrough.dashboardStartWritingTitle,
        copy.walkthrough.dashboardStartWritingBody,
        copy.walkthrough.taskPickerTitle,
        copy.walkthrough.taskPickerBody,
        copy.walkthrough.topicPickerTitle,
        copy.walkthrough.topicPickerBody,
        copy.walkthrough.guidedWritingTitle,
        copy.walkthrough.guidedWritingBody,
        copy.walkthrough.editorTitle,
        copy.walkthrough.editorBody,
        copy.walkthrough.correctButtonTitle,
        copy.walkthrough.correctButtonBody,
        copy.walkthrough.correctionModalTitle,
        copy.walkthrough.correctionModalBody,
        copy.walkthrough.exampleGenerateTitle,
        copy.walkthrough.exampleGenerateBody,
        copy.walkthrough.editorCopyTitle,
        copy.walkthrough.editorCopyBody,
        copy.walkthrough.editorClearTitle,
        copy.walkthrough.editorClearBody,
        copy.walkthrough.translationTitle,
        copy.walkthrough.translationBody,
        copy.walkthrough.navTitle,
        copy.walkthrough.navBody,
        copy.walkthrough.previewFeedback.summary,
        copy.walkthrough.previewFeedback.cefrRationale,
        copy.walkthrough.previewFeedback.wordCountNote,
        copy.walkthrough.previewFeedback.contentNote,
        copy.walkthrough.previewFeedback.linguisticsNote,
        copy.walkthrough.previewFeedback.vocabularyNote,
        copy.walkthrough.previewFeedback.agreementErrorExplanation,
        copy.walkthrough.previewFeedback.participleErrorExplanation,
        copy.walkthrough.previewFeedback.suggestionOne,
        copy.walkthrough.previewFeedback.suggestionTwo,
        copy.settings.title,
        copy.settings.appearanceHeading,
        copy.settings.appearanceDescription,
        copy.settings.themeLight,
        copy.settings.themeDark,
        copy.settings.themeSystem,
        copy.settings.languageHeading,
        copy.settings.languageDescription,
        copy.settings.helpHeading,
        copy.settings.helpDescription,
        copy.workspace.task.heading,
        copy.workspace.task.targetLength({ minWords: 60, maxWords: 120 }),
        copy.workspace.topic.heading,
        copy.workspace.topic.recentExamTitle,
        copy.workspace.topic.recentExamDescription,
        copy.workspace.topic.customTitle,
        copy.workspace.topic.customDescription,
        copy.workspace.topic.loading,
        copy.workspace.topic.fetchError,
        copy.workspace.topic.unavailableError,
        copy.workspace.topic.notPublishedError,
        copy.workspace.topic.selectedRecentExamAriaLabel,
        copy.workspace.topic.sourceLabel,
        copy.workspace.topic.recentExamsSource({ month: "July 2026" }),
        copy.workspace.topic.customTopicLabel,
        copy.workspace.topic.customTopicPlaceholder,
        copy.workspace.editor.heading,
        copy.workspace.editor.wordCount({ count: 80, minWords: 60, maxWords: 120 }),
        copy.workspace.editor.responseLabel,
        copy.workspace.editor.frenchResponsePlaceholder,
        copy.workspace.editor.correct,
        copy.workspace.editor.correcting,
        copy.workspace.editor.correctingStatus,
        copy.workspace.editor.genericCorrectionError,
        copy.workspace.editor.alreadyCorrected,
        copy.workspace.editor.correctionInProgress,
        copy.workspace.editor.exampleLevelLabel,
        copy.workspace.editor.generateExample,
        copy.workspace.editor.generatingExample,
        copy.workspace.editor.generatingExampleStatus,
        copy.workspace.editor.exampleRateLimitedError,
        copy.workspace.editor.exampleDailyLimitError,
        copy.workspace.editor.exampleUnavailableError,
        copy.workspace.editor.exampleGenericError,
        copy.workspace.editor.exampleNeedsTopicWarning,
        copy.workspace.editor.copy,
        copy.workspace.editor.copied,
        copy.workspace.editor.copyFailed,
        copy.workspace.editor.clear,
        copy.workspace.guidedWriting.show,
        copy.workspace.guidedWriting.hide,
        copy.workspace.guidedWriting.heading,
        copy.workspace.guidedWriting.guideForLevel({ level: "B2" }),
        copy.workspace.guidedWriting.contextConfirmHeading,
        copy.workspace.guidedWriting.contextConfirmPrompt,
        copy.workspace.guidedWriting.contextConfirmTextTypePrompt,
        copy.workspace.guidedWriting.contextConfirmAction,
        copy.workspace.guidedWriting.changeContext,
        copy.workspace.guidedWriting.contextLabel({ profile: "Test" }),
        copy.workspace.guidedWriting.previousStage,
        copy.workspace.guidedWriting.nextStage,
        copy.workspace.guidedWriting.optionalStep,
        copy.workspace.guidedWriting.ideasLabel,
        copy.workspace.guidedWriting.tensesLabel,
        copy.workspace.guidedWriting.tensesHint,
        copy.workspace.guidedWriting.completionCheckLabel,
        copy.workspace.guidedWriting.examplesLabel,
        copy.workspace.guidedWriting.morePhrases,
        copy.workspace.timedTask.show,
        copy.workspace.timedTask.heading,
        copy.workspace.timedTask.recommendedPace({ task: "Tâche 1", minutes: 12 }),
        copy.workspace.timedTask.setupDescription,
        copy.workspace.timedTask.changeDuration,
        copy.workspace.timedTask.durationLabel,
        copy.workspace.timedTask.start,
        copy.workspace.timedTask.pause,
        copy.workspace.timedTask.resume,
        copy.workspace.timedTask.end,
        copy.workspace.timedTask.remaining({ minutes: "12", seconds: "00" }),
        copy.workspace.timedTask.timeUp,
        copy.workspace.timedTask.continueForTwoMinutes,
        copy.workspace.timedTask.summaryHeading,
        copy.workspace.timedTask.summaryActualTime({ time: "12:00" }),
        copy.workspace.timedTask.summaryTargetTime({ time: "12:00" }),
        copy.workspace.timedTask.summaryWordCount({ count: 80 }),
        copy.workspace.timedTask.summaryPhaseReached,
        copy.workspace.timedTask.summaryPhaseNotReached,
        copy.workspace.timedTask.summaryClose,
        ...Object.values(copy.workspace.timedTask.phaseLabels),
        ...Object.values(copy.workspace.timedTask.phasePrompts),
        copy.workspace.translation.heading({ language: "English" }),
        copy.workspace.translation.show,
        copy.workspace.translation.update,
        copy.workspace.translation.hide,
        copy.workspace.translation.inProgress,
        copy.workspace.translation.unavailableError,
        copy.workspace.translation.rateLimitedError,
        copy.workspace.translation.monthlyQuotaError,
        copy.workspace.translation.tooLong({ maxCharacters: "4,000" }),
        copy.workspace.translation.unofficialFallbackNotice,
        copy.workspace.feedback.heading({ language: "English" }),
        copy.workspace.feedback.estimatedLevel({ level: "B2" }),
        copy.workspace.feedback.generatedInOtherLanguage({
          generatedLanguage: "English",
          selectedLanguage: "French",
        }),
        copy.workspace.feedback.stale,
        copy.workspace.feedback.correctedText,
        copy.workspace.feedback.errors({ count: 2 }),
        copy.workspace.feedback.suggestions,
        ...Object.values(copy.workspace.feedback.errorCategories),
        copy.workspace.correctionModal.title({ taskLabel: "Tâche 2" }),
        copy.workspace.correctionModal.submissionId({ id: "essay_123" }),
        copy.workspace.correctionModal.loading,
        copy.workspace.correctionModal.statusEvaluated,
        copy.workspace.correctionModal.wordCount({ count: 135, minWords: 120, maxWords: 150 }),
        copy.workspace.correctionModal.secureLevel({ level: "B2" }),
        copy.workspace.correctionModal.demonstratedLevel({ level: "B2" }),
        copy.workspace.correctionModal.cefrRationaleHeading,
        copy.workspace.correctionModal.cefrEstimateDisclosure,
        copy.workspace.correctionModal.downloadPdf,
        copy.workspace.correctionModal.viewCorrection,
        copy.workspace.correctionModal.tabOverview,
        copy.workspace.correctionModal.scoreDisclosure,
        copy.workspace.correctionModal.globalPerformanceHeading,
        copy.workspace.correctionModal.overallScore({ score: 80 }),
        copy.workspace.correctionModal.overallScoreDescription,
        copy.workspace.correctionModal.tabCompared,
        copy.workspace.correctionModal.tabComments,
        copy.workspace.correctionModal.contentScoreLabel,
        copy.workspace.correctionModal.linguisticsScoreLabel,
        copy.workspace.correctionModal.vocabularyScoreLabel,
        copy.workspace.correctionModal.originalHeading,
        copy.workspace.correctionModal.correctedHeading,
        copy.workspace.correctionModal.correctionsHeading({ count: 2 }),
        copy.workspace.correctionModal.noCorrectionsNote,
        copy.workspace.correctionModal.errorLabel,
        copy.workspace.correctionModal.correctionLabel,
        copy.workspace.correctionModal.noteLabel,
        copy.workspace.correctionModal.toggleNote,
        copy.workspace.correctionModal.commentsHeading,
        copy.workspace.correctionModal.modelVersionHeading,
        copy.workspace.correctionModal.tryAgain,
        copy.workspace.dialog.title,
        copy.workspace.dialog.taskSwitchDescription,
        copy.workspace.dialog.topicSwitchDescription,
        copy.workspace.dialog.dashboardSwitchDescription,
        copy.workspace.dialog.adminSwitchDescription,
        copy.workspace.dialog.exampleOverwriteDescription,
        copy.workspace.dialog.exampleOverwriteConfirm,
        copy.workspace.dialog.clearDraftDescription,
        copy.workspace.dialog.clearDraftConfirm,
        copy.workspace.dialog.confirm,
        copy.workspace.dialog.cancel,
      ];

      for (const value of renderedCopy) {
        expect(value.trim()).not.toBe("");
      }
    }
  });

  it("describes Tâche 2 as a multi-reader narrative-plus-commentary task, not an opinion essay, in every locale", () => {
    // A revert to the old "give and justify an opinion" framing must fail
    // this test even though taskPickerBody would still be non-empty.
    const oldOpinionPhrasingByLocale = {
      en: "give and justify an opinion",
      fr: "donner et justifier une opinion",
      es: "dar y justificar una opinión",
      pt: "dar e justificar uma opinião",
    } as const;
    const correctedPhrasingByLocale = {
      en: "recount an experience for several readers",
      fr: "raconter une expérience pour plusieurs destinataires",
      es: "narrar una experiencia para varios destinatarios",
      pt: "narrar uma experiência para vários destinatários",
    } as const;

    for (const locale of APP_LOCALES) {
      const taskPickerBody = getAppCopy(locale).walkthrough.taskPickerBody;

      expect(taskPickerBody.toLowerCase()).not.toContain(oldOpinionPhrasingByLocale[locale]);
      expect(taskPickerBody).toContain(correctedPhrasingByLocale[locale]);
    }
  });
});
