import type { PracticeExercise } from "./practice-curriculum";

/**
 * Fixed, editor-reviewed Task 3 B2 data. The helper only attaches the
 * deterministic six-stage metadata; all learning content is static below.
 */
type AuthoredVariant = Omit<
  PracticeExercise,
  "id" | "task" | "level" | "skill" | "exerciseType" | "difficulty" | "sequenceOrder" | "prerequisiteExerciseId"
>;

const STAGES: readonly PracticeExercise["exerciseType"][] = [
  "recognize",
  "complete",
  "transform",
  "organize",
  "develop",
  "produce",
];

const taskThreeB2Path = (
  prefix: string,
  skill: string,
  stages: readonly (readonly [AuthoredVariant, AuthoredVariant])[],
): readonly PracticeExercise[] =>
  stages.flatMap(([primary, alternative], index) => {
    const sequenceOrder = (index + 1) as 1 | 2 | 3 | 4 | 5 | 6;
    const shared = {
      task: "TASK_3" as const,
      level: "B2" as const,
      skill,
      exerciseType: STAGES[index]!,
      difficulty: sequenceOrder,
      sequenceOrder,
      prerequisiteExerciseId: index === 0 ? null : `${prefix}-${index}`,
    };
    return [
      { id: `${prefix}-${sequenceOrder}`, ...shared, ...primary },
      { id: `${prefix}-a${sequenceOrder}`, ...shared, ...alternative },
    ];
  });

export const TASK_3_B2_EXERCISES: readonly PracticeExercise[] = [
  ...taskThreeB2Path("t3-b2-introducing-topic", "introducing-topic", [
    [
      { subSkill: "neutral-debate-framing", prompt: "Deux documents discutent de l'installation de jardins partagés dans les villes : l'un insiste sur le lien social, l'autre sur le coût et l'entretien.", instructions: "Choisissez l'introduction qui présente le sujet sans donner votre avis trop tôt.", options: ["Les jardins partagés sont une très bonne idée.", "Les jardins partagés divisent les habitants, car ils peuvent créer du lien social mais demandent aussi des moyens et une organisation durable.", "Les villes devraient toutes avoir plus de jardins.", "Les habitants qui refusent les jardins ont tort."], correctAnswer: "Les jardins partagés divisent les habitants, car ils peuvent créer du lien social mais demandent aussi des moyens et une organisation durable.", acceptedAnswers: [], explanation: "Une introduction B2 présente le sujet et les deux aspects du débat avant de défendre une position.", targetLanguageFeature: "présentation neutre d'un débat", tags: ["introduction", "synthesis", "recognize"] },
      { subSkill: "neutral-debate-framing-alternative", prompt: "Deux documents débattent de la gratuité des musées un dimanche par mois : l'un y voit un moyen d'élargir l'accès, l'autre craint un coût important.", instructions: "Choisissez la formulation qui introduit clairement le débat.", options: ["Les musées doivent être gratuits.", "La gratuité ponctuelle des musées soulève la question de l'accès à la culture et de son financement.", "Les musées gratuits sont toujours meilleurs.", "Le prix des musées est trop élevé."], correctAnswer: "La gratuité ponctuelle des musées soulève la question de l'accès à la culture et de son financement.", acceptedAnswers: [], explanation: "La phrase nomme l'enjeu commun sans choisir encore un camp.", targetLanguageFeature: "enjeu formulé sans prise de position", tags: ["introduction", "recognize", "variant"] },
    ],
    [
      { subSkill: "debate-question", prompt: "Vous présentez deux sources sur le télétravail.", instructions: "Complétez : « Le débat porte sur la question de savoir si le télétravail ______ améliorer l'organisation du travail sans isoler les salariés. »", options: [], correctAnswer: "peut", acceptedAnswers: ["pourrait"], explanation: "La formulation présente une question ouverte plutôt qu'une réponse déjà décidée.", targetLanguageFeature: "formulation d'un enjeu", tags: ["introduction", "complete", "question"] },
      { subSkill: "debate-question-alternative", prompt: "Vous introduisez deux documents sur les repas végétariens dans les cantines.", instructions: "Complétez : « Ces documents interrogent la place que ______ prendre les repas végétariens dans la restauration scolaire. »", options: [], correctAnswer: "pourraient", acceptedAnswers: ["devraient"], explanation: "Le conditionnel permet d'ouvrir le débat sans imposer une conclusion.", targetLanguageFeature: "problématique ouverte", tags: ["introduction", "complete", "variant"] },
    ],
    [
      { subSkill: "opinion-to-neutral-issue", prompt: "Transformez : « Les vélos en libre-service sont indispensables dans toutes les villes. »", instructions: "Reformulez cette opinion pour présenter le débat de manière neutre.", options: [], correctAnswer: null, acceptedAnswers: ["Les vélos en libre-service posent la question de leur utilité et de leur coût pour les villes.", "Le développement des vélos en libre-service fait débat, notamment en raison de leur financement et de leur usage réel."], explanation: "On retire le jugement absolu et on fait apparaître les éléments que les sources peuvent discuter.", targetLanguageFeature: "passage de l'opinion à l'enjeu", tags: ["introduction", "transform", "neutrality"] },
      { subSkill: "opinion-to-neutral-issue-alternative", prompt: "Transformez : « Les écrans devraient être interdits à l'école. »", instructions: "Présentez cette idée comme un débat avec des enjeux opposés.", options: [], correctAnswer: null, acceptedAnswers: ["L'usage des écrans à l'école suscite un débat entre les possibilités pédagogiques et les risques de distraction.", "La place des écrans à l'école interroge leurs avantages pour apprendre et leurs effets possibles sur l'attention."], explanation: "Une bonne introduction B2 rend visibles les deux dimensions du sujet avant toute opinion personnelle.", targetLanguageFeature: "enjeu avec deux aspects", tags: ["introduction", "transform", "variant"] },
    ],
    [
      { subSkill: "theme-views-question-order", prompt: "Vous introduisez deux documents sur la limitation des voitures au centre-ville.", instructions: "Mettez les phrases dans l'ordre d'une introduction claire.", options: ["Ce sujet oppose souvent le besoin de réduire la pollution et les difficultés de déplacement de certains habitants.", "La place de la voiture dans les centres-villes fait actuellement débat.", "Il convient donc d'examiner les arguments avancés de part et d'autre."], correctAnswer: ["La place de la voiture dans les centres-villes fait actuellement débat.", "Ce sujet oppose souvent le besoin de réduire la pollution et les difficultés de déplacement de certains habitants.", "Il convient donc d'examiner les arguments avancés de part et d'autre."], acceptedAnswers: [], explanation: "L'introduction va du thème général aux enjeux opposés, puis annonce l'analyse des sources.", targetLanguageFeature: "thème → enjeux → annonce de l'analyse", tags: ["introduction", "organization", "synthesis"] },
      { subSkill: "theme-views-question-order-alternative", prompt: "Vous introduisez un débat sur l'ouverture des commerces le dimanche.", instructions: "Organisez les phrases.", options: ["La question divise entre la liberté de choix des consommateurs et les conditions de travail des salariés.", "L'ouverture des commerces le dimanche est régulièrement discutée.", "Les deux documents permettent d'examiner ces points de vue avant de se prononcer."], correctAnswer: ["L'ouverture des commerces le dimanche est régulièrement discutée.", "La question divise entre la liberté de choix des consommateurs et les conditions de travail des salariés.", "Les deux documents permettent d'examiner ces points de vue avant de se prononcer."], acceptedAnswers: [], explanation: "On nomme le thème, on précise l'opposition, puis on situe le rôle des documents.", targetLanguageFeature: "organisation d'une introduction", tags: ["introduction", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-source-aware-introduction", prompt: "Deux sources discutent de la création de zones sans voiture près des écoles : l'une met en avant la sécurité des enfants, l'autre souligne les contraintes pour les parents.", instructions: "Rédigez 3 ou 4 phrases : présentez le thème, faites apparaître les deux enjeux et annoncez que vous allez examiner les points de vue avant de donner votre avis.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "À ce stade, vous entraînez une entrée de synthèse : elle doit organiser le débat, pas encore le résoudre.", targetLanguageFeature: "introduction guidée de deux sources", tags: ["introduction", "development", "sources"], selfCheck: ["Je présente le thème sans donner encore mon opinion.", "Les deux enjeux ou points de vue sont clairement visibles.", "J'annonce le passage par les documents avant ma position personnelle."] },
      { subSkill: "guided-source-aware-introduction-alternative", prompt: "Deux documents débattent de l'interdiction des bouteilles en plastique lors des événements publics : l'un défend la réduction des déchets, l'autre évoque le coût des alternatives.", instructions: "Rédigez 3 ou 4 phrases qui introduisent le sujet et les enjeux, sans défendre déjà une solution.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le lecteur doit comprendre pourquoi le sujet fait débat avant de découvrir votre analyse.", targetLanguageFeature: "cadre neutre d'un débat", tags: ["introduction", "development", "variant"], selfCheck: ["J'identifie clairement le sujet commun aux deux documents.", "Je présente au moins un enjeu de chaque côté.", "Mon vocabulaire reste neutre et n'annonce pas prématurément ma conclusion."] },
    ],
    [
      { subSkill: "independent-source-aware-introduction", prompt: "Deux sources débattent de la mise en place d'un service municipal de location de vélos : l'une insiste sur la mobilité accessible, l'autre sur le coût et le risque d'un usage insuffisant.", instructions: "Rédigez une introduction de 50 à 70 mots : présentez le sujet, les deux principaux enjeux et la démarche de synthèse que vous allez suivre avant de prendre position.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une introduction B2 autonome prépare le lecteur à comprendre la comparaison des sources et la future position personnelle.", targetLanguageFeature: "introduction autonome de synthèse", tags: ["introduction", "production", "sources"], selfCheck: ["Le sujet et les deux enjeux sont clairement présentés.", "Je ne donne pas encore mon opinion personnelle.", "J'annonce que je vais examiner ou comparer les points de vue."] },
      { subSkill: "independent-source-aware-introduction-alternative", prompt: "Deux sources débattent de la possibilité de rendre les transports publics gratuits le week-end : l'une souligne l'accès pour tous, l'autre le financement nécessaire.", instructions: "Rédigez une introduction de 50 à 70 mots qui pose le débat, présente les enjeux opposés et prépare l'analyse des documents.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production doit rester équilibrée : elle introduit le débat avant de justifier une préférence.", targetLanguageFeature: "introduction autonome équilibrée", tags: ["introduction", "production", "variant"], selfCheck: ["Je formule le débat sous forme d'enjeu, pas de réponse évidente.", "Les deux points de vue sont représentés de manière équilibrée.", "L'introduction conduit naturellement vers l'analyse des sources."] },
    ],
  ]),
  ...taskThreeB2Path("t3-b2-reformulating-sources", "reformulating-sources", [
    [
      { subSkill: "faithful-main-idea", prompt: "Une source affirme : « Les bibliothèques devraient ouvrir le dimanche car les personnes qui travaillent en semaine pourraient enfin y accéder. »", instructions: "Choisissez la reformulation la plus fidèle.", options: ["La source dit que les bibliothèques sont inutiles en semaine.", "Selon cette source, ouvrir les bibliothèques le dimanche permettrait à davantage de salariés et d'étudiants d'en profiter.", "La source exige que toutes les bibliothèques restent ouvertes toute la nuit.", "Les bibliothèques sont réservées aux personnes qui travaillent."], correctAnswer: "Selon cette source, ouvrir les bibliothèques le dimanche permettrait à davantage de salariés et d'étudiants d'en profiter.", acceptedAnswers: [], explanation: "La reformulation conserve l'idée principale et le groupe concerné, sans reprendre exactement les mots de la source.", targetLanguageFeature: "reformulation fidèle d'une idée principale", tags: ["reformulation", "sources", "recognize"] },
      { subSkill: "faithful-main-idea-alternative", prompt: "Une source affirme : « Les cours en ligne offrent plus de souplesse aux étudiants qui habitent loin de leur établissement. »", instructions: "Choisissez la reformulation correcte.", options: ["La source pense que les cours en ligne sont plus faciles.", "D'après cette source, l'enseignement à distance peut faciliter l'accès aux études pour les personnes éloignées.", "La source veut supprimer toutes les universités.", "Les étudiants ne devraient plus se déplacer."], correctAnswer: "D'après cette source, l'enseignement à distance peut faciliter l'accès aux études pour les personnes éloignées.", acceptedAnswers: [], explanation: "La reformulation garde le lien entre distance et accessibilité sans ajouter une conclusion non présente dans le document.", targetLanguageFeature: "fidélité sans copie", tags: ["reformulation", "recognize", "variant"] },
    ],
    [
      { subSkill: "source-attribution", prompt: "Vous rapportez l'idée d'un premier document sur les jardins partagés.", instructions: "Complétez : « Selon le premier document, les jardins partagés ______ renforcer les liens entre les habitants. »", options: [], correctAnswer: "peuvent", acceptedAnswers: ["pourraient", "permettent de"], explanation: "L'attribution montre que l'idée appartient à la source et non encore à votre position personnelle.", targetLanguageFeature: "attribution à une source", tags: ["reformulation", "complete", "sources"] },
      { subSkill: "source-attribution-alternative", prompt: "Vous rapportez une source sur les écrans à l'école.", instructions: "Complétez : « D'après cette source, les outils numériques ______ soutenir certains apprentissages lorsqu'ils sont utilisés avec un objectif précis. »", options: [], correctAnswer: "peuvent", acceptedAnswers: ["pourraient", "sont susceptibles de"], explanation: "La formule attribue clairement l'argument au document tout en évitant de le présenter comme une vérité générale.", targetLanguageFeature: "verbe de reformulation attribuée", tags: ["reformulation", "complete", "variant"] },
    ],
    [
      { subSkill: "copy-to-paraphrase", prompt: "Reformulez sans copier : « La circulation automobile est responsable d'une grande partie de la pollution en ville. »", instructions: "Conservez l'idée et attribuez-la à la source.", options: [], correctAnswer: null, acceptedAnswers: ["Selon cette source, les voitures contribuent fortement à la pollution dans les zones urbaines.", "Le document souligne que le trafic routier est une cause importante de pollution dans les villes."], explanation: "Une reformulation change les mots et la structure tout en restant fidèle au message du document.", targetLanguageFeature: "paraphrase avec attribution", tags: ["reformulation", "transform", "sources"] },
      { subSkill: "copy-to-paraphrase-alternative", prompt: "Reformulez sans copier : « Les repas végétariens permettent de réduire l'impact environnemental de la restauration collective. »", instructions: "Gardez l'idée principale et mentionnez qu'elle vient de la source.", options: [], correctAnswer: null, acceptedAnswers: ["Le document estime que proposer davantage de menus végétariens peut limiter les effets écologiques de la restauration collective.", "Selon cette source, les choix alimentaires sans viande peuvent rendre les cantines plus respectueuses de l'environnement."], explanation: "La paraphrase remplace les mots de la source sans modifier son lien logique.", targetLanguageFeature: "reformulation sans déformation", tags: ["reformulation", "transform", "variant"] },
    ],
    [
      { subSkill: "two-source-summary-order", prompt: "Deux sources discutent du télétravail. L'une souligne la réduction des trajets ; l'autre craint la perte de liens entre collègues.", instructions: "Mettez les phrases dans l'ordre d'une synthèse courte et claire.", options: ["En revanche, la seconde source rappelle que le travail à distance peut isoler certains salariés.", "La première source met en avant le temps gagné grâce à l'absence de déplacements.", "Ces documents présentent donc à la fois un avantage pratique et une limite relationnelle."], correctAnswer: ["La première source met en avant le temps gagné grâce à l'absence de déplacements.", "En revanche, la seconde source rappelle que le travail à distance peut isoler certains salariés.", "Ces documents présentent donc à la fois un avantage pratique et une limite relationnelle."], acceptedAnswers: [], explanation: "On attribue chaque idée à son document, puis on relie les deux apports sans donner encore son opinion.", targetLanguageFeature: "source 1 → source 2 → synthèse", tags: ["reformulation", "organization", "sources"] },
      { subSkill: "two-source-summary-order-alternative", prompt: "Deux sources parlent de la gratuité des transports. L'une défend l'accès pour les personnes modestes ; l'autre évoque le coût pour les villes.", instructions: "Organisez ce court résumé.", options: ["La seconde souligne toutefois la difficulté de financer durablement cette mesure.", "La première source considère que la gratuité faciliterait les déplacements des personnes aux revenus limités.", "Les documents opposent ainsi un objectif d'égalité à une question de financement."], correctAnswer: ["La première source considère que la gratuité faciliterait les déplacements des personnes aux revenus limités.", "La seconde souligne toutefois la difficulté de financer durablement cette mesure.", "Les documents opposent ainsi un objectif d'égalité à une question de financement."], acceptedAnswers: [], explanation: "L'ordre permet de restituer les deux sources et de dégager leur opposition principale.", targetLanguageFeature: "résumé de deux points de vue", tags: ["reformulation", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-faithful-synthesis", prompt: "La première source défend l'installation de fontaines publiques pour réduire les bouteilles en plastique. La seconde craint le coût de leur entretien.", instructions: "Rédigez 3 ou 4 phrases : reformulez fidèlement chaque idée, attribuez-la au bon document et terminez par une phrase qui indique le débat commun.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le but est de restituer les sources avec vos propres mots, sans les confondre ni ajouter votre avis.", targetLanguageFeature: "synthèse guidée et fidèle", tags: ["reformulation", "development", "sources"], selfCheck: ["J'attribue clairement chaque idée à une source.", "Je reformule sans reprendre des expressions entières.", "Ma dernière phrase relie les deux idées sans introduire mon opinion."] },
      { subSkill: "guided-faithful-synthesis-alternative", prompt: "Une source soutient les cours de musique obligatoires à l'école pour favoriser la créativité. L'autre estime que les élèves ont déjà un emploi du temps trop chargé.", instructions: "Rédigez 3 ou 4 phrases qui reformulent les deux positions et font apparaître le point de désaccord.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une bonne synthèse B2 fait comprendre le désaccord tout en respectant les deux documents.", targetLanguageFeature: "reformulation de deux positions", tags: ["reformulation", "development", "variant"], selfCheck: ["Les deux points de vue sont présentés de manière distincte.", "Je garde les idées importantes sans ajouter d'argument personnel.", "Le désaccord est formulé clairement dans une phrase de synthèse."] },
    ],
    [
      { subSkill: "independent-faithful-synthesis", prompt: "Deux sources débattent de la création de marchés de producteurs dans les quartiers : l'une met en avant les produits locaux et les rencontres, l'autre s'inquiète des prix pour certains habitants.", instructions: "Rédigez 60 à 80 mots : reformulez les deux idées avec vos propres mots, attribuez-les clairement et indiquez l'enjeu qui les oppose, sans donner encore votre avis.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production B2 autonome doit laisser au lecteur la possibilité de reconnaître les deux sources avant votre prise de position.", targetLanguageFeature: "synthèse autonome de deux sources", tags: ["reformulation", "production", "sources"], selfCheck: ["Les deux sources sont clairement distinguées.", "Je reformule les idées principales sans les déformer.", "Je ne donne pas encore mon opinion personnelle."] },
      { subSkill: "independent-faithful-synthesis-alternative", prompt: "Deux documents discutent de la rénovation énergétique obligatoire des logements : l'un souligne les économies d'énergie, l'autre craint la charge financière pour les propriétaires.", instructions: "Rédigez 60 à 80 mots qui présentent fidèlement les deux points de vue et le débat commun, sans choisir encore une solution.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une synthèse réussie conserve l'équilibre entre les sources et prépare la future prise de position.", targetLanguageFeature: "synthèse autonome équilibrée", tags: ["reformulation", "production", "variant"], selfCheck: ["Chaque source est présentée de façon fidèle et équilibrée.", "Je reformule les idées avec mes propres mots.", "Je fais apparaître l'enjeu commun sans annoncer ma conclusion."] },
    ],
  ]),
  ...taskThreeB2Path("t3-b2-identifying-arguments", "identifying-arguments", [
    [
      { subSkill: "argument-or-topic", prompt: "Une source soutient que les bibliothèques devraient ouvrir le dimanche parce que beaucoup de personnes travaillent du lundi au samedi.", instructions: "Choisissez l'argument avancé dans cette phrase.", options: ["Les bibliothèques sont des lieux calmes.", "Beaucoup de personnes n'ont pas accès à la bibliothèque en semaine à cause de leur travail.", "Le dimanche est le dernier jour de la semaine.", "Les bibliothèques possèdent de nombreux livres."], correctAnswer: "Beaucoup de personnes n'ont pas accès à la bibliothèque en semaine à cause de leur travail.", acceptedAnswers: [], explanation: "Un argument donne une raison qui soutient une position. Ici, l'accès limité en semaine explique la demande d'ouverture le dimanche.", targetLanguageFeature: "repérage d'un argument et de sa raison", tags: ["arguments", "sources", "recognize"] },
      { subSkill: "argument-or-topic-alternative", prompt: "Une source défend les repas végétariens à la cantine, car ils peuvent réduire l'impact environnemental des repas scolaires.", instructions: "Identifiez l'argument qui justifie cette position.", options: ["Les cantines servent des repas chaque jour.", "Réduire l'impact environnemental est une raison de proposer davantage de repas végétariens.", "Les élèves aiment tous les légumes.", "Un repas végétarien ne contient pas de viande."], correctAnswer: "Réduire l'impact environnemental est une raison de proposer davantage de repas végétariens.", acceptedAnswers: [], explanation: "L'argument répond à la question « pourquoi ? » : il donne un effet positif qui soutient la proposition.", targetLanguageFeature: "relation entre position et justification", tags: ["arguments", "recognize", "variant"] },
    ],
    [
      { subSkill: "complete-argument-link", prompt: "Une source veut limiter les voitures près des écoles pour protéger les enfants.", instructions: "Complétez l'argument : « Cette mesure est utile, car elle ______ le risque d'accident aux heures d'entrée et de sortie. »", options: [], correctAnswer: "réduit", acceptedAnswers: ["diminue", "limite"], explanation: "Le verbe complète une raison concrète : la mesure est soutenue par son effet sur la sécurité.", targetLanguageFeature: "justification par une conséquence concrète", tags: ["arguments", "complete", "cause"] },
      { subSkill: "complete-argument-link-alternative", prompt: "Une source défend l'installation de fontaines publiques.", instructions: "Complétez : « Selon le document, ces fontaines permettraient de ______ les achats de bouteilles en plastique. »", options: [], correctAnswer: "réduire", acceptedAnswers: ["limiter", "diminuer"], explanation: "L'argument relie la mesure proposée à un bénéfice précis : moins de déchets plastiques.", targetLanguageFeature: "mesure et effet attendu", tags: ["arguments", "complete", "variant"] },
    ],
    [
      { subSkill: "fact-to-argument", prompt: "Une source écrit : « Dans notre ville, les bus sont moins fréquents après 20 heures. »", instructions: "Transformez ce constat en un argument en faveur de bus plus fréquents le soir.", options: [], correctAnswer: null, acceptedAnswers: ["Il faudrait augmenter la fréquence des bus le soir, car les habitants ont actuellement peu de possibilités pour rentrer après 20 heures.", "Puisque les bus sont rares après 20 heures, une meilleure fréquence le soir permettrait aux habitants de se déplacer plus facilement."], explanation: "Le constat devient un argument lorsqu'il est relié à une mesure et à une raison pour cette mesure.", targetLanguageFeature: "passage d'un fait à une justification", tags: ["arguments", "transform", "evidence"] },
      { subSkill: "fact-to-argument-alternative", prompt: "Une source indique : « Beaucoup de logements anciens perdent de la chaleur en hiver. »", instructions: "Reformulez cette information comme un argument pour encourager la rénovation énergétique.", options: [], correctAnswer: null, acceptedAnswers: ["Il faudrait encourager la rénovation énergétique, car de nombreux logements anciens perdent encore beaucoup de chaleur en hiver.", "La rénovation des logements anciens devrait être soutenue puisqu'elle permettrait de limiter les pertes de chaleur en hiver."], explanation: "Une transformation réussie garde le fait, puis montre clairement la conclusion ou la mesure qu'il soutient.", targetLanguageFeature: "fait observé et proposition justifiée", tags: ["arguments", "transform", "variant"] },
    ],
    [
      { subSkill: "claim-reason-example-order", prompt: "Une source défend l'ouverture des gymnases municipaux le soir.", instructions: "Mettez les éléments dans l'ordre pour faire apparaître clairement la position, sa raison et son exemple.", options: ["Par exemple, une personne qui finit son travail à 18 h pourrait encore pratiquer une activité sportive.", "Les gymnases municipaux devraient rester ouverts plus tard.", "De nombreux habitants ne peuvent pas y aller pendant les horaires actuels à cause de leur travail."], correctAnswer: ["Les gymnases municipaux devraient rester ouverts plus tard.", "De nombreux habitants ne peuvent pas y aller pendant les horaires actuels à cause de leur travail.", "Par exemple, une personne qui finit son travail à 18 h pourrait encore pratiquer une activité sportive."], acceptedAnswers: [], explanation: "L'argument est plus lisible quand on annonce la position, qu'on explique pourquoi, puis qu'on l'illustre.", targetLanguageFeature: "position → raison → exemple", tags: ["arguments", "organize", "sources"] },
      { subSkill: "claim-reason-example-order-alternative", prompt: "Une source souhaite développer les jardins partagés dans les quartiers.", instructions: "Organisez son argumentation.", options: ["Ainsi, des voisins qui ne se connaissent pas peuvent se rencontrer et organiser des activités communes.", "Les jardins partagés devraient être davantage soutenus par les villes.", "Ils créent des occasions concrètes de contact entre les habitants."], correctAnswer: ["Les jardins partagés devraient être davantage soutenus par les villes.", "Ils créent des occasions concrètes de contact entre les habitants.", "Ainsi, des voisins qui ne se connaissent pas peuvent se rencontrer et organiser des activités communes."], acceptedAnswers: [], explanation: "La dernière phrase illustre la raison avancée ; elle ne remplace pas la position de départ.", targetLanguageFeature: "identification de la fonction de chaque idée", tags: ["arguments", "organize", "variant"] },
    ],
    [
      { subSkill: "guided-argument-analysis", prompt: "La première source veut interdire les téléphones pendant les cours, car ils distraient les élèves. La seconde préfère apprendre aux élèves à les utiliser de manière responsable, car ils peuvent aussi servir à rechercher des informations.", instructions: "Rédigez 3 ou 4 phrases : indiquez la position de chaque source, l'argument principal qui la soutient et ce qui les oppose.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "À ce stade, vous ne donnez pas encore votre avis : vous montrez comment chaque source relie une position à une raison.", targetLanguageFeature: "analyse guidée de deux arguments", tags: ["arguments", "develop", "sources"], selfCheck: ["J'identifie séparément la position de chaque source.", "J'explique la raison qui soutient chaque position.", "Je formule clairement le point de désaccord."] },
      { subSkill: "guided-argument-analysis-alternative", prompt: "Un document propose de rendre les musées gratuits certains jours afin que les familles aux revenus limités puissent y accéder. L'autre craint que cette mesure réduise les ressources nécessaires à l'entretien des collections.", instructions: "Présentez les deux arguments en 3 ou 4 phrases, sans choisir encore l'un des deux.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une analyse B2 distingue le but recherché par chaque source et la raison donnée, sans transformer l'un des arguments en opinion personnelle.", targetLanguageFeature: "raison et conséquence dans deux positions", tags: ["arguments", "develop", "variant"], selfCheck: ["Je précise le bénéfice recherché par la première source.", "Je nomme la difficulté évoquée par la seconde source.", "Je n'ajoute pas encore ma préférence personnelle."] },
    ],
    [
      { subSkill: "independent-argument-analysis", prompt: "Deux sources discutent de la création d'un abonnement de vélos en libre-service. La première soutient que cela aiderait les habitants qui ne possèdent pas de voiture ; la seconde estime que le coût d'entretien pourrait être trop élevé pour la ville.", instructions: "Rédigez 60 à 80 mots qui identifient la position et l'argument principal de chaque source, puis expliquent en une phrase ce qui les oppose. Ne donnez pas votre avis.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une analyse autonome B2 permet au lecteur de reconnaître la logique des deux arguments avant toute prise de position.", targetLanguageFeature: "identification autonome d'arguments opposés", tags: ["arguments", "produce", "sources"], selfCheck: ["J'attribue chaque position au bon document.", "Je formule la raison principale de chaque argument.", "J'explique le désaccord sans donner mon opinion."] },
      { subSkill: "independent-argument-analysis-alternative", prompt: "Deux documents parlent de repas gratuits à l'école. Le premier insiste sur l'égalité entre les élèves ; le second rappelle que la mesure demanderait un budget important aux collectivités.", instructions: "Rédigez 60 à 80 mots qui présentent les deux arguments et l'opposition principale entre eux, sans défendre encore une solution.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le texte doit faire comprendre pourquoi les deux documents n'arrivent pas à la même conclusion, tout en restant fidèle à chacun.", targetLanguageFeature: "analyse autonome d'une opposition argumentative", tags: ["arguments", "produce", "variant"], selfCheck: ["Les deux arguments sont présentés de manière équilibrée.", "Je relie chaque argument à sa position.", "Le conflit entre égalité et coût est clair."] },
    ],
  ]),
  ...taskThreeB2Path("t3-b2-comparing-viewpoints", "comparing-viewpoints", [
    [
      { subSkill: "identify-difference", prompt: "Une source soutient les cours en ligne parce qu'ils évitent de longs trajets. L'autre préfère les cours en classe parce qu'ils facilitent les échanges avec le professeur.", instructions: "Choisissez la phrase qui compare fidèlement les deux points de vue.", options: ["Les deux sources sont totalement d'accord sur les cours en ligne.", "La première valorise la souplesse des cours en ligne, tandis que la seconde insiste sur l'importance du contact direct en classe.", "La première source déteste les professeurs.", "Les cours en ligne sont toujours meilleurs."], correctAnswer: "La première valorise la souplesse des cours en ligne, tandis que la seconde insiste sur l'importance du contact direct en classe.", acceptedAnswers: [], explanation: "Comparer consiste à présenter les deux critères différents sans déformer l'une des sources.", targetLanguageFeature: "opposition avec tandis que", tags: ["comparison", "sources", "recognize"] },
      { subSkill: "identify-difference-alternative", prompt: "Un document veut limiter les voitures en centre-ville pour réduire la pollution. Un autre craint les difficultés pour les commerçants qui reçoivent des livraisons.", instructions: "Choisissez la meilleure comparaison.", options: ["Les deux documents refusent toute limitation.", "Le premier privilégie la qualité de l'air, alors que le second met l'accent sur les contraintes des commerces.", "Les commerçants sont responsables de la pollution.", "La circulation est un sujet sans importance."], correctAnswer: "Le premier privilégie la qualité de l'air, alors que le second met l'accent sur les contraintes des commerces.", acceptedAnswers: [], explanation: "La phrase compare le critère principal de chaque source : environnement d'un côté, activité économique de l'autre.", targetLanguageFeature: "comparaison de deux priorités", tags: ["comparison", "recognize", "variant"] },
    ],
    [
      { subSkill: "comparison-connector", prompt: "Une source défend les jardins partagés pour créer du lien social. L'autre craint les dépenses d'entretien.", instructions: "Complétez : « La première insiste sur les relations entre habitants, ______ la seconde met en avant le coût du projet. »", options: [], correctAnswer: "tandis que", acceptedAnswers: ["alors que"], explanation: "« Tandis que » met en regard deux idées différentes sans dire que l'une est forcément fausse.", targetLanguageFeature: "connecteur de comparaison", tags: ["comparison", "complete", "connectors"] },
      { subSkill: "comparison-connector-alternative", prompt: "Un document présente la gratuité des transports comme une aide pour les personnes modestes. Un autre s'interroge sur son financement.", instructions: "Complétez : « Le premier document défend un objectif d'égalité, ______ le second souligne une limite financière. »", options: [], correctAnswer: "alors que", acceptedAnswers: ["tandis que"], explanation: "Le connecteur relie deux points de vue distincts et prépare une synthèse équilibrée.", targetLanguageFeature: "mise en regard de deux arguments", tags: ["comparison", "complete", "variant"] },
    ],
    [
      { subSkill: "two-sentences-to-comparison", prompt: "Transformez : « La première source veut installer des fontaines publiques. Elle veut réduire les bouteilles en plastique. La seconde préfère améliorer le tri des déchets. Elle pense que cela coûte moins cher. »", instructions: "Réunissez ces idées dans une phrase qui compare les deux solutions.", options: [], correctAnswer: null, acceptedAnswers: ["La première source propose des fontaines pour réduire les bouteilles en plastique, tandis que la seconde préfère améliorer le tri, une solution qu'elle juge moins coûteuse.", "Alors que le premier document mise sur des fontaines afin de limiter les bouteilles, le second privilégie le tri des déchets pour des raisons de coût."], explanation: "La comparaison réunit les deux solutions et la raison principale de chaque source dans une phrase organisée.", targetLanguageFeature: "synthèse comparative de deux solutions", tags: ["comparison", "transform", "sources"] },
      { subSkill: "two-sentences-to-comparison-alternative", prompt: "Transformez : « Le premier document veut ouvrir les bibliothèques le dimanche. Il pense que les salariés pourraient y aller. Le second préfère garder les horaires actuels. Il craint des frais supplémentaires. »", instructions: "Formulez une phrase de comparaison fidèle aux deux documents.", options: [], correctAnswer: null, acceptedAnswers: ["Le premier document défend l'ouverture le dimanche pour permettre aux salariés d'accéder aux bibliothèques, alors que le second redoute les coûts supplémentaires de cette mesure.", "Tandis que la première source met l'accent sur l'accès des salariés, la seconde préfère les horaires actuels en raison des dépenses possibles."], explanation: "Une comparaison claire fait apparaître le bénéfice recherché et la réserve formulée, sans ajouter un jugement personnel.", targetLanguageFeature: "comparaison d'un avantage et d'une limite", tags: ["comparison", "transform", "variant"] },
    ],
    [
      { subSkill: "common-point-and-difference-order", prompt: "Deux documents parlent de la rénovation des logements. Tous deux veulent réduire les dépenses d'énergie ; le premier demande une aide publique, le second préfère laisser les propriétaires choisir.", instructions: "Organisez ces phrases pour présenter d'abord le point commun, puis la différence.", options: ["En revanche, ils ne proposent pas la même manière d'y parvenir.", "Les deux sources souhaitent limiter la consommation d'énergie des logements.", "La première demande des aides publiques, tandis que la seconde privilégie la liberté de décision des propriétaires."], correctAnswer: ["Les deux sources souhaitent limiter la consommation d'énergie des logements.", "En revanche, ils ne proposent pas la même manière d'y parvenir.", "La première demande des aides publiques, tandis que la seconde privilégie la liberté de décision des propriétaires."], acceptedAnswers: [], explanation: "Une comparaison équilibrée peut montrer un accord sur le but avant d'expliquer le désaccord sur la solution.", targetLanguageFeature: "point commun → différence → précision", tags: ["comparison", "organize", "sources"] },
      { subSkill: "common-point-and-difference-order-alternative", prompt: "Deux documents veulent améliorer la vie dans les quartiers. L'un propose davantage d'activités gratuites, l'autre préfère développer les espaces verts.", instructions: "Mettez les phrases dans l'ordre.", options: ["Cependant, ils n'identifient pas le même moyen pour atteindre cet objectif.", "Les deux documents cherchent à rendre les quartiers plus agréables pour les habitants.", "Le premier mise sur des activités accessibles, alors que le second donne la priorité aux parcs et aux jardins."], correctAnswer: ["Les deux documents cherchent à rendre les quartiers plus agréables pour les habitants.", "Cependant, ils n'identifient pas le même moyen pour atteindre cet objectif.", "Le premier mise sur des activités accessibles, alors que le second donne la priorité aux parcs et aux jardins."], acceptedAnswers: [], explanation: "L'organisation rend visible ce que les sources partagent avant de préciser ce qui les sépare.", targetLanguageFeature: "comparaison accord et désaccord", tags: ["comparison", "organize", "variant"] },
    ],
    [
      { subSkill: "guided-viewpoint-comparison", prompt: "Une source propose de rendre les transports publics gratuits le week-end pour faciliter les sorties des familles et des jeunes. L'autre préfère réduire le prix des abonnements mensuels, car cette mesure aiderait aussi les personnes qui se déplacent tous les jours.", instructions: "Rédigez 3 ou 4 phrases : présentez leur objectif commun, comparez les solutions et expliquez à quels usagers chacune donne la priorité. Ne donnez pas encore votre avis.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Vous apprenez à comparer les documents selon leur solution et le public auquel ils s'adressent, sans choisir à leur place.", targetLanguageFeature: "comparaison guidée de solutions et de publics", tags: ["comparison", "develop", "sources"], selfCheck: ["Je nomme l'objectif commun des deux sources.", "Je distingue clairement les deux solutions proposées.", "Je précise le public prioritaire pour chaque source."] },
      { subSkill: "guided-viewpoint-comparison-alternative", prompt: "Le premier document veut créer des repas végétariens chaque jour à la cantine pour réduire l'impact environnemental. Le second accepte cette idée, mais seulement deux fois par semaine afin de préserver le choix des familles.", instructions: "Comparez les deux positions en 3 ou 4 phrases : indiquez l'accord, la différence de rythme proposé et la raison mise en avant par chaque source.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Comparer ne signifie pas seulement opposer : les deux sources peuvent partager un objectif tout en proposant des moyens différents.", targetLanguageFeature: "accord partiel et différence de solution", tags: ["comparison", "develop", "variant"], selfCheck: ["Je fais apparaître le point d'accord entre les sources.", "Je précise la différence entre tous les jours et deux fois par semaine.", "Je n'ajoute pas encore mon avis personnel."] },
    ],
    [
      { subSkill: "independent-viewpoint-comparison", prompt: "Deux documents discutent de l'installation de casiers de retrait de colis dans les quartiers. Le premier y voit un moyen pratique de récupérer un colis à toute heure ; le second préfère soutenir les petits commerces, qui peuvent aussi servir de points de retrait et garder du contact avec les habitants.", instructions: "Rédigez 60 à 80 mots qui comparent l'objectif, la solution et le public privilégié par chaque document. Terminez par leur principale différence, sans donner votre avis.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une comparaison B2 autonome permet de voir que les sources peuvent chercher à faciliter un service tout en donnant la priorité à des usages différents.", targetLanguageFeature: "comparaison autonome de critères", tags: ["comparison", "produce", "sources"], selfCheck: ["Je compare les deux solutions sans les confondre.", "Je précise ce que chaque source considère comme prioritaire.", "Ma dernière phrase résume leur différence principale."] },
      { subSkill: "independent-viewpoint-comparison-alternative", prompt: "Deux sources discutent de l'organisation de cours de sport après l'école. L'une propose des séances gratuites dans les établissements pour que tous les élèves puissent participer. L'autre préfère aider les associations locales qui offrent des activités variées le soir.", instructions: "Rédigez 60 à 80 mots qui mettent en regard les objectifs communs, les deux solutions et leurs différences, sans choisir encore l'une des deux.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le lecteur doit pouvoir identifier à la fois l'intention partagée et les priorités distinctes des deux documents.", targetLanguageFeature: "mise en regard autonome de deux points de vue", tags: ["comparison", "produce", "variant"], selfCheck: ["J'indique l'objectif que les deux sources ont en commun.", "Je présente la solution de chaque source de façon fidèle.", "Je termine par une comparaison claire plutôt que par mon opinion."] },
    ],
  ]),
  ...taskThreeB2Path("t3-b2-synthesizing", "synthesizing", [
    [
      { subSkill: "shared-debate-summary", prompt: "Une source soutient les bibliothèques ouvertes le dimanche pour faciliter l'accès des salariés. L'autre craint les coûts d'ouverture supplémentaires.", instructions: "Choisissez la phrase qui synthétise le débat sans donner votre avis.", options: ["Les bibliothèques doivent ouvrir le dimanche.", "Les deux sources opposent un meilleur accès aux bibliothèques à la question de leur financement.", "Les salariés ont toujours raison.", "Les coûts ne sont jamais importants."], correctAnswer: "Les deux sources opposent un meilleur accès aux bibliothèques à la question de leur financement.", acceptedAnswers: [], explanation: "Une synthèse B2 relie les idées principales dans une phrase neutre qui fait apparaître l'enjeu commun.", targetLanguageFeature: "synthèse neutre d'un désaccord", tags: ["synthesis", "sources", "recognize"] },
      { subSkill: "shared-debate-summary-alternative", prompt: "Un document souhaite réduire les voitures en ville pour améliorer l'air. L'autre veut préserver les possibilités de livraison pour les commerces.", instructions: "Identifiez la meilleure phrase de synthèse.", options: ["Les voitures sont interdites partout.", "Les documents mettent en balance la réduction de la pollution et les besoins pratiques des commerces.", "Les commerces ne devraient pas recevoir de livraisons.", "L'air est toujours pollué."], correctAnswer: "Les documents mettent en balance la réduction de la pollution et les besoins pratiques des commerces.", acceptedAnswers: [], explanation: "La synthèse ne répète pas chaque phrase : elle nomme le point de tension qui relie les deux sources.", targetLanguageFeature: "enjeu commun de deux sources", tags: ["synthesis", "recognize", "variant"] },
    ],
    [
      { subSkill: "synthesis-connector", prompt: "Une source présente les jardins partagés comme un lieu de rencontre. L'autre souligne le travail nécessaire pour les entretenir.", instructions: "Complétez : « Dans l'ensemble, les documents montrent que les jardins partagés peuvent créer du lien, mais qu'ils demandent aussi ______. »", options: [], correctAnswer: "une organisation régulière", acceptedAnswers: ["un entretien suivi", "des moyens pour être entretenus"], explanation: "La formule rassemble un avantage et une limite dans une même phrase de synthèse.", targetLanguageFeature: "bilan nuancé par mais", tags: ["synthesis", "complete", "connectors"] },
      { subSkill: "synthesis-connector-alternative", prompt: "Un document voit les cours en ligne comme une solution souple. L'autre rappelle qu'ils peuvent isoler certains étudiants.", instructions: "Complétez : « Ces deux points de vue montrent que l'enseignement à distance offre de la flexibilité, tout en ______ pour certains étudiants. »", options: [], correctAnswer: "présentant un risque d'isolement", acceptedAnswers: ["risquant d'isoler certains étudiants", "pouvant limiter les échanges"], explanation: "La construction « tout en » permet de relier l'avantage et la réserve sans prendre encore position.", targetLanguageFeature: "mise en relation d'un avantage et d'une limite", tags: ["synthesis", "complete", "variant"] },
    ],
    [
      { subSkill: "list-to-synthesis", prompt: "Reformulez ces idées en une phrase de synthèse : « Les transports gratuits aideraient les personnes aux revenus faibles. Cette mesure coûterait cher aux villes. »", instructions: "Reliez l'avantage et la limite sans dire si vous êtes pour ou contre.", options: [], correctAnswer: null, acceptedAnswers: ["La gratuité des transports pourrait faciliter les déplacements des personnes aux revenus faibles, mais elle poserait la question de son financement par les villes.", "Cette mesure favoriserait l'accès aux transports pour certains habitants tout en représentant un coût important pour les collectivités."], explanation: "La synthèse garde les deux idées et les relie ; elle ne choisit pas encore laquelle est la plus importante.", targetLanguageFeature: "reformulation synthétique avantage-limite", tags: ["synthesis", "transform", "sources"] },
      { subSkill: "list-to-synthesis-alternative", prompt: "Reformulez : « Les repas végétariens peuvent réduire l'impact écologique. Certaines familles souhaitent garder plusieurs choix de menus. »", instructions: "Écrivez une phrase de synthèse équilibrée.", options: [], correctAnswer: null, acceptedAnswers: ["Les repas végétariens peuvent réduire l'impact écologique, mais leur développement doit aussi tenir compte du souhait des familles de conserver différents choix.", "Les documents mettent en avant un bénéfice environnemental tout en rappelant l'importance de proposer des options variées."], explanation: "Le texte de synthèse fait tenir ensemble les idées compatibles ou opposées sans les caricaturer.", targetLanguageFeature: "bilan équilibré de deux idées", tags: ["synthesis", "transform", "variant"] },
    ],
    [
      { subSkill: "source-one-source-two-balance-order", prompt: "Deux documents parlent des activités sportives après l'école : le premier veut des séances gratuites dans les établissements ; le second préfère soutenir les associations locales, qui offrent plus de choix.", instructions: "Mettez les phrases dans l'ordre d'une courte synthèse avant de donner un avis.", options: ["Ainsi, les deux sources cherchent à faciliter l'accès au sport, mais elles ne privilégient pas le même cadre.", "La première défend des activités gratuites directement à l'école.", "La seconde mise sur les associations locales afin de proposer des pratiques plus variées."], correctAnswer: ["La première défend des activités gratuites directement à l'école.", "La seconde mise sur les associations locales afin de proposer des pratiques plus variées.", "Ainsi, les deux sources cherchent à faciliter l'accès au sport, mais elles ne privilégient pas le même cadre."], acceptedAnswers: [], explanation: "On restitue les deux apports avant de dégager leur point commun et leur différence principale.", targetLanguageFeature: "source 1 → source 2 → bilan", tags: ["synthesis", "organize", "sources"] },
      { subSkill: "source-one-source-two-balance-order-alternative", prompt: "Deux documents discutent de la rénovation énergétique : l'un demande des aides publiques ; l'autre préfère laisser les propriétaires décider selon leur budget.", instructions: "Organisez ces phrases pour produire une synthèse neutre.", options: ["Les deux documents reconnaissent donc l'intérêt de réduire la consommation d'énergie, même s'ils divergent sur le rôle des pouvoirs publics.", "Le premier considère que les aides sont nécessaires pour encourager les travaux.", "Le second insiste sur la liberté des propriétaires de choisir le moment des rénovations."], correctAnswer: ["Le premier considère que les aides sont nécessaires pour encourager les travaux.", "Le second insiste sur la liberté des propriétaires de choisir le moment des rénovations.", "Les deux documents reconnaissent donc l'intérêt de réduire la consommation d'énergie, même s'ils divergent sur le rôle des pouvoirs publics."], acceptedAnswers: [], explanation: "La dernière phrase met en évidence l'accord de fond et le désaccord sur les moyens.", targetLanguageFeature: "synthèse accord et divergence", tags: ["synthesis", "organize", "variant"] },
    ],
    [
      { subSkill: "guided-neutral-synthesis", prompt: "Une source défend des fontaines publiques pour limiter l'achat de bouteilles en plastique. L'autre estime qu'il faudrait d'abord améliorer la collecte et le tri des déchets, moins coûteux selon elle.", instructions: "Rédigez 3 ou 4 phrases : reformulez chaque solution, expliquez l'avantage recherché par chacune et terminez par l'enjeu commun. Ne donnez pas votre avis.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La synthèse guidée prépare la prise de position : elle montre que vous avez compris les sources avant de les évaluer.", targetLanguageFeature: "synthèse guidée de solutions distinctes", tags: ["synthesis", "develop", "sources"], selfCheck: ["Je présente les deux solutions de façon fidèle.", "Je précise la raison principale de chaque source.", "Je termine par l'enjeu commun sans donner mon opinion."] },
      { subSkill: "guided-neutral-synthesis-alternative", prompt: "Le premier document veut ouvrir les musées gratuitement une fois par mois pour accueillir davantage de familles. Le second accepte l'idée, mais rappelle qu'il faut prévoir un financement pour maintenir les collections et les services.", instructions: "Rédigez 3 ou 4 phrases de synthèse équilibrée avant toute prise de position.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une bonne synthèse B2 relie le désir d'accès à la culture à la condition concrète évoquée par l'autre source.", targetLanguageFeature: "bilan guidé d'un avantage et d'une condition", tags: ["synthesis", "develop", "variant"], selfCheck: ["J'attribue clairement l'idée d'accès à la première source.", "Je formule la condition de financement de la seconde.", "Je garde une formulation neutre et équilibrée."] },
    ],
    [
      { subSkill: "independent-neutral-synthesis", prompt: "Deux sources discutent des marchés de producteurs dans les quartiers. L'une souligne l'intérêt des produits locaux et des rencontres entre habitants. L'autre s'inquiète de prix qui pourraient exclure certains publics.", instructions: "Rédigez 60 à 80 mots qui synthétisent les deux points de vue, leur objectif ou enjeu commun et leur principale opposition. Ne donnez pas encore votre avis.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une synthèse autonome B2 doit être assez claire pour qu'un lecteur comprenne le débat avant de découvrir votre position.", targetLanguageFeature: "synthèse autonome équilibrée", tags: ["synthesis", "produce", "sources"], selfCheck: ["Je restitue l'idée principale de chaque source.", "Je fais apparaître l'enjeu commun ou la tension principale.", "Je ne formule pas encore mon opinion personnelle."] },
      { subSkill: "independent-neutral-synthesis-alternative", prompt: "Deux documents débattent de la création de zones sans voiture près des écoles. Le premier insiste sur la sécurité des enfants ; le second craint les difficultés de déplacement pour certains parents.", instructions: "Rédigez 60 à 80 mots qui présentent fidèlement les deux points de vue et résument le débat, sans choisir encore une solution.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le résultat doit faire comprendre les bénéfices attendus et la contrainte mise en avant, sans transformer la synthèse en argument personnel.", targetLanguageFeature: "synthèse autonome d'un débat local", tags: ["synthesis", "produce", "variant"], selfCheck: ["Je présente les deux sources avec mes propres mots.", "Le bénéfice et la difficulté sont tous deux visibles.", "Je termine par le débat commun, pas par ma préférence."] },
    ],
  ]),
  ...taskThreeB2Path("t3-b2-taking-position", "taking-position", [
    [
      { subSkill: "clear-position-after-sources", prompt: "Après avoir résumé deux sources sur les transports gratuits le week-end, vous souhaitez donner votre avis.", instructions: "Choisissez la phrase qui annonce une position claire et personnelle.", options: ["Les documents parlent des transports.", "Après avoir examiné ces deux points de vue, je pense que la gratuité le week-end serait une mesure utile, à condition que son financement soit prévu.", "Les transports existent dans les villes.", "La première source a écrit un document."], correctAnswer: "Après avoir examiné ces deux points de vue, je pense que la gratuité le week-end serait une mesure utile, à condition que son financement soit prévu.", acceptedAnswers: [], explanation: "La phrase sépare l'analyse des sources de votre propre position et annonce déjà une condition importante.", targetLanguageFeature: "prise de position explicite après synthèse", tags: ["position", "sources", "recognize"] },
      { subSkill: "clear-position-after-sources-alternative", prompt: "Vous avez présenté deux opinions sur les repas végétariens à la cantine.", instructions: "Choisissez la meilleure transition vers votre position.", options: ["Les repas sont mangés à midi.", "Pour ma part, je serais favorable à davantage de menus végétariens, tout en maintenant plusieurs options pour respecter les choix des familles.", "Les deux documents sont longs.", "Les familles ont des opinions."], correctAnswer: "Pour ma part, je serais favorable à davantage de menus végétariens, tout en maintenant plusieurs options pour respecter les choix des familles.", acceptedAnswers: [], explanation: "La formule annonce clairement votre point de vue sans faire disparaître la préoccupation évoquée par l'autre source.", targetLanguageFeature: "position personnelle avec réserve", tags: ["position", "recognize", "variant"] },
    ],
    [
      { subSkill: "position-marker", prompt: "Vous choisissez votre position après avoir comparé deux sources sur les jardins partagés.", instructions: "Complétez : « Après avoir considéré ces arguments, ______ que les villes devraient soutenir ces projets. »", options: [], correctAnswer: "j'estime", acceptedAnswers: ["je pense", "je considère"], explanation: "Le marqueur personnel indique clairement que vous passez de la synthèse à votre propre jugement.", targetLanguageFeature: "verbe d'opinion explicite", tags: ["position", "complete", "opinion"] },
      { subSkill: "position-marker-alternative", prompt: "Vous avez résumé un débat sur les cours de sport après l'école.", instructions: "Complétez : « Pour ma part, je serais ______ à une offre gratuite dans les établissements. »", options: [], correctAnswer: "favorable", acceptedAnswers: ["plutôt favorable", "en faveur"], explanation: "« Être favorable à » permet d'annoncer sa position de manière nette et adaptée à un texte argumentatif.", targetLanguageFeature: "formulation d'une préférence", tags: ["position", "complete", "variant"] },
    ],
    [
      { subSkill: "source-to-own-position", prompt: "Transformez : « La première source souhaite installer des fontaines publiques. »", instructions: "Ajoutez une phrase qui distingue cette idée de votre position personnelle, puis annonce votre avis.", options: [], correctAnswer: null, acceptedAnswers: ["La première source souhaite installer des fontaines publiques. Après avoir examiné cet argument, je pense que cette mesure serait utile pour réduire les déchets plastiques.", "Le document propose des fontaines publiques ; pour ma part, je serais favorable à cette solution, car elle peut limiter l'achat de bouteilles."], explanation: "Vous devez d'abord attribuer l'idée à la source, puis utiliser un marqueur clair pour faire entendre votre propre voix.", targetLanguageFeature: "transition source → position personnelle", tags: ["position", "transform", "sources"] },
      { subSkill: "source-to-own-position-alternative", prompt: "Transformez : « Le second document craint que l'ouverture des bibliothèques le dimanche coûte trop cher. »", instructions: "Gardez cette réserve, mais exprimez ensuite votre position personnelle.", options: [], correctAnswer: null, acceptedAnswers: ["Le second document craint des coûts trop élevés. Pour ma part, je pense que l'ouverture le dimanche reste souhaitable si la ville organise un budget adapté.", "Même si la seconde source souligne le coût, je serais favorable à une ouverture le dimanche, à condition d'en prévoir le financement."], explanation: "Une prise de position B2 peut reconnaître une réserve des sources tout en annonçant clairement ce que vous choisissez.", targetLanguageFeature: "prise de position après une réserve", tags: ["position", "transform", "variant"] },
    ],
    [
      { subSkill: "synthesis-to-position-order", prompt: "Vous terminez une synthèse sur les vélos en libre-service et vous passez à votre avis.", instructions: "Mettez les phrases dans l'ordre : bilan des sources, transition, position personnelle.", options: ["Pour ma part, je serais favorable à ce service s'il est installé dans plusieurs quartiers.", "Les documents reconnaissent tous deux que la mobilité est un enjeu important, mais ils diffèrent sur le coût du projet.", "Après avoir pris en compte ces arguments, il me semble qu'une solution accessible à tous doit être recherchée."], correctAnswer: ["Les documents reconnaissent tous deux que la mobilité est un enjeu important, mais ils diffèrent sur le coût du projet.", "Après avoir pris en compte ces arguments, il me semble qu'une solution accessible à tous doit être recherchée.", "Pour ma part, je serais favorable à ce service s'il est installé dans plusieurs quartiers."], acceptedAnswers: [], explanation: "On clôt la synthèse avant d'annoncer son choix ; le lecteur comprend ainsi à quel moment commence votre argumentation personnelle.", targetLanguageFeature: "organisation synthèse → transition → position", tags: ["position", "organize", "sources"] },
      { subSkill: "synthesis-to-position-order-alternative", prompt: "Vous avez comparé deux idées sur la rénovation des logements.", instructions: "Organisez la fin de la synthèse et le début de votre position.", options: ["À mon avis, des aides ciblées permettraient de concilier économies d'énergie et contraintes financières.", "Les deux sources veulent réduire la consommation d'énergie, mais elles ne donnent pas le même rôle aux pouvoirs publics.", "Après cette comparaison, je considère qu'il faut chercher une mesure qui tienne compte des deux préoccupations."], correctAnswer: ["Les deux sources veulent réduire la consommation d'énergie, mais elles ne donnent pas le même rôle aux pouvoirs publics.", "Après cette comparaison, je considère qu'il faut chercher une mesure qui tienne compte des deux préoccupations.", "À mon avis, des aides ciblées permettraient de concilier économies d'énergie et contraintes financières."], acceptedAnswers: [], explanation: "Cette organisation sépare clairement les idées rapportées de la proposition que vous défendez ensuite.", targetLanguageFeature: "transition ordonnée vers une opinion", tags: ["position", "organize", "variant"] },
    ],
    [
      { subSkill: "guided-position-after-synthesis", prompt: "Deux sources discutent de la gratuité des musées certains jours. L'une veut favoriser l'accès à la culture ; l'autre craint le coût pour les établissements.", instructions: "Après deux phrases qui résument rapidement les sources, rédigez 2 ou 3 phrases qui annoncent votre position. Dites clairement si vous êtes favorable ou non et ajoutez une condition ou une limite simple.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Vous vous entraînez à ne pas confondre les sources avec votre voix : votre position commence après la synthèse et peut reconnaître une limite.", targetLanguageFeature: "position guidée avec condition", tags: ["position", "develop", "sources"], selfCheck: ["Je distingue la synthèse de mon propre avis.", "Ma position est explicite et liée au sujet.", "J'ajoute une condition ou une limite réaliste."] },
      { subSkill: "guided-position-after-synthesis-alternative", prompt: "Deux documents opposent les avantages des cours en ligne à l'importance des échanges en classe.", instructions: "Écrivez 3 ou 4 phrases après la synthèse : annoncez votre choix, reconnaissez brièvement l'idée que vous ne retenez pas entièrement et proposez une solution simple.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une prise de position B2 convaincante ne répète pas seulement une source : elle montre que vous avez considéré les deux points de vue avant de choisir.", targetLanguageFeature: "position guidée après comparaison", tags: ["position", "develop", "variant"], selfCheck: ["J'annonce ma préférence avec un marqueur personnel.", "Je reconnais au moins une idée de l'autre point de vue.", "Je formule une solution cohérente avec mon choix."] },
    ],
    [
      { subSkill: "independent-position-after-synthesis", prompt: "Deux documents débattent de la limitation des voitures au centre-ville. L'un insiste sur la baisse de la pollution ; l'autre évoque les contraintes pour certains commerçants et habitants.", instructions: "Après avoir résumé les deux positions en une ou deux phrases, rédigez un paragraphe de 70 à 90 mots qui annonce votre position personnelle, donne une première raison et propose une condition ou un aménagement. Ne développez pas encore tous vos arguments.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production doit créer une frontière nette entre la synthèse des sources et le début de votre propre réponse argumentée.", targetLanguageFeature: "prise de position autonome et conditionnée", tags: ["position", "produce", "sources"], selfCheck: ["Je sépare les idées des documents de mon avis personnel.", "Ma position est claire dès le début de mon paragraphe.", "Je propose une condition ou un aménagement concret."] },
      { subSkill: "independent-position-after-synthesis-alternative", prompt: "Deux sources discutent des repas végétariens à la cantine : l'une défend leur intérêt écologique, l'autre demande de préserver le choix des familles.", instructions: "Rédigez 70 à 90 mots : faites une courte synthèse, annoncez votre position et ajoutez une condition qui répond à l'une des préoccupations évoquées. Vous développerez les autres arguments plus tard.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Cette étape évalue votre capacité à prendre position après une synthèse, sans effacer la question soulevée par l'autre source.", targetLanguageFeature: "opinion autonome reliée à la synthèse", tags: ["position", "produce", "variant"], selfCheck: ["La synthèse est courte et fidèle aux deux sources.", "Je formule mon avis avec une expression personnelle claire.", "Ma condition répond à une préoccupation présente dans le débat."] },
    ],
  ]),
];
