import type { TaskType } from "@prisma/client";

/**
 * Fixed, reviewed curriculum content for the writing trainer.
 *
 * This module deliberately contains no prompt-generation code. Exercises are
 * authored data: a learner's selection only filters this bank by task, level,
 * and writing micro-skill.
 */
export type PracticeLevel = "B2" | "C1" | "C2";
export const PRACTICE_LEVELS: readonly PracticeLevel[] = ["B2", "C1", "C2"];

export type PracticeExerciseType = "recognize" | "complete" | "transform" | "organize" | "develop" | "produce";
export const PRACTICE_EXERCISE_SEQUENCE: readonly PracticeExerciseType[] = [
  "recognize",
  "complete",
  "transform",
  "organize",
  "develop",
  "produce",
];

export interface PracticeTopic {
  id: string;
  task: TaskType;
  label: string;
  description: string;
  /** The skill is a writing move, never an isolated grammar point. */
  learningGoal: Record<PracticeLevel, string>;
  tags: readonly string[];
}

export interface PracticeExercise {
  id: string;
  task: TaskType;
  level: PracticeLevel;
  skill: string;
  subSkill: string;
  exerciseType: PracticeExerciseType;
  prompt: string;
  instructions: string;
  options: readonly string[];
  correctAnswer: string | readonly string[] | null;
  acceptedAnswers: readonly string[];
  explanation: string;
  targetLanguageFeature: string;
  difficulty: 1 | 2 | 3 | 4 | 5 | 6;
  sequenceOrder: 1 | 2 | 3 | 4 | 5 | 6;
  prerequisiteExerciseId: string | null;
  tags: readonly string[];
  /**
   * Manually authored criteria for open writing. These deliberately replace
   * an automatic correct/incorrect verdict for Develop and Produce steps.
   */
  selfCheck?: readonly string[];
}

const allLevels = (b2: string, c1: string, c2: string): Record<PracticeLevel, string> => ({ B2: b2, C1: c1, C2: c2 });

/**
 * Topic taxonomy. Topics never cross task boundaries: functional messages in
 * Task 1, experience writing for multiple readers in Task 2, and source-aware
 * argumentation in Task 3. A future author can add exercises without changing
 * this contract.
 */
export const PRACTICE_TOPICS: readonly PracticeTopic[] = [
  {
    id: "openings",
    task: "TASK_1",
    label: "Ouvertures",
    description: "Choisir et rédiger une entrée de message adaptée à la situation.",
    learningGoal: allLevels("Commencer clairement un message courant.", "Installer rapidement le contexte et l'intention.", "Ouvrir avec précision, naturel et maîtrise du ton."),
    tags: ["functional-communication", "message"],
  },
  { id: "salutations", task: "TASK_1", label: "Salutations", description: "Adapter la formule de salutation au destinataire.", learningGoal: allLevels("Distinguer une formule familière et une formule neutre.", "Choisir une salutation professionnelle appropriée.", "Ajuster finement la distance relationnelle."), tags: ["functional-communication", "register"] },
  { id: "message-purpose", task: "TASK_1", label: "But du message", description: "Annoncer clairement pourquoi vous écrivez.", learningGoal: allLevels("Exprimer un objectif simple.", "Formuler l'objectif avec contexte et précision.", "Formuler l'objectif avec concision et souplesse."), tags: ["functional-communication", "purpose"] },
  { id: "giving-information", task: "TASK_1", label: "Donner des informations", description: "Transmettre les détails utiles à votre destinataire.", learningGoal: allLevels("Donner les informations essentielles.", "Hiérarchiser et préciser les informations.", "Sélectionner et présenter les informations avec efficacité."), tags: ["functional-communication", "information"] },
  { id: "developing-information", task: "TASK_1", label: "Développer les informations", description: "Ajouter les détails qui rendent un message utile et complet.", learningGoal: allLevels("Ajouter un détail pertinent.", "Développer en anticipant les besoins du lecteur.", "Développer avec une progression naturelle et ciblée."), tags: ["functional-communication", "development"] },
  { id: "asking-information", task: "TASK_1", label: "Demander des informations", description: "Poser des questions précises et adaptées au contexte.", learningGoal: allLevels("Poser une question claire.", "Formuler plusieurs demandes de manière structurée.", "Obtenir les précisions nécessaires avec tact et efficacité."), tags: ["functional-communication", "questions"] },
  { id: "making-requests", task: "TASK_1", label: "Faire une demande", description: "Formuler une demande claire, polie et réaliste.", learningGoal: allLevels("Faire une demande directe et polie.", "Moduler une demande selon la relation.", "Formuler une demande délicate avec diplomatie."), tags: ["functional-communication", "requests"] },
  { id: "suggestions-invitations", task: "TASK_1", label: "Suggestions et invitations", description: "Proposer une action et inviter le destinataire à y répondre.", learningGoal: allLevels("Faire une proposition simple.", "Justifier une suggestion et laisser une marge de choix.", "Formuler une invitation engageante et flexible."), tags: ["functional-communication", "suggestions"] },
  { id: "register", task: "TASK_1", label: "Registre", description: "Adapter le ton au destinataire et à la situation.", learningGoal: allLevels("Distinguer le familier du formel.", "Maintenir un registre cohérent dans tout le message.", "Contrôler les nuances de politesse et de proximité."), tags: ["functional-communication", "register"] },
  { id: "closing-message", task: "TASK_1", label: "Clore le message", description: "Terminer avec une formule et une action attendue appropriées.", learningGoal: allLevels("Terminer un message de façon claire.", "Conclure en rappelant l'action ou l'échéance.", "Conclure avec une formule naturelle et parfaitement calibrée."), tags: ["functional-communication", "closing"] },

  { id: "format-and-audience", task: "TASK_2", label: "Format et destinataires", description: "Choisir un blog, un e-mail ou une note pour raconter une expérience à plusieurs lecteurs.", learningGoal: allLevels("Identifier le format et les lecteurs visés.", "Adapter le point de vue et le ton au support.", "Exploiter les codes du support avec naturel et précision."), tags: ["experience", "audience", "format"] },
  { id: "introducing-experience", task: "TASK_2", label: "Introduire une expérience", description: "Situer l'expérience, son contexte et son intérêt pour les lecteurs.", learningGoal: allLevels("Présenter clairement l'expérience.", "Créer une entrée qui situe le contexte et l'enjeu.", "Installer un angle vivant et adapté au lectorat."), tags: ["experience", "opening"] },
  { id: "recounting-events", task: "TASK_2", label: "Raconter les événements", description: "Faire suivre les faits de manière claire et intéressante.", learningGoal: allLevels("Raconter les étapes essentielles.", "Sélectionner et lier les moments importants.", "Construire un récit fluide avec un point de vue maîtrisé."), tags: ["experience", "narration", "organization"] },
  { id: "chronology", task: "TASK_2", label: "Organiser la chronologie", description: "Guider le lecteur dans le déroulement de l'expérience.", learningGoal: allLevels("Indiquer l'ordre des événements.", "Structurer les étapes et les changements de rythme.", "Jouer avec la chronologie sans nuire à la clarté."), tags: ["experience", "narration", "organization"] },
  { id: "describing-experience", task: "TASK_2", label: "Décrire les détails marquants", description: "Choisir des détails concrets qui rendent l'expérience compréhensible.", learningGoal: allLevels("Ajouter un détail pertinent.", "Sélectionner les détails qui éclairent le récit.", "Créer une description précise au service du propos."), tags: ["experience", "description"] },
  { id: "expressing-reaction", task: "TASK_2", label: "Exprimer une réaction", description: "Partager votre ressenti et votre appréciation de l'expérience.", learningGoal: allLevels("Exprimer une réaction personnelle claire.", "Relier sa réaction aux faits racontés.", "Exprimer un point de vue nuancé et crédible."), tags: ["experience", "commentary"] },
  { id: "commenting-on-experience", task: "TASK_2", label: "Commenter l'expérience", description: "Ajouter une réflexion ou un conseil utile aux lecteurs.", learningGoal: allLevels("Ajouter un commentaire lié à l'expérience.", "Tirer un enseignement ou formuler une recommandation.", "Développer un commentaire personnel et pertinent pour le lectorat."), tags: ["experience", "commentary", "audience"] },
  { id: "giving-examples", task: "TASK_2", label: "Illustrer par un moment précis", description: "Utiliser un épisode concret pour rendre le récit vivant.", learningGoal: allLevels("Décrire un moment précis.", "Choisir un épisode qui éclaire son commentaire.", "Intégrer un épisode significatif avec efficacité narrative."), tags: ["experience", "examples", "narration"] },
  { id: "adding-details", task: "TASK_2", label: "Ajouter des détails utiles", description: "Enrichir le récit sans le disperser.", learningGoal: allLevels("Ajouter une information utile.", "Développer les détails importants pour le lecteur.", "Sélectionner les détails avec économie et impact."), tags: ["experience", "development"] },
  { id: "contrasting-expectations", task: "TASK_2", label: "Comparer attentes et réalité", description: "Montrer une surprise, une difficulté ou une évolution dans l'expérience.", learningGoal: allLevels("Exprimer un contraste simple.", "Expliquer l'écart entre attente et expérience vécue.", "Exploiter le contraste pour structurer un récit réfléchi."), tags: ["experience", "commentary", "contrast"] },
  { id: "conclusion", task: "TASK_2", label: "Conclure le récit", description: "Terminer le blog ou l'e-mail par un bilan, un conseil ou une ouverture.", learningGoal: allLevels("Clore l'expérience de façon claire.", "Conclure par un bilan utile aux lecteurs.", "Conclure avec une appréciation nuancée et une portée claire."), tags: ["experience", "organization", "closing"] },

  { id: "introducing-topic", task: "TASK_3", label: "Introduire le sujet", description: "Présenter clairement l'enjeu et le débat à analyser.", learningGoal: allLevels("Présenter le sujet sans donner une réponse hâtive.", "Poser une problématique qui fait apparaître le débat.", "Cadrer l'enjeu avec précision et sans simplification."), tags: ["synthesis", "argumentation"] },
  { id: "reformulating-sources", task: "TASK_3", label: "Reformuler les idées des sources", description: "Restituer une idée de document sans la copier ni la déformer.", learningGoal: allLevels("Reformuler une idée principale.", "Reformuler avec fidélité et distinction des points de vue.", "Synthétiser avec précision en conservant les nuances."), tags: ["synthesis", "sources"] },
  { id: "comparing-viewpoints", task: "TASK_3", label: "Comparer les points de vue", description: "Relier les convergences et désaccords entre les sources.", learningGoal: allLevels("Identifier une différence entre deux points de vue.", "Comparer les accords et désaccords de manière organisée.", "Mettre en regard les logiques, limites et implications."), tags: ["synthesis", "comparison", "sources"] },
  { id: "identifying-arguments", task: "TASK_3", label: "Identifier les arguments", description: "Distinguer une idée, un argument, un exemple et une conséquence.", learningGoal: allLevels("Repérer les arguments principaux.", "Différencier les arguments et leurs justifications.", "Évaluer la portée et les présupposés d'un argument."), tags: ["synthesis", "argumentation", "sources"] },
  { id: "taking-position", task: "TASK_3", label: "Prendre position", description: "Formuler une réponse personnelle après l'analyse des points de vue.", learningGoal: allLevels("Annoncer une position claire.", "Prendre position après avoir reconnu une autre perspective.", "Formuler une position autonome, précise et conditionnée."), tags: ["synthesis", "argumentation"] },
  { id: "justifying-position", task: "TASK_3", label: "Justifier sa position", description: "Soutenir votre position par un raisonnement structuré.", learningGoal: allLevels("Justifier sa position avec une raison et un exemple.", "Développer une justification qui tient compte du débat.", "Construire une justification rigoureuse, hiérarchisée et nuancée."), tags: ["synthesis", "argumentation"] },
  { id: "counterarguments", task: "TASK_3", label: "Introduire un contre-argument", description: "Présenter loyalement une objection avant d'y répondre.", learningGoal: allLevels("Introduire une objection simple.", "Reconnaître une perspective opposée sans abandonner sa position.", "Formuler un contre-argument solide dans toute sa portée."), tags: ["synthesis", "argumentation", "nuance"] },
  { id: "responding-counterarguments", task: "TASK_3", label: "Répondre à un contre-argument", description: "Réfuter ou limiter une objection de manière cohérente.", learningGoal: allLevels("Répondre à une objection simplement.", "Répondre en distinguant ce qui est valable et ce qui est limité.", "Répondre avec précision sans caricaturer le point de vue opposé."), tags: ["synthesis", "argumentation", "nuance"] },
  { id: "nuancing-position", task: "TASK_3", label: "Nuancer", description: "Préciser les conditions, limites et exceptions de votre position.", learningGoal: allLevels("Ajouter une limite à une position.", "Nuancer selon les contextes et les conséquences.", "Définir avec finesse les limites et conditions de validité."), tags: ["synthesis", "nuance"] },
  { id: "synthesizing", task: "TASK_3", label: "Synthétiser", description: "Rassembler les idées utiles avant de formuler une conclusion personnelle.", learningGoal: allLevels("Résumer deux idées liées.", "Faire une synthèse qui relie les sources à sa position.", "Produire une synthèse fidèle, sélective et orientée vers l'enjeu."), tags: ["synthesis", "sources", "organization"] },
  { id: "conclusion", task: "TASK_3", label: "Conclure", description: "Conclure une analyse argumentative sans répéter l'introduction.", learningGoal: allLevels("Conclure par une position claire.", "Conclure en tenant compte de la complexité du débat.", "Conclure par une synthèse précise et une ouverture proportionnée."), tags: ["synthesis", "organization"] },
];

const exercise = (entry: PracticeExercise): PracticeExercise => entry;

/**
 * Initial reviewed sequences. The six entries in each sequence deliberately
 * reuse one communicative situation and decrease support at every step.
 */
export const PRACTICE_EXERCISES: readonly PracticeExercise[] = [
  exercise({ id: "t1-b2-openings-1", task: "TASK_1", level: "B2", skill: "openings", subSkill: "opening-by-register", exerciseType: "recognize", prompt: "Vous écrivez au responsable de votre résidence pour signaler un problème de chauffage.", instructions: "Choisissez la meilleure première phrase.", options: ["Salut, j'ai un souci de chauffage.", "Madame, Monsieur, je vous écris afin de vous signaler un problème de chauffage dans mon appartement.", "Le chauffage, c'est vraiment nul !", "Je veux que vous répariez cela."], correctAnswer: "Madame, Monsieur, je vous écris afin de vous signaler un problème de chauffage dans mon appartement.", acceptedAnswers: [], explanation: "La phrase indique le destinataire, le but du message et conserve un registre formel adapté.", targetLanguageFeature: "ouverture formelle et but du message", difficulty: 1, sequenceOrder: 1, prerequisiteExerciseId: null, tags: ["opening", "formal", "recognize"] }),
  exercise({ id: "t1-b2-openings-2", task: "TASK_1", level: "B2", skill: "openings", subSkill: "purpose-formula", exerciseType: "complete", prompt: "Vous écrivez à votre professeur pour expliquer une absence.", instructions: "Complétez l'ouverture : « Bonjour Madame, je vous écris pour ______ mon absence au cours de lundi. »", options: [], correctAnswer: "vous expliquer", acceptedAnswers: ["expliquer", "vous informer de"], explanation: "Une ouverture efficace annonce immédiatement l'objectif du message avec une formule polie.", targetLanguageFeature: "annonce du but", difficulty: 2, sequenceOrder: 2, prerequisiteExerciseId: "t1-b2-openings-1", tags: ["opening", "purpose", "complete"] }),
  exercise({ id: "t1-b2-openings-3", task: "TASK_1", level: "B2", skill: "openings", subSkill: "register-change", exerciseType: "transform", prompt: "Transformez cette première phrase pour écrire à une amie : « Madame, je vous écris afin de vous proposer de venir chez moi samedi. »", instructions: "Gardez le même but, mais adoptez un registre amical.", options: [], correctAnswer: null, acceptedAnswers: ["Salut, je t'écris pour te proposer de venir chez moi samedi.", "Bonjour, je voulais te proposer de venir chez moi samedi."], explanation: "Le destinataire proche permet une formule plus directe et le tutoiement, sans perdre la clarté de l'invitation.", targetLanguageFeature: "adaptation du registre", difficulty: 3, sequenceOrder: 3, prerequisiteExerciseId: "t1-b2-openings-2", tags: ["opening", "register", "transform"] }),
  exercise({ id: "t1-b2-openings-4", task: "TASK_1", level: "B2", skill: "openings", subSkill: "opening-order", exerciseType: "organize", prompt: "Vous demandez des renseignements à une association de sport.", instructions: "Remettez ces éléments dans l'ordre d'une ouverture claire.", options: ["Je souhaiterais connaître les horaires des cours du soir.", "Madame, Monsieur,", "Je vous écris car je souhaite m'inscrire à votre association."], correctAnswer: ["Madame, Monsieur,", "Je vous écris car je souhaite m'inscrire à votre association.", "Je souhaiterais connaître les horaires des cours du soir."], acceptedAnswers: [], explanation: "On salue, on situe son intention générale, puis on formule la demande précise.", targetLanguageFeature: "organisation de l'ouverture", difficulty: 4, sequenceOrder: 4, prerequisiteExerciseId: "t1-b2-openings-3", tags: ["opening", "organization"] }),
  exercise({ id: "t1-b2-openings-5", task: "TASK_1", level: "B2", skill: "openings", subSkill: "context-and-purpose", exerciseType: "develop", prompt: "Situation : vous avez trouvé un portefeuille dans le bus et vous écrivez au service des objets trouvés.", instructions: "Rédigez deux phrases d'ouverture : saluez le service, annoncez le but du message, puis donnez le contexte utile.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Votre ouverture doit permettre au lecteur de comprendre immédiatement ce que vous avez trouvé et pourquoi vous écrivez.", targetLanguageFeature: "but et contexte", difficulty: 5, sequenceOrder: 5, prerequisiteExerciseId: "t1-b2-openings-4", tags: ["opening", "development"], selfCheck: ["J'ai choisi une formule de salutation adaptée à un service.", "J'annonce clairement que j'ai trouvé un portefeuille.", "Je donne un détail utile sur le lieu ou le moment." ] }),
  exercise({ id: "t1-b2-openings-6", task: "TASK_1", level: "B2", skill: "openings", subSkill: "independent-opening", exerciseType: "produce", prompt: "Vous écrivez à votre mairie parce que l'éclairage de votre rue ne fonctionne plus depuis une semaine.", instructions: "Rédigez l'ouverture de votre message (2 ou 3 phrases), dans un registre formel. N'ajoutez pas encore la conclusion.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Vérifiez que le destinataire, le problème et votre objectif sont identifiables dès l'ouverture.", targetLanguageFeature: "ouverture autonome en registre formel", difficulty: 6, sequenceOrder: 6, prerequisiteExerciseId: "t1-b2-openings-5", tags: ["opening", "production"], selfCheck: ["Le destinataire est clairement identifié.", "Le problème et sa durée sont formulés sans ambiguïté.", "Le ton reste formel et poli." ] }),

  exercise({ id: "t2-b2-recounting-events-1", task: "TASK_2", level: "B2", skill: "recounting-events", subSkill: "relevant-opening", exerciseType: "recognize", prompt: "Vous publiez sur le blog de votre association le récit d'une journée de bénévolat.", instructions: "Choisissez la meilleure ouverture.", options: ["J'aime beaucoup le bénévolat.", "Samedi dernier, j'ai participé à une journée de ramassage des déchets avec notre association, une expérience aussi utile qu'inattendue.", "Les déchets, c'est mauvais.", "Il faut faire attention."], correctAnswer: "Samedi dernier, j'ai participé à une journée de ramassage des déchets avec notre association, une expérience aussi utile qu'inattendue.", acceptedAnswers: [], explanation: "L'ouverture situe le moment, l'action et donne au lecteur une raison de poursuivre le récit.", targetLanguageFeature: "situation de départ", difficulty: 1, sequenceOrder: 1, prerequisiteExerciseId: null, tags: ["experience", "opening", "recognize"] }),
  exercise({ id: "t2-b2-recounting-events-2", task: "TASK_2", level: "B2", skill: "recounting-events", subSkill: "chronological-link", exerciseType: "complete", prompt: "Complétez : « Nous avons d'abord reçu le matériel. ______, nous nous sommes répartis dans les rues du quartier. »", instructions: "Ajoutez un connecteur qui marque l'étape suivante.", options: [], correctAnswer: "Ensuite", acceptedAnswers: ["Puis", "Après cela"], explanation: "Un connecteur chronologique aide les lecteurs d'un blog ou d'un e-mail à suivre les faits.", targetLanguageFeature: "chronologie du récit", difficulty: 2, sequenceOrder: 2, prerequisiteExerciseId: "t2-b2-recounting-events-1", tags: ["experience", "chronology", "complete"] }),
  exercise({ id: "t2-b2-recounting-events-3", task: "TASK_2", level: "B2", skill: "recounting-events", subSkill: "combine-event-and-reaction", exerciseType: "transform", prompt: "Combinez : « Nous avons rempli vingt sacs. Nous étions surpris par la quantité de déchets. »", instructions: "Rédigez une phrase qui raconte le fait et votre réaction.", options: [], correctAnswer: null, acceptedAnswers: ["Nous avons rempli vingt sacs, ce qui nous a surpris par la quantité de déchets.", "Après avoir rempli vingt sacs, nous avons été surpris par la quantité de déchets."], explanation: "Un bon récit relie les faits vécus à une réaction personnelle, au lieu de les juxtaposer.", targetLanguageFeature: "fait et réaction", difficulty: 3, sequenceOrder: 3, prerequisiteExerciseId: "t2-b2-recounting-events-2", tags: ["experience", "reaction", "transform"] }),
  exercise({ id: "t2-b2-recounting-events-4", task: "TASK_2", level: "B2", skill: "recounting-events", subSkill: "narrative-order", exerciseType: "organize", prompt: "Organisez un court passage pour le blog de l'association.", instructions: "Mettez les phrases dans l'ordre chronologique.", options: ["À la fin de la journée, nous avons constaté que le parc était beaucoup plus propre.", "Samedi dernier, vingt bénévoles se sont retrouvés devant la gare.", "Après une brève explication, chacun a reçu des gants et des sacs.", "Nous avons ensuite nettoyé les rues et le parc pendant trois heures."], correctAnswer: ["Samedi dernier, vingt bénévoles se sont retrouvés devant la gare.", "Après une brève explication, chacun a reçu des gants et des sacs.", "Nous avons ensuite nettoyé les rues et le parc pendant trois heures.", "À la fin de la journée, nous avons constaté que le parc était beaucoup plus propre."], acceptedAnswers: [], explanation: "Le récit progresse du contexte à la préparation, à l'action, puis au résultat.", targetLanguageFeature: "organisation chronologique", difficulty: 4, sequenceOrder: 4, prerequisiteExerciseId: "t2-b2-recounting-events-3", tags: ["experience", "chronology", "organization"] }),
  exercise({ id: "t2-b2-recounting-events-5", task: "TASK_2", level: "B2", skill: "recounting-events", subSkill: "event-commentary", exerciseType: "develop", prompt: "Départ : vous avez participé à un atelier de cuisine organisé par votre quartier. Vous avez appris une recette avec des voisins que vous ne connaissiez pas.", instructions: "Rédigez 3 ou 4 phrases : racontez un moment précis, ajoutez votre réaction, puis expliquez ce que cette expérience vous a apporté.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le lecteur doit voir un événement concret et comprendre votre appréciation personnelle.", targetLanguageFeature: "récit et commentaire", difficulty: 5, sequenceOrder: 5, prerequisiteExerciseId: "t2-b2-recounting-events-4", tags: ["experience", "commentary", "development"], selfCheck: ["Je raconte un moment réellement identifiable.", "Ma réaction est liée à ce qui s'est passé.", "J'explique ce que cette expérience m'a apporté." ] }),
  exercise({ id: "t2-b2-recounting-events-6", task: "TASK_2", level: "B2", skill: "recounting-events", subSkill: "independent-experience-post", exerciseType: "produce", prompt: "Pour le blog de votre école de français, racontez une activité culturelle à laquelle vous avez participé récemment.", instructions: "Écrivez un post de 80 à 100 mots : situez l'expérience, racontez deux moments dans l'ordre, donnez votre réaction et terminez par un conseil ou un bilan pour les lecteurs.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Votre texte doit être un récit adressé à plusieurs lecteurs : les événements et votre commentaire personnel doivent être liés.", targetLanguageFeature: "post de blog autonome", difficulty: 6, sequenceOrder: 6, prerequisiteExerciseId: "t2-b2-recounting-events-5", tags: ["experience", "blog", "production"], selfCheck: ["Je situe l'expérience pour les lecteurs du blog.", "Les deux moments sont reliés dans un ordre compréhensible.", "Je donne une réaction et un conseil ou bilan personnel." ] }),

  exercise({ id: "t3-c1-counterarguments-1", task: "TASK_3", level: "C1", skill: "counterarguments", subSkill: "fair-objection", exerciseType: "recognize", prompt: "Vous défendez la réduction de la place de la voiture en centre-ville.", instructions: "Choisissez la formulation qui introduit loyalement un contre-argument.", options: ["Les automobilistes n'ont rien compris.", "Certains estiment toutefois qu'une réduction trop rapide de la circulation pourrait pénaliser les personnes qui n'ont pas d'alternative fiable.", "Les voitures sont mauvaises, donc le débat est terminé.", "Il faut être contre les voitures."], correctAnswer: "Certains estiment toutefois qu'une réduction trop rapide de la circulation pourrait pénaliser les personnes qui n'ont pas d'alternative fiable.", acceptedAnswers: [], explanation: "Un contre-argument C1 présente une objection plausible, avec une conséquence précise, sans la caricaturer.", targetLanguageFeature: "introduction loyale d'une objection", difficulty: 1, sequenceOrder: 1, prerequisiteExerciseId: null, tags: ["counterargument", "register", "recognize"] }),
  exercise({ id: "t3-c1-counterarguments-2", task: "TASK_3", level: "C1", skill: "counterarguments", subSkill: "concession-marker", exerciseType: "complete", prompt: "Complétez : « ______ les transports publics ne desservent pas encore tous les quartiers, il serait excessif d'interdire immédiatement toutes les voitures. »", instructions: "Choisissez un connecteur de concession qui introduit une limite réelle.", options: ["Bien que", "Parce que", "Donc", "Par conséquent"], correctAnswer: "Bien que", acceptedAnswers: [], explanation: "« Bien que » reconnaît un fait avant d'en tirer une position nuancée.", targetLanguageFeature: "concession", difficulty: 2, sequenceOrder: 2, prerequisiteExerciseId: "t3-c1-counterarguments-1", tags: ["counterargument", "concession", "complete"] }),
  exercise({ id: "t3-c1-counterarguments-3", task: "TASK_3", level: "C1", skill: "counterarguments", subSkill: "balanced-reformulation", exerciseType: "transform", prompt: "Reformulez sans dévaloriser l'objection : « Les opposants disent que les pistes cyclables sont inutiles. »", instructions: "Faites apparaître une raison possible de leur point de vue.", options: [], correctAnswer: null, acceptedAnswers: ["Certains opposants craignent que les pistes cyclables réduisent trop l'espace disponible pour les autres usagers.", "D'aucuns estiment que les pistes cyclables peuvent compliquer la circulation de certains usagers."], explanation: "Une reformulation utile remplace une affirmation absolue par une inquiétude identifiable et discutable.", targetLanguageFeature: "reformulation d'un point de vue", difficulty: 3, sequenceOrder: 3, prerequisiteExerciseId: "t3-c1-counterarguments-2", tags: ["counterargument", "reformulation", "transform"] }),
  exercise({ id: "t3-c1-counterarguments-4", task: "TASK_3", level: "C1", skill: "counterarguments", subSkill: "objection-response-order", exerciseType: "organize", prompt: "Organisez ce passage sur la limitation des voitures au centre-ville.", instructions: "Mettez les phrases dans l'ordre du raisonnement.", options: ["Cette difficulté justifie donc une mise en œuvre progressive, plutôt que l'abandon du projet.", "Il reste néanmoins nécessaire de réduire la pollution dans les zones les plus fréquentées.", "Certes, certains habitants dépendent encore de leur véhicule.", "La municipalité pourrait d'abord améliorer les lignes de bus dans les quartiers concernés."], correctAnswer: ["Certes, certains habitants dépendent encore de leur véhicule.", "Il reste néanmoins nécessaire de réduire la pollution dans les zones les plus fréquentées.", "Cette difficulté justifie donc une mise en œuvre progressive, plutôt que l'abandon du projet.", "La municipalité pourrait d'abord améliorer les lignes de bus dans les quartiers concernés."], acceptedAnswers: [], explanation: "On reconnaît l'objection, on maintient l'enjeu, on nuance la réponse, puis on propose une solution concrète.", targetLanguageFeature: "concession → position → réponse nuancée → solution", difficulty: 4, sequenceOrder: 4, prerequisiteExerciseId: "t3-c1-counterarguments-3", tags: ["counterargument", "organization"] }),
  exercise({ id: "t3-c1-counterarguments-5", task: "TASK_3", level: "C1", skill: "counterarguments", subSkill: "qualified-response", exerciseType: "develop", prompt: "Position de départ : « Les universités devraient limiter l'usage des téléphones pendant les cours. » Objection : certains étudiants les utilisent pour consulter des ressources pédagogiques.", instructions: "Rédigez 3 ou 4 phrases qui reconnaissent cette objection, la limitent ou y répondent, puis précisent votre position.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Votre réponse doit reconnaître ce qui est valable dans l'objection avant de proposer une position plus précise.", targetLanguageFeature: "réponse nuancée à une objection", difficulty: 5, sequenceOrder: 5, prerequisiteExerciseId: "t3-c1-counterarguments-4", tags: ["counterargument", "development"], selfCheck: ["Je présente l'objection sans la déformer.", "Je reconnais ce qui peut être valable dans cette objection.", "Ma réponse précise la limite ou la condition de ma position." ] }),
  exercise({ id: "t3-c1-counterarguments-6", task: "TASK_3", level: "C1", skill: "counterarguments", subSkill: "independent-balanced-position", exerciseType: "produce", prompt: "Deux sources débattent de l'interdiction de la publicité destinée aux enfants : l'une insiste sur la protection des mineurs, l'autre sur la liberté des entreprises et des familles.", instructions: "Écrivez un paragraphe de 90 à 110 mots : présentez un contre-argument de manière loyale, puis donnez une réponse nuancée et votre position.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le lecteur doit pouvoir distinguer le point de vue opposé, votre réponse et la position que vous retenez.", targetLanguageFeature: "contre-argument autonome dans une synthèse", difficulty: 6, sequenceOrder: 6, prerequisiteExerciseId: "t3-c1-counterarguments-5", tags: ["counterargument", "synthesis", "production"], selfCheck: ["Je distingue nettement le point de vue opposé du mien.", "Je réponds à l'objection avec une limite ou une condition précise.", "Ma conclusion exprime une position personnelle défendable." ] }),

  exercise({ id: "t1-c1-developing-information-1", task: "TASK_1", level: "C1", skill: "developing-information", subSkill: "anticipate-reader-needs", exerciseType: "recognize", prompt: "Vous signalez à votre syndic des nuisances sonores nocturnes récurrentes dans l'immeuble.", instructions: "Choisissez la phrase qui développe l'information de façon la plus utile pour le syndic.", options: ["Il y a beaucoup de bruit le soir, c'est insupportable.", "Depuis environ trois semaines, des bruits de perceuse et de meubles déplacés réveillent plusieurs voisins vers 23 heures, principalement les mardis et jeudis.", "Le bruit vient sûrement de l'appartement du dessus, je crois.", "Merci de faire quelque chose rapidement."], correctAnswer: "Depuis environ trois semaines, des bruits de perceuse et de meubles déplacés réveillent plusieurs voisins vers 23 heures, principalement les mardis et jeudis.", acceptedAnswers: [], explanation: "Un développement de niveau C1 anticipe ce dont le lecteur a besoin pour agir : depuis quand, quel type de bruit, à quelle heure et à quelle fréquence.", targetLanguageFeature: "développement anticipant les besoins du lecteur", difficulty: 1, sequenceOrder: 1, prerequisiteExerciseId: null, tags: ["development", "information", "recognize"] }),
  exercise({ id: "t1-c1-developing-information-2", task: "TASK_1", level: "C1", skill: "developing-information", subSkill: "consequence-link", exerciseType: "complete", prompt: "Complétez cette phrase pour préciser l'impact des nuisances : « Ces réveils répétés ______, ce qui commence à affecter la vie quotidienne de plusieurs foyers. »", instructions: "Ajoutez une précision qui montre la conséquence concrète du bruit.", options: [], correctAnswer: null, acceptedAnswers: ["perturbent le sommeil de plusieurs résidents", "empêchent certains voisins de dormir correctement", "nuisent au sommeil des habitants"], explanation: "Développer l'information pour un lecteur C1 suppose de relier le fait à une conséquence concrète et vérifiable.", targetLanguageFeature: "développement par la conséquence", difficulty: 2, sequenceOrder: 2, prerequisiteExerciseId: "t1-c1-developing-information-1", tags: ["development", "consequence", "complete"] }),
  exercise({ id: "t1-c1-developing-information-3", task: "TASK_1", level: "C1", skill: "developing-information", subSkill: "combine-details", exerciseType: "transform", prompt: "Développez cette information trop générale : « Le bruit dérange les voisins. »", instructions: "Réécrivez la phrase en ajoutant le moment précis, la source probable et l'effet sur les voisins, en une seule phrase fluide.", options: [], correctAnswer: null, acceptedAnswers: ["Le bruit, qui provient probablement de l'appartement du troisième étage, dérange plusieurs voisins en fin de soirée en les empêchant de trouver le sommeil.", "Provenant sans doute du troisième étage, ce bruit en fin de soirée empêche plusieurs voisins de dormir."], explanation: "Une bonne transformation combine plusieurs informations (source, moment, effet) en une phrase claire plutôt que de les juxtaposer.", targetLanguageFeature: "combinaison d'informations en une phrase développée", difficulty: 3, sequenceOrder: 3, prerequisiteExerciseId: "t1-c1-developing-information-2", tags: ["development", "transform"] }),
  exercise({ id: "t1-c1-developing-information-4", task: "TASK_1", level: "C1", skill: "developing-information", subSkill: "development-order", exerciseType: "organize", prompt: "Organisez ce passage qui développe la situation pour le syndic.", instructions: "Mettez les phrases dans l'ordre le plus utile pour un lecteur qui doit agir.", options: ["Ces bruits reviennent surtout le mardi et le jeudi soir, vers 23 heures.", "Depuis trois semaines, plusieurs résidents constatent des nuisances sonores nocturnes.", "Ils semblent provenir du même appartement à chaque fois.", "Une intervention auprès du logement concerné permettrait sans doute de résoudre rapidement la situation."], correctAnswer: ["Depuis trois semaines, plusieurs résidents constatent des nuisances sonores nocturnes.", "Ces bruits reviennent surtout le mardi et le jeudi soir, vers 23 heures.", "Ils semblent provenir du même appartement à chaque fois.", "Une intervention auprès du logement concerné permettrait sans doute de résoudre rapidement la situation."], acceptedAnswers: [], explanation: "On part du constat général, on précise la fréquence, on identifie la source probable, puis on propose une action anticipant le besoin du lecteur.", targetLanguageFeature: "organisation du développement (constat → détail → source → action)", difficulty: 4, sequenceOrder: 4, prerequisiteExerciseId: "t1-c1-developing-information-3", tags: ["development", "organization"] }),
  exercise({ id: "t1-c1-developing-information-5", task: "TASK_1", level: "C1", skill: "developing-information", subSkill: "guided-development", exerciseType: "develop", prompt: "Idée de départ : « Le hall d'entrée de l'immeuble est mal éclairé le soir. »", instructions: "Développez cette information en 3 ou 4 phrases en anticipant ce dont le syndic a besoin pour agir : précisez depuis quand, à quel moment, quel risque cela pose, et ce que vous suggérez.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Un développement C1 réussi donne au lecteur tout ce qu'il lui faut pour comprendre le problème et agir, sans qu'il ait besoin de revenir vers vous pour des précisions.", targetLanguageFeature: "développement complet anticipant l'action du lecteur", difficulty: 5, sequenceOrder: 5, prerequisiteExerciseId: "t1-c1-developing-information-4", tags: ["development", "develop"], selfCheck: ["J'indique depuis quand le problème existe.", "Je précise le moment ou les circonstances utiles au lecteur.", "Je nomme le risque et ce que je suggère." ] }),
  exercise({ id: "t1-c1-developing-information-6", task: "TASK_1", level: "C1", skill: "developing-information", subSkill: "independent-development", exerciseType: "produce", prompt: "Vous écrivez au syndic de votre immeuble pour signaler que la porte du parking ne se ferme plus correctement depuis quelques jours.", instructions: "Rédigez un paragraphe de 50 à 70 mots qui développe la situation : depuis quand, dans quelles circonstances, quel risque cela représente, et ce que vous attendez du syndic. N'ajoutez pas de salutation ni de formule de politesse.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Relisez votre paragraphe : un lecteur qui ne connaît pas la situation doit pouvoir agir seulement grâce à vos informations, sans poser de question supplémentaire.", targetLanguageFeature: "développement autonome anticipant les besoins du lecteur", difficulty: 6, sequenceOrder: 6, prerequisiteExerciseId: "t1-c1-developing-information-5", tags: ["development", "production"], selfCheck: ["Depuis quand et dans quelles circonstances est précisé.", "Le risque ou la gêne est explicite.", "J'indique clairement ce que j'attends du syndic." ] }),

  exercise({ id: "t3-b2-justifying-position-1", task: "TASK_3", level: "B2", skill: "justifying-position", subSkill: "relevant-justification", exerciseType: "recognize", prompt: "Vous donnez votre avis sur l'ouverture des bibliothèques municipales le dimanche.", instructions: "Choisissez la justification la plus convaincante.", options: ["Les bibliothèques devraient être ouvertes le dimanche parce que c'est une bonne idée.", "Les bibliothèques devraient être ouvertes le dimanche, car de nombreux étudiants et salariés n'ont que ce jour-là pour venir travailler ou emprunter des livres.", "Les bibliothèques, il faut les ouvrir le dimanche, un point c'est tout.", "Le dimanche est un jour important."], correctAnswer: "Les bibliothèques devraient être ouvertes le dimanche, car de nombreux étudiants et salariés n'ont que ce jour-là pour venir travailler ou emprunter des livres.", acceptedAnswers: [], explanation: "Une justification convaincante donne une raison précise, liée à un groupe concret de lecteurs, plutôt qu'une affirmation vague.", targetLanguageFeature: "justification par parce que / car", difficulty: 1, sequenceOrder: 1, prerequisiteExerciseId: null, tags: ["opinion", "justification", "recognize"] }),
  exercise({ id: "t3-b2-justifying-position-2", task: "TASK_3", level: "B2", skill: "justifying-position", subSkill: "because-clause", exerciseType: "complete", prompt: "Complétez : « Je pense que les bibliothèques municipales devraient ouvrir le dimanche parce que ______. »", instructions: "Ajoutez une raison précise, pas seulement une préférence personnelle.", options: [], correctAnswer: null, acceptedAnswers: ["beaucoup de gens travaillent toute la semaine", "certains n'ont pas d'autre jour disponible", "cela permettrait à plus de monde d'y accéder"], explanation: "La raison doit expliquer l'opinion et rester liée au sujet des bibliothèques.", targetLanguageFeature: "justification par parce que", difficulty: 2, sequenceOrder: 2, prerequisiteExerciseId: "t3-b2-justifying-position-1", tags: ["opinion", "justification", "complete"] }),
  exercise({ id: "t3-b2-justifying-position-3", task: "TASK_3", level: "B2", skill: "justifying-position", subSkill: "combine-cause-and-effect", exerciseType: "transform", prompt: "Combinez ces deux idées en une phrase argumentative : « L'ouverture du dimanche aiderait les étudiants. Beaucoup d'entre eux travaillent en semaine. »", instructions: "Utilisez un connecteur qui montre la relation logique.", options: [], correctAnswer: null, acceptedAnswers: ["L'ouverture du dimanche aiderait les étudiants, car beaucoup d'entre eux travaillent en semaine.", "Comme beaucoup d'étudiants travaillent en semaine, l'ouverture du dimanche les aiderait."], explanation: "La phrase doit relier clairement l'avantage au fait qui le justifie.", targetLanguageFeature: "connecteur de cause", difficulty: 3, sequenceOrder: 3, prerequisiteExerciseId: "t3-b2-justifying-position-2", tags: ["opinion", "justification", "transform"] }),
  exercise({ id: "t3-b2-justifying-position-4", task: "TASK_3", level: "B2", skill: "justifying-position", subSkill: "argument-chain", exerciseType: "organize", prompt: "Organisez un mini-paragraphe qui justifie une position sur ce sujet.", instructions: "Mettez les phrases dans l'ordre le plus logique.", options: ["Par exemple, un étudiant qui travaille toute la semaine pourrait enfin venir réviser tranquillement.", "Je pense que les bibliothèques municipales devraient ouvrir le dimanche.", "En effet, ce jour est souvent le seul disponible pour de nombreux salariés et étudiants.", "Cela permettrait à un plus grand nombre de personnes d'accéder aux services de la bibliothèque."], correctAnswer: ["Je pense que les bibliothèques municipales devraient ouvrir le dimanche.", "En effet, ce jour est souvent le seul disponible pour de nombreux salariés et étudiants.", "Par exemple, un étudiant qui travaille toute la semaine pourrait enfin venir réviser tranquillement.", "Cela permettrait à un plus grand nombre de personnes d'accéder aux services de la bibliothèque."], acceptedAnswers: [], explanation: "On annonce la position, on la justifie, on l'illustre par un exemple, puis on explicite la conséquence.", targetLanguageFeature: "position → argument → exemple → conséquence", difficulty: 4, sequenceOrder: 4, prerequisiteExerciseId: "t3-b2-justifying-position-3", tags: ["opinion", "justification", "organization"] }),
  exercise({ id: "t3-b2-justifying-position-5", task: "TASK_3", level: "B2", skill: "justifying-position", subSkill: "explanation-and-example", exerciseType: "develop", prompt: "Idée de départ : « Les transports publics devraient être gratuits le week-end. »", instructions: "Ajoutez une justification, une explication et un exemple concret en 3 ou 4 phrases.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Votre développement doit aller au-delà d'une opinion : montrez pourquoi l'idée est utile et pour qui.", targetLanguageFeature: "développement argumentatif", difficulty: 5, sequenceOrder: 5, prerequisiteExerciseId: "t3-b2-justifying-position-4", tags: ["opinion", "justification", "development"], selfCheck: ["J'exprime une position claire sur l'idée de départ.", "J'explique pourquoi cette mesure serait utile.", "Je donne un exemple concret qui illustre mon explication." ] }),
  exercise({ id: "t3-b2-justifying-position-6", task: "TASK_3", level: "B2", skill: "justifying-position", subSkill: "independent-paragraph", exerciseType: "produce", prompt: "Deux sources débattent de l'interdiction des sacs plastiques à usage unique dans les commerces : l'une souligne la protection de l'environnement, l'autre le coût pour les petits commerçants.", instructions: "Écrivez un paragraphe de 60 à 80 mots : exprimez votre position, donnez une raison, expliquez-la et ajoutez un exemple.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Relisez votre paragraphe : le lecteur doit pouvoir repérer une position, une raison, une explication et un exemple.", targetLanguageFeature: "paragraphe argumentatif autonome", difficulty: 6, sequenceOrder: 6, prerequisiteExerciseId: "t3-b2-justifying-position-5", tags: ["opinion", "justification", "production"], selfCheck: ["Ma position est énoncée clairement.", "Une raison précise justifie cette position.", "Un exemple concret rend mon explication crédible." ] }),
];

export function getPracticeTopics(task: TaskType, level?: PracticeLevel): readonly PracticeTopic[] {
  const topicsForTask = PRACTICE_TOPICS.filter((topic) => topic.task === task);
  if (!level) return topicsForTask;

  // The curriculum taxonomy remains visible to authors at every level; the
  // learner-facing selector only exposes a topic after its reviewed sequence
  // has been added to the bank for that exact task and level.
  const availableSkillIds = new Set(
    PRACTICE_EXERCISES.filter((exercise) => exercise.task === task && exercise.level === level).map((exercise) => exercise.skill),
  );
  return topicsForTask.filter((topic) => availableSkillIds.has(topic.id));
}

export function getPracticeExercises(task: TaskType, level: PracticeLevel, skill: string): readonly PracticeExercise[] {
  return PRACTICE_EXERCISES.filter(
    (exercise) => exercise.task === task && exercise.level === level && exercise.skill === skill,
  ).sort((left, right) => left.sequenceOrder - right.sequenceOrder);
}

export function getPracticeTopic(task: TaskType, skill: string): PracticeTopic | undefined {
  return PRACTICE_TOPICS.find((topic) => topic.task === task && topic.id === skill);
}
