import type { PracticeExercise } from "./practice-curriculum";

/**
 * Editor-reviewed C2 material for Task 3, authored in a second isolated
 * module (alongside practice-task3-c2-exercises.ts) so two agents could
 * complete the remaining C2 parts without editing the same file. This file
 * covers counterarguments, nuancing-position, and conclusion.
 */
type AuthoredVariant = Omit<
  PracticeExercise,
  "id" | "task" | "level" | "skill" | "exerciseType" | "difficulty" | "sequenceOrder" | "prerequisiteExerciseId"
>;

const STAGES: readonly PracticeExercise["exerciseType"][] = [
  "recognize",
  "complete",
  "transform",
  "organize",
  "develop",
  "produce",
];

const taskThreeC2Path = (
  prefix: string,
  skill: string,
  stages: readonly (readonly [AuthoredVariant, AuthoredVariant])[],
): readonly PracticeExercise[] =>
  stages.flatMap(([primary, alternative], index) => {
    const sequenceOrder = (index + 1) as 1 | 2 | 3 | 4 | 5 | 6;
    const shared = {
      task: "TASK_3" as const,
      level: "C2" as const,
      skill,
      exerciseType: STAGES[index]!,
      difficulty: sequenceOrder,
      sequenceOrder,
      prerequisiteExerciseId: index === 0 ? null : `${prefix}-${index}`,
    };
    return [
      { id: `${prefix}-${sequenceOrder}`, ...shared, ...primary },
      { id: `${prefix}-a${sequenceOrder}`, ...shared, ...alternative },
    ];
  });

export const TASK_3_C2_EXERCISES_2: readonly PracticeExercise[] = [
  ...taskThreeC2Path("t3-c2-counterarguments", "counterarguments", [
    [
      { subSkill: "counterargument-full-strength", prompt: "Vous défendez l'instauration d'une taxe carbone aux frontières. Vous devez maintenant introduire loyalement, dans toute sa portée, l'objection la plus sérieuse à cette position.", instructions: "Choisissez la formulation qui présente le contre-argument avec toute sa force, sans le minimiser.", options: ["Certains pourraient dire que ça pose un problème.", "On pourrait objecter que cette taxe pénaliserait avant tout les économies en développement les plus dépendantes de leurs exportations vers l'Europe, sans qu'elles disposent des moyens de décarboner rapidement leur production.", "Il y a bien sûr des critiques, mais elles ne sont pas très solides.", "Certains pays ne seront pas contents."], correctAnswer: "On pourrait objecter que cette taxe pénaliserait avant tout les économies en développement les plus dépendantes de leurs exportations vers l'Europe, sans qu'elles disposent des moyens de décarboner rapidement leur production.", acceptedAnswers: [], explanation: "Cette formulation restitue le mécanisme réel de l'objection et ses conséquences précises, au lieu de l'affaiblir en une réserve vague.", targetLanguageFeature: "contre-argument formulé dans toute sa portée", tags: ["counterargument", "recognize"] },
      { subSkill: "counterargument-full-strength-alternative", prompt: "Vous défendez l'interdiction des vols intérieurs courts lorsqu'une alternative ferroviaire existe. Vous devez introduire loyalement l'objection la plus sérieuse à cette position.", instructions: "Choisissez la formulation qui présente le contre-argument avec toute sa force.", options: ["Certains n'aimeront pas cette interdiction.", "On pourrait objecter qu'une telle interdiction fragiliserait la connexion de certaines régions mal desservies par le rail, où l'avion reste le seul moyen de transport rapide.", "Il y a des critiques, mais elles sont mineures.", "Certains voyageurs seront gênés."], correctAnswer: "On pourrait objecter qu'une telle interdiction fragiliserait la connexion de certaines régions mal desservies par le rail, où l'avion reste le seul moyen de transport rapide.", acceptedAnswers: [], explanation: "L'objection identifie un public précis et un mécanisme réel, sans être minimisée.", targetLanguageFeature: "contre-argument formulé dans toute sa portée", tags: ["counterargument", "recognize", "variant"] },
    ],
    [
      { subSkill: "counterargument-concessive-intensifier", prompt: "Vous introduisez un contre-argument dans toute sa portée.", instructions: "Complétez : « On pourrait objecter que cette mesure, aussi ______ soit-elle sur le plan environnemental, risque de figer les inégalités entre économies industrialisées et économies en développement. »", options: [], correctAnswer: "justifiée", acceptedAnswers: ["fondée", "légitime"], explanation: "Cette construction concessive reconnaît la légitimité de la mesure tout en formulant pleinement l'objection.", targetLanguageFeature: "concession intensifiée avant l'objection", tags: ["counterargument", "complete"] },
      { subSkill: "counterargument-concessive-intensifier-alternative", prompt: "Vous introduisez un contre-argument dans toute sa portée.", instructions: "Complétez : « On pourrait objecter que cette interdiction, aussi ______ soit-elle sur le plan climatique, risque d'isoler davantage certaines régions déjà mal desservies. »", options: [], correctAnswer: "justifiée", acceptedAnswers: ["fondée", "légitime"], explanation: "La même construction reconnaît la légitimité de la mesure avant de formuler pleinement l'objection.", targetLanguageFeature: "concession intensifiée avant l'objection", tags: ["counterargument", "complete", "variant"] },
    ],
    [
      { subSkill: "strengthen-weak-counterargument", prompt: "Renforcez ce contre-argument affaibli en une objection formulée dans toute sa portée : « Certains n'aiment pas cette taxe parce que ça coûte cher. »", instructions: "Réécrivez en restituant le mécanisme réel de l'objection et les acteurs concernés.", options: [], correctAnswer: null, acceptedAnswers: ["L'objection la plus sérieuse tient au risque que cette taxe fasse porter le coût de la transition sur des pays qui n'ont pas eu le temps ni les moyens de décarboner leur production, aggravant ainsi une inégalité déjà présente dans les échanges internationaux.", "On pourrait objecter, non sans fondement, que cette mesure protège la compétitivité européenne au prix d'une charge disproportionnée sur des économies moins outillées pour s'adapter rapidement."], explanation: "Le contre-argument C2 nomme le mécanisme et les acteurs précis, au lieu de se limiter à un coût vague.", targetLanguageFeature: "renforcement d'un contre-argument affaibli", tags: ["counterargument", "transform"] },
      { subSkill: "strengthen-weak-counterargument-alternative", prompt: "Renforcez ce contre-argument affaibli : « Certains n'aiment pas cette interdiction parce que c'est contraignant. »", instructions: "Réécrivez en restituant le mécanisme réel de l'objection et les acteurs concernés.", options: [], correctAnswer: null, acceptedAnswers: ["L'objection la plus sérieuse tient au risque que cette interdiction prive certaines régions mal desservies par le rail de leur seul moyen de transport rapide, aggravant leur isolement.", "On pourrait objecter, non sans fondement, que cette mesure profite aux grandes métropoles bien reliées au prix d'une pénalisation disproportionnée des territoires enclavés."], explanation: "Le contre-argument nomme le mécanisme et les acteurs précis.", targetLanguageFeature: "renforcement d'un contre-argument affaibli", tags: ["counterargument", "transform", "variant"] },
    ],
    [
      { subSkill: "full-strength-counterargument-order", prompt: "Vous introduisez, dans toute sa portée, un contre-argument à l'interdiction des voitures thermiques en centre-ville d'ici 2030.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Aussi nécessaire soit-elle pour la qualité de l'air, cette interdiction pourrait pénaliser lourdement les ménages qui n'ont pas les moyens de changer de véhicule d'ici l'échéance.", "Ce sont précisément ces ménages, souvent les plus modestes, qui utilisent leur voiture pour des trajets que les transports en commun ne couvrent pas encore.", "L'objection mérite donc d'être prise au sérieux avant d'envisager une réponse."], correctAnswer: ["Aussi nécessaire soit-elle pour la qualité de l'air, cette interdiction pourrait pénaliser lourdement les ménages qui n'ont pas les moyens de changer de véhicule d'ici l'échéance.", "Ce sont précisément ces ménages, souvent les plus modestes, qui utilisent leur voiture pour des trajets que les transports en commun ne couvrent pas encore.", "L'objection mérite donc d'être prise au sérieux avant d'envisager une réponse."], acceptedAnswers: [], explanation: "L'objection est formulée avec sa concession, précisée par son public réel, puis reconnue comme sérieuse.", targetLanguageFeature: "organisation d'un contre-argument dans toute sa portée", tags: ["counterargument", "organization"] },
      { subSkill: "full-strength-counterargument-order-alternative", prompt: "Vous introduisez, dans toute sa portée, un contre-argument à l'interdiction de la publicité pour les voitures les plus polluantes.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Aussi justifiée soit-elle sur le plan écologique, cette interdiction pourrait fragiliser l'équilibre économique de médias déjà dépendants de ces recettes publicitaires.", "Ce sont précisément les médias locaux et indépendants, moins diversifiés dans leurs sources de revenus, qui seraient les plus exposés.", "L'objection mérite donc d'être prise au sérieux avant d'envisager une réponse."], correctAnswer: ["Aussi justifiée soit-elle sur le plan écologique, cette interdiction pourrait fragiliser l'équilibre économique de médias déjà dépendants de ces recettes publicitaires.", "Ce sont précisément les médias locaux et indépendants, moins diversifiés dans leurs sources de revenus, qui seraient les plus exposés.", "L'objection mérite donc d'être prise au sérieux avant d'envisager une réponse."], acceptedAnswers: [], explanation: "Même organisation : concession, public précis, reconnaissance du sérieux de l'objection.", targetLanguageFeature: "organisation d'un contre-argument dans toute sa portée", tags: ["counterargument", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-full-strength-counterargument", prompt: "Idée de départ : vous défendez la légalisation encadrée du cannabis. Introduisez, dans toute sa portée, l'objection selon laquelle une telle mesure pourrait normaliser une consommation à risque, en particulier chez les plus jeunes.", instructions: "Rédigez 3 à 4 phrases qui formulent ce contre-argument avec toute sa force, en nommant le mécanisme et le public concerné.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le contre-argument doit rester crédible et complet, sans être affaibli ni caricaturé.", targetLanguageFeature: "contre-argument formulé dans toute sa portée", tags: ["counterargument", "development"], selfCheck: ["Le contre-argument nomme un mécanisme réel, pas une crainte vague.", "Le public concerné est identifié précisément.", "L'objection n'est ni affaiblie ni exagérée."] },
      { subSkill: "guided-full-strength-counterargument-alternative", prompt: "Idée de départ : vous défendez l'instauration d'un salaire maximum dans les grandes entreprises. Introduisez, dans toute sa portée, l'objection selon laquelle une telle mesure pourrait inciter les dirigeants les plus qualifiés à quitter le pays.", instructions: "Rédigez 3 à 4 phrases qui formulent ce contre-argument avec toute sa force.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le contre-argument doit rester crédible et complet.", targetLanguageFeature: "contre-argument formulé dans toute sa portée", tags: ["counterargument", "development", "variant"], selfCheck: ["Le contre-argument nomme un mécanisme réel, pas une crainte vague.", "Le public ou l'acteur concerné est identifié précisément.", "L'objection n'est ni affaiblie ni exagérée."] },
    ],
    [
      { subSkill: "independent-full-strength-counterargument", prompt: "Vous défendez l'obligation de rénovation énergétique des logements anciens avant leur mise en location. Introduisez, dans toute sa portée, l'objection la plus sérieuse que pourraient formuler de petits propriétaires bailleurs.", instructions: "Rédigez 3 à 4 phrases qui formulent ce contre-argument avec toute sa force.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Un contre-argument C2 réussi reste crédible, complet et attribué à un acteur précis.", targetLanguageFeature: "contre-argument formulé dans toute sa portée, autonome", tags: ["counterargument", "production"], selfCheck: ["Le contre-argument nomme un mécanisme réel.", "L'acteur concerné est identifié précisément.", "L'objection n'est ni affaiblie ni exagérée."] },
      { subSkill: "independent-full-strength-counterargument-alternative", prompt: "Vous défendez la taxation accrue des successions les plus élevées. Introduisez, dans toute sa portée, l'objection la plus sérieuse que pourraient formuler des chefs de petites entreprises familiales.", instructions: "Rédigez 3 à 4 phrases qui formulent ce contre-argument avec toute sa force.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Un contre-argument C2 réussi reste crédible, complet et attribué à un acteur précis.", targetLanguageFeature: "contre-argument formulé dans toute sa portée, autonome", tags: ["counterargument", "production", "variant"], selfCheck: ["Le contre-argument nomme un mécanisme réel.", "L'acteur concerné est identifié précisément.", "L'objection n'est ni affaiblie ni exagérée."] },
    ],
  ]),

  ...taskThreeC2Path("t3-c2-nuancing-position", "nuancing-position", [
    [
      { subSkill: "precise-validity-conditions", prompt: "Vous nuancez avec finesse votre position favorable à la taxe carbone aux frontières.", instructions: "Choisissez la formulation qui définit le plus précisément les limites et conditions de validité de votre position.", options: ["Cette taxe est une bonne idée, mais il y a des limites.", "Cette mesure ne me semble justifiable que si elle s'accompagne d'un mécanisme de transition pour les pays les moins avancés et d'une révision périodique de son barème en fonction des efforts de décarbonation constatés.", "Ça dépend des pays.", "Il faut faire attention aux effets secondaires."], correctAnswer: "Cette mesure ne me semble justifiable que si elle s'accompagne d'un mécanisme de transition pour les pays les moins avancés et d'une révision périodique de son barème en fonction des efforts de décarbonation constatés.", acceptedAnswers: [], explanation: "Cette nuance précise deux conditions de validité concrètes et vérifiables, au lieu d'une réserve générale.", targetLanguageFeature: "conditions de validité précises", tags: ["nuance", "recognize"] },
      { subSkill: "precise-validity-conditions-alternative", prompt: "Vous nuancez avec finesse votre position favorable à l'interdiction des vols intérieurs courts.", instructions: "Choisissez la formulation qui définit le plus précisément les limites et conditions de validité de votre position.", options: ["Cette interdiction est une bonne idée, mais il y a des limites.", "Cette mesure ne me semble justifiable que là où une alternative ferroviaire assure un temps de trajet comparable et une fréquence suffisante, faute de quoi elle pénaliserait sans bénéfice réel.", "Ça dépend des régions.", "Il faut faire attention aux effets secondaires."], correctAnswer: "Cette mesure ne me semble justifiable que là où une alternative ferroviaire assure un temps de trajet comparable et une fréquence suffisante, faute de quoi elle pénaliserait sans bénéfice réel.", acceptedAnswers: [], explanation: "La nuance précise un critère vérifiable, au lieu d'une réserve générale.", targetLanguageFeature: "conditions de validité précises", tags: ["nuance", "recognize", "variant"] },
    ],
    [
      { subSkill: "validity-condition-connector", prompt: "Vous définissez avec finesse les conditions de validité de votre position.", instructions: "Complétez : « Cette mesure ne me semble justifiable qu'______ elle s'accompagne d'un mécanisme de transition pour les économies les plus vulnérables. »", options: [], correctAnswer: "à condition que", acceptedAnswers: ["dans la mesure où"], explanation: "Cette formule pose une condition de validité précise, plutôt qu'une réserve vague.", targetLanguageFeature: "connecteur de condition de validité", tags: ["nuance", "complete"] },
      { subSkill: "validity-condition-connector-alternative", prompt: "Vous définissez avec finesse les conditions de validité de votre position.", instructions: "Complétez : « Cette interdiction ne me semble justifiable qu'______ une alternative ferroviaire réellement comparable existe. »", options: [], correctAnswer: "à condition qu'", acceptedAnswers: ["dans la mesure où"], explanation: "La même formule pose ici une condition de validité précise.", targetLanguageFeature: "connecteur de condition de validité", tags: ["nuance", "complete", "variant"] },
    ],
    [
      { subSkill: "sharpen-vague-nuance", prompt: "Précisez cette nuance trop vague par des conditions de validité concrètes : « Il y a des limites à cette taxe. »", instructions: "Réécrivez en formulant des conditions de validité précises et vérifiables.", options: [], correctAnswer: null, acceptedAnswers: ["Cette taxe ne trouve sa pleine justification que si son produit finance effectivement la transition des secteurs concernés, et non le seul budget général.", "La validité de cette mesure suppose un réexamen régulier de son barème, sous peine de devenir un simple outil protectionniste déconnecté de son objectif initial."], explanation: "La nuance C2 précise des conditions vérifiables, plutôt qu'une réserve générale.", targetLanguageFeature: "précision des conditions de validité", tags: ["nuance", "transform"] },
      { subSkill: "sharpen-vague-nuance-alternative", prompt: "Précisez cette nuance trop vague par des conditions de validité concrètes : « Il y a des limites à cette interdiction. »", instructions: "Réécrivez en formulant des conditions de validité précises et vérifiables.", options: [], correctAnswer: null, acceptedAnswers: ["Cette interdiction ne trouve sa pleine justification que si elle s'accompagne d'un calendrier de développement ferroviaire vérifiable pour les liaisons concernées.", "La validité de cette mesure suppose un réexamen régulier des liaisons couvertes, sous peine de pénaliser des trajets sans réelle alternative."], explanation: "La nuance précise des conditions vérifiables.", targetLanguageFeature: "précision des conditions de validité", tags: ["nuance", "transform", "variant"] },
    ],
    [
      { subSkill: "validity-conditions-order", prompt: "Vous nuancez avec finesse votre position favorable à l'interdiction des voitures thermiques en centre-ville d'ici 2030.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Cette échéance ne me semble tenable que si elle s'accompagne d'aides ciblées pour les ménages modestes.", "et d'un développement suffisant des transports alternatifs dans les zones périphériques.", "Sans ces deux conditions, la mesure risquerait de pénaliser sans réduire durablement les déplacements contraints en voiture."], correctAnswer: ["Cette échéance ne me semble tenable que si elle s'accompagne d'aides ciblées pour les ménages modestes.", "et d'un développement suffisant des transports alternatifs dans les zones périphériques.", "Sans ces deux conditions, la mesure risquerait de pénaliser sans réduire durablement les déplacements contraints en voiture."], acceptedAnswers: [], explanation: "Les conditions de validité sont énumérées avant d'en tirer la conséquence si elles ne sont pas réunies.", targetLanguageFeature: "organisation de conditions de validité précises", tags: ["nuance", "organization"] },
      { subSkill: "validity-conditions-order-alternative", prompt: "Vous nuancez avec finesse votre position favorable à la légalisation encadrée du cannabis.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Cette légalisation ne me semble acceptable que si elle s'accompagne d'un contrôle strict de la qualité des produits.", "et d'un plafond de possession destiné à limiter la revente informelle.", "Sans ces deux conditions, la mesure risquerait de déplacer les problèmes plutôt que de les résoudre."], correctAnswer: ["Cette légalisation ne me semble acceptable que si elle s'accompagne d'un contrôle strict de la qualité des produits.", "et d'un plafond de possession destiné à limiter la revente informelle.", "Sans ces deux conditions, la mesure risquerait de déplacer les problèmes plutôt que de les résoudre."], acceptedAnswers: [], explanation: "Même organisation : conditions énumérées, puis conséquence de leur absence.", targetLanguageFeature: "organisation de conditions de validité précises", tags: ["nuance", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-validity-conditions", prompt: "Idée de départ : vous nuancez avec finesse votre position favorable à un salaire maximum dans les grandes entreprises, en précisant les conditions qui rendraient cette mesure acceptable (secteur concerné, seuil de taille d'entreprise, mécanisme d'exception pour certains profils).", instructions: "Rédigez 3 à 4 phrases qui définissent des conditions de validité précises et vérifiables.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La nuance doit préciser des conditions concrètes, pas une réserve générale.", targetLanguageFeature: "conditions de validité précises", tags: ["nuance", "development"], selfCheck: ["Au moins deux conditions concrètes et vérifiables sont formulées.", "Les conditions sont spécifiques à ce cas, pas génériques.", "La conséquence de leur absence est explicite."] },
      { subSkill: "guided-validity-conditions-alternative", prompt: "Idée de départ : vous nuancez avec finesse votre position favorable à l'obligation de rénovation énergétique des logements anciens, en précisant les conditions qui rendraient cette mesure acceptable (délai réaliste, aides proportionnées aux revenus, exceptions pour les logements protégés).", instructions: "Rédigez 3 à 4 phrases qui définissent des conditions de validité précises et vérifiables.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La nuance doit préciser des conditions concrètes.", targetLanguageFeature: "conditions de validité précises", tags: ["nuance", "development", "variant"], selfCheck: ["Au moins deux conditions concrètes et vérifiables sont formulées.", "Les conditions sont spécifiques à ce cas, pas génériques.", "La conséquence de leur absence est explicite."] },
    ],
    [
      { subSkill: "independent-validity-conditions", prompt: "Vous nuancez avec finesse votre position favorable à la taxation accrue des successions les plus élevées, en précisant les conditions qui rendraient cette mesure acceptable.", instructions: "Rédigez 3 à 4 phrases qui définissent des conditions de validité précises et vérifiables.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une nuance C2 réussie précise des conditions concrètes et vérifiables.", targetLanguageFeature: "conditions de validité précises, autonomes", tags: ["nuance", "production"], selfCheck: ["Au moins deux conditions concrètes et vérifiables sont formulées.", "Les conditions sont spécifiques à ce cas.", "La conséquence de leur absence est explicite."] },
      { subSkill: "independent-validity-conditions-alternative", prompt: "Vous nuancez avec finesse votre position favorable à l'interdiction de la publicité pour les voitures les plus polluantes, en précisant les conditions qui rendraient cette mesure acceptable.", instructions: "Rédigez 3 à 4 phrases qui définissent des conditions de validité précises et vérifiables.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une nuance C2 réussie précise des conditions concrètes et vérifiables.", targetLanguageFeature: "conditions de validité précises, autonomes", tags: ["nuance", "production", "variant"], selfCheck: ["Au moins deux conditions concrètes et vérifiables sont formulées.", "Les conditions sont spécifiques à ce cas.", "La conséquence de leur absence est explicite."] },
    ],
  ]),

  ...taskThreeC2Path("t3-c2-conclusion", "conclusion", [
    [
      { subSkill: "precise-synthesis-proportionate-opening", prompt: "Vous concluez une analyse sur la taxe carbone aux frontières.", instructions: "Choisissez la conclusion la plus adaptée au niveau C2.", options: ["Cette taxe est donc une solution parfaite.", "En subordonnant son acceptabilité à un mécanisme de transition et à une révision régulière de son barème, cette mesure pourrait concilier ambition climatique et équité internationale, sans que cela dispense d'en évaluer les effets réels dans les années à venir.", "Voilà pour la taxe carbone.", "Cette question restera sans doute débattue encore longtemps."], correctAnswer: "En subordonnant son acceptabilité à un mécanisme de transition et à une révision régulière de son barème, cette mesure pourrait concilier ambition climatique et équité internationale, sans que cela dispense d'en évaluer les effets réels dans les années à venir.", acceptedAnswers: [], explanation: "Cette conclusion résume précisément les conditions dégagées par l'analyse et ouvre sur un suivi proportionné, sans généraliser abusivement.", targetLanguageFeature: "synthèse précise et ouverture proportionnée", tags: ["conclusion", "recognize"] },
      { subSkill: "precise-synthesis-proportionate-opening-alternative", prompt: "Vous concluez une analyse sur l'interdiction des vols intérieurs courts.", instructions: "Choisissez la conclusion la plus adaptée au niveau C2.", options: ["Cette interdiction est donc une solution parfaite.", "En la limitant aux liaisons où une alternative ferroviaire comparable existe déjà, cette mesure pourrait réduire des émissions évitables sans pénaliser les régions les moins bien desservies, à condition d'accompagner son extension progressive.", "Voilà pour les vols intérieurs.", "Cette question restera sans doute débattue encore longtemps."], correctAnswer: "En la limitant aux liaisons où une alternative ferroviaire comparable existe déjà, cette mesure pourrait réduire des émissions évitables sans pénaliser les régions les moins bien desservies, à condition d'accompagner son extension progressive.", acceptedAnswers: [], explanation: "La conclusion résume précisément les conditions dégagées et ouvre sur une extension mesurée.", targetLanguageFeature: "synthèse précise et ouverture proportionnée", tags: ["conclusion", "recognize", "variant"] },
    ],
    [
      { subSkill: "proportionate-opening-connector", prompt: "Vous concluez par une synthèse précise et une ouverture proportionnée.", instructions: "Complétez : « Cette mesure pourrait concilier ambition climatique et équité internationale, ______ cela dispense d'en évaluer les effets réels dans les années à venir. »", options: [], correctAnswer: "sans que", acceptedAnswers: ["ce qui ne signifie pas que"], explanation: "Cette formule ouvre sur un suivi nécessaire sans relativiser la conclusion déjà établie.", targetLanguageFeature: "connecteur d'ouverture proportionnée", tags: ["conclusion", "complete"] },
      { subSkill: "proportionate-opening-connector-alternative", prompt: "Vous concluez par une synthèse précise et une ouverture proportionnée.", instructions: "Complétez : « Cette mesure pourrait réduire des émissions évitables, ______ cela dispense d'accompagner son extension par un suivi des régions concernées. »", options: [], correctAnswer: "sans que", acceptedAnswers: ["ce qui ne signifie pas que"], explanation: "La même formule ouvre ici sur un suivi nécessaire.", targetLanguageFeature: "connecteur d'ouverture proportionnée", tags: ["conclusion", "complete", "variant"] },
    ],
    [
      { subSkill: "add-precision-and-proportion", prompt: "Transformez cette conclusion trop générale pour qu'elle offre une synthèse précise et une ouverture proportionnée : « Cette taxe carbone a du bon et du mauvais, il faudra voir. »", instructions: "Réécrivez en résumant précisément les conditions dégagées par l'analyse et en ouvrant sur un suivi mesuré.", options: [], correctAnswer: null, acceptedAnswers: ["En subordonnant son acceptabilité à un accompagnement des économies les plus vulnérables, cette mesure pourrait constituer un levier climatique équitable, dont il conviendra d'évaluer les effets concrets sur les échanges internationaux.", "Si son efficacité dépend largement des conditions de transition qui l'accompagnent, cette taxe reste une piste à suivre de près plutôt qu'une solution acquise."], explanation: "La conclusion C2 résume les conditions précises de l'analyse et ouvre sur un suivi mesuré, sans rester vague.", targetLanguageFeature: "synthèse précise et ouverture proportionnée", tags: ["conclusion", "transform"] },
      { subSkill: "add-precision-and-proportion-alternative", prompt: "Transformez cette conclusion trop générale : « Cette interdiction des vols a du bon et du mauvais, il faudra voir. »", instructions: "Réécrivez en résumant précisément les conditions dégagées par l'analyse et en ouvrant sur un suivi mesuré.", options: [], correctAnswer: null, acceptedAnswers: ["En la limitant aux liaisons disposant d'une alternative ferroviaire comparable, cette interdiction pourrait réduire des émissions évitables, à condition de suivre de près son effet sur les régions les moins bien desservies.", "Si son efficacité dépend du développement préalable de liaisons ferroviaires suffisantes, cette mesure reste une piste à affiner plutôt qu'une solution définitive."], explanation: "La conclusion résume les conditions précises et ouvre sur un suivi mesuré.", targetLanguageFeature: "synthèse précise et ouverture proportionnée", tags: ["conclusion", "transform", "variant"] },
    ],
    [
      { subSkill: "precise-conclusion-order", prompt: "Vous concluez une analyse sur l'interdiction des voitures thermiques en centre-ville d'ici 2030.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Cette analyse a montré que l'acceptabilité de cette échéance dépend d'aides ciblées et d'alternatives de transport suffisantes.", "Sous ces conditions, la mesure paraît une étape raisonnable vers la réduction de la pollution urbaine.", "Il reviendra néanmoins aux collectivités d'en mesurer les effets réels sur les ménages les plus modestes."], correctAnswer: ["Cette analyse a montré que l'acceptabilité de cette échéance dépend d'aides ciblées et d'alternatives de transport suffisantes.", "Sous ces conditions, la mesure paraît une étape raisonnable vers la réduction de la pollution urbaine.", "Il reviendra néanmoins aux collectivités d'en mesurer les effets réels sur les ménages les plus modestes."], acceptedAnswers: [], explanation: "La conclusion résume les conditions précises, en tire une appréciation mesurée, puis ouvre sur un suivi proportionné.", targetLanguageFeature: "organisation synthèse précise → ouverture proportionnée", tags: ["conclusion", "organization"] },
      { subSkill: "precise-conclusion-order-alternative", prompt: "Vous concluez une analyse sur la légalisation encadrée du cannabis.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Cette analyse a montré que l'acceptabilité de cette légalisation dépend d'un contrôle strict de la qualité et d'un plafond de possession.", "Sous ces conditions, la mesure paraît une évolution raisonnable par rapport à une interdiction inefficace.", "Il reviendra néanmoins aux autorités d'en mesurer les effets réels sur la consommation des plus jeunes."], correctAnswer: ["Cette analyse a montré que l'acceptabilité de cette légalisation dépend d'un contrôle strict de la qualité et d'un plafond de possession.", "Sous ces conditions, la mesure paraît une évolution raisonnable par rapport à une interdiction inefficace.", "Il reviendra néanmoins aux autorités d'en mesurer les effets réels sur la consommation des plus jeunes."], acceptedAnswers: [], explanation: "Même organisation : conditions précises, appréciation mesurée, ouverture sur un suivi proportionné.", targetLanguageFeature: "organisation synthèse précise → ouverture proportionnée", tags: ["conclusion", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-precise-conclusion", prompt: "Idée de départ : vous concluez une analyse sur l'instauration d'un salaire maximum dans les grandes entreprises, dont l'acceptabilité dépend du secteur concerné et de mécanismes d'exception pour certains profils.", instructions: "Rédigez 2 à 3 phrases de conclusion qui résument précisément ces conditions et ouvrent sur un suivi proportionné, sans généraliser abusivement.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La conclusion doit résumer des conditions précises et ouvrir sur un suivi mesuré, ni exagéré ni minimisé.", targetLanguageFeature: "synthèse précise et ouverture proportionnée", tags: ["conclusion", "development"], selfCheck: ["La synthèse résume des conditions précises, pas une impression générale.", "L'ouverture reste proportionnée, ni exagérée ni minimisée.", "Aucun nouvel argument n'est introduit."] },
      { subSkill: "guided-precise-conclusion-alternative", prompt: "Idée de départ : vous concluez une analyse sur l'obligation de rénovation énergétique des logements anciens, dont l'acceptabilité dépend d'un délai réaliste et d'aides proportionnées aux revenus.", instructions: "Rédigez 2 à 3 phrases de conclusion qui résument précisément ces conditions et ouvrent sur un suivi proportionné.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La conclusion doit résumer des conditions précises et ouvrir sur un suivi mesuré.", targetLanguageFeature: "synthèse précise et ouverture proportionnée", tags: ["conclusion", "development", "variant"], selfCheck: ["La synthèse résume des conditions précises, pas une impression générale.", "L'ouverture reste proportionnée, ni exagérée ni minimisée.", "Aucun nouvel argument n'est introduit."] },
    ],
    [
      { subSkill: "independent-precise-conclusion", prompt: "Vous concluez une analyse sur la taxation accrue des successions les plus élevées, dont l'acceptabilité dépend d'un seuil précis et d'exceptions pour les petites entreprises familiales.", instructions: "Rédigez 2 à 3 phrases de conclusion qui résument précisément ces conditions et ouvrent sur un suivi proportionné.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une conclusion C2 réussie résume des conditions précises et ouvre sur un suivi mesuré.", targetLanguageFeature: "synthèse précise et ouverture proportionnée, autonome", tags: ["conclusion", "production"], selfCheck: ["La synthèse résume des conditions précises.", "L'ouverture reste proportionnée.", "Aucun nouvel argument n'est introduit."] },
      { subSkill: "independent-precise-conclusion-alternative", prompt: "Vous concluez une analyse sur l'interdiction de la publicité pour les voitures les plus polluantes, dont l'acceptabilité dépend d'un accompagnement des médias les plus dépendants de ces recettes.", instructions: "Rédigez 2 à 3 phrases de conclusion qui résument précisément ces conditions et ouvrent sur un suivi proportionné.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une conclusion C2 réussie résume des conditions précises et ouvre sur un suivi mesuré.", targetLanguageFeature: "synthèse précise et ouverture proportionnée, autonome", tags: ["conclusion", "production", "variant"], selfCheck: ["La synthèse résume des conditions précises.", "L'ouverture reste proportionnée.", "Aucun nouvel argument n'est introduit."] },
    ],
  ]),
];
