import type { PracticeExercise } from "./practice-curriculum";

/**
 * Fixed, editor-reviewed Task 3 B2 data. The helper only attaches the
 * deterministic six-stage metadata; all learning content is static below.
 */
type AuthoredVariant = Omit<
  PracticeExercise,
  "id" | "task" | "level" | "skill" | "exerciseType" | "difficulty" | "sequenceOrder" | "prerequisiteExerciseId"
>;

const STAGES: readonly PracticeExercise["exerciseType"][] = [
  "recognize",
  "complete",
  "transform",
  "organize",
  "develop",
  "produce",
];

const taskThreeB2Path = (
  prefix: string,
  skill: string,
  stages: readonly (readonly [AuthoredVariant, AuthoredVariant])[],
): readonly PracticeExercise[] =>
  stages.flatMap(([primary, alternative], index) => {
    const sequenceOrder = (index + 1) as 1 | 2 | 3 | 4 | 5 | 6;
    const shared = {
      task: "TASK_3" as const,
      level: "B2" as const,
      skill,
      exerciseType: STAGES[index]!,
      difficulty: sequenceOrder,
      sequenceOrder,
      prerequisiteExerciseId: index === 0 ? null : `${prefix}-${index}`,
    };
    return [
      { id: `${prefix}-${sequenceOrder}`, ...shared, ...primary },
      { id: `${prefix}-a${sequenceOrder}`, ...shared, ...alternative },
    ];
  });

export const TASK_3_B2_EXERCISES: readonly PracticeExercise[] = [
  ...taskThreeB2Path("t3-b2-introducing-topic", "introducing-topic", [
    [
      { subSkill: "neutral-debate-framing", prompt: "Deux documents discutent de l'installation de jardins partagés dans les villes : l'un insiste sur le lien social, l'autre sur le coût et l'entretien.", instructions: "Choisissez l'introduction qui présente le sujet sans donner votre avis trop tôt.", options: ["Les jardins partagés sont une très bonne idée.", "Les jardins partagés divisent les habitants, car ils peuvent créer du lien social mais demandent aussi des moyens et une organisation durable.", "Les villes devraient toutes avoir plus de jardins.", "Les habitants qui refusent les jardins ont tort."], correctAnswer: "Les jardins partagés divisent les habitants, car ils peuvent créer du lien social mais demandent aussi des moyens et une organisation durable.", acceptedAnswers: [], explanation: "Une introduction B2 présente le sujet et les deux aspects du débat avant de défendre une position.", targetLanguageFeature: "présentation neutre d'un débat", tags: ["introduction", "synthesis", "recognize"] },
      { subSkill: "neutral-debate-framing-alternative", prompt: "Deux documents débattent de la gratuité des musées un dimanche par mois : l'un y voit un moyen d'élargir l'accès, l'autre craint un coût important.", instructions: "Choisissez la formulation qui introduit clairement le débat.", options: ["Les musées doivent être gratuits.", "La gratuité ponctuelle des musées soulève la question de l'accès à la culture et de son financement.", "Les musées gratuits sont toujours meilleurs.", "Le prix des musées est trop élevé."], correctAnswer: "La gratuité ponctuelle des musées soulève la question de l'accès à la culture et de son financement.", acceptedAnswers: [], explanation: "La phrase nomme l'enjeu commun sans choisir encore un camp.", targetLanguageFeature: "enjeu formulé sans prise de position", tags: ["introduction", "recognize", "variant"] },
    ],
    [
      { subSkill: "debate-question", prompt: "Vous présentez deux sources sur le télétravail.", instructions: "Complétez : « Le débat porte sur la question de savoir si le télétravail ______ améliorer l'organisation du travail sans isoler les salariés. »", options: [], correctAnswer: "peut", acceptedAnswers: ["pourrait"], explanation: "La formulation présente une question ouverte plutôt qu'une réponse déjà décidée.", targetLanguageFeature: "formulation d'un enjeu", tags: ["introduction", "complete", "question"] },
      { subSkill: "debate-question-alternative", prompt: "Vous introduisez deux documents sur les repas végétariens dans les cantines.", instructions: "Complétez : « Ces documents interrogent la place que ______ prendre les repas végétariens dans la restauration scolaire. »", options: [], correctAnswer: "pourraient", acceptedAnswers: ["devraient"], explanation: "Le conditionnel permet d'ouvrir le débat sans imposer une conclusion.", targetLanguageFeature: "problématique ouverte", tags: ["introduction", "complete", "variant"] },
    ],
    [
      { subSkill: "opinion-to-neutral-issue", prompt: "Transformez : « Les vélos en libre-service sont indispensables dans toutes les villes. »", instructions: "Reformulez cette opinion pour présenter le débat de manière neutre.", options: [], correctAnswer: null, acceptedAnswers: ["Les vélos en libre-service posent la question de leur utilité et de leur coût pour les villes.", "Le développement des vélos en libre-service fait débat, notamment en raison de leur financement et de leur usage réel."], explanation: "On retire le jugement absolu et on fait apparaître les éléments que les sources peuvent discuter.", targetLanguageFeature: "passage de l'opinion à l'enjeu", tags: ["introduction", "transform", "neutrality"] },
      { subSkill: "opinion-to-neutral-issue-alternative", prompt: "Transformez : « Les écrans devraient être interdits à l'école. »", instructions: "Présentez cette idée comme un débat avec des enjeux opposés.", options: [], correctAnswer: null, acceptedAnswers: ["L'usage des écrans à l'école suscite un débat entre les possibilités pédagogiques et les risques de distraction.", "La place des écrans à l'école interroge leurs avantages pour apprendre et leurs effets possibles sur l'attention."], explanation: "Une bonne introduction B2 rend visibles les deux dimensions du sujet avant toute opinion personnelle.", targetLanguageFeature: "enjeu avec deux aspects", tags: ["introduction", "transform", "variant"] },
    ],
    [
      { subSkill: "theme-views-question-order", prompt: "Vous introduisez deux documents sur la limitation des voitures au centre-ville.", instructions: "Mettez les phrases dans l'ordre d'une introduction claire.", options: ["Ce sujet oppose souvent le besoin de réduire la pollution et les difficultés de déplacement de certains habitants.", "La place de la voiture dans les centres-villes fait actuellement débat.", "Il convient donc d'examiner les arguments avancés de part et d'autre."], correctAnswer: ["La place de la voiture dans les centres-villes fait actuellement débat.", "Ce sujet oppose souvent le besoin de réduire la pollution et les difficultés de déplacement de certains habitants.", "Il convient donc d'examiner les arguments avancés de part et d'autre."], acceptedAnswers: [], explanation: "L'introduction va du thème général aux enjeux opposés, puis annonce l'analyse des sources.", targetLanguageFeature: "thème → enjeux → annonce de l'analyse", tags: ["introduction", "organization", "synthesis"] },
      { subSkill: "theme-views-question-order-alternative", prompt: "Vous introduisez un débat sur l'ouverture des commerces le dimanche.", instructions: "Organisez les phrases.", options: ["La question divise entre la liberté de choix des consommateurs et les conditions de travail des salariés.", "L'ouverture des commerces le dimanche est régulièrement discutée.", "Les deux documents permettent d'examiner ces points de vue avant de se prononcer."], correctAnswer: ["L'ouverture des commerces le dimanche est régulièrement discutée.", "La question divise entre la liberté de choix des consommateurs et les conditions de travail des salariés.", "Les deux documents permettent d'examiner ces points de vue avant de se prononcer."], acceptedAnswers: [], explanation: "On nomme le thème, on précise l'opposition, puis on situe le rôle des documents.", targetLanguageFeature: "organisation d'une introduction", tags: ["introduction", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-source-aware-introduction", prompt: "Deux sources discutent de la création de zones sans voiture près des écoles : l'une met en avant la sécurité des enfants, l'autre souligne les contraintes pour les parents.", instructions: "Rédigez 3 ou 4 phrases : présentez le thème, faites apparaître les deux enjeux et annoncez que vous allez examiner les points de vue avant de donner votre avis.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "À ce stade, vous entraînez une entrée de synthèse : elle doit organiser le débat, pas encore le résoudre.", targetLanguageFeature: "introduction guidée de deux sources", tags: ["introduction", "development", "sources"], selfCheck: ["Je présente le thème sans donner encore mon opinion.", "Les deux enjeux ou points de vue sont clairement visibles.", "J'annonce le passage par les documents avant ma position personnelle."] },
      { subSkill: "guided-source-aware-introduction-alternative", prompt: "Deux documents débattent de l'interdiction des bouteilles en plastique lors des événements publics : l'un défend la réduction des déchets, l'autre évoque le coût des alternatives.", instructions: "Rédigez 3 ou 4 phrases qui introduisent le sujet et les enjeux, sans défendre déjà une solution.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le lecteur doit comprendre pourquoi le sujet fait débat avant de découvrir votre analyse.", targetLanguageFeature: "cadre neutre d'un débat", tags: ["introduction", "development", "variant"], selfCheck: ["J'identifie clairement le sujet commun aux deux documents.", "Je présente au moins un enjeu de chaque côté.", "Mon vocabulaire reste neutre et n'annonce pas prématurément ma conclusion."] },
    ],
    [
      { subSkill: "independent-source-aware-introduction", prompt: "Deux sources débattent de la mise en place d'un service municipal de location de vélos : l'une insiste sur la mobilité accessible, l'autre sur le coût et le risque d'un usage insuffisant.", instructions: "Rédigez une introduction de 50 à 70 mots : présentez le sujet, les deux principaux enjeux et la démarche de synthèse que vous allez suivre avant de prendre position.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une introduction B2 autonome prépare le lecteur à comprendre la comparaison des sources et la future position personnelle.", targetLanguageFeature: "introduction autonome de synthèse", tags: ["introduction", "production", "sources"], selfCheck: ["Le sujet et les deux enjeux sont clairement présentés.", "Je ne donne pas encore mon opinion personnelle.", "J'annonce que je vais examiner ou comparer les points de vue."] },
      { subSkill: "independent-source-aware-introduction-alternative", prompt: "Deux sources débattent de la possibilité de rendre les transports publics gratuits le week-end : l'une souligne l'accès pour tous, l'autre le financement nécessaire.", instructions: "Rédigez une introduction de 50 à 70 mots qui pose le débat, présente les enjeux opposés et prépare l'analyse des documents.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production doit rester équilibrée : elle introduit le débat avant de justifier une préférence.", targetLanguageFeature: "introduction autonome équilibrée", tags: ["introduction", "production", "variant"], selfCheck: ["Je formule le débat sous forme d'enjeu, pas de réponse évidente.", "Les deux points de vue sont représentés de manière équilibrée.", "L'introduction conduit naturellement vers l'analyse des sources."] },
    ],
  ]),
  ...taskThreeB2Path("t3-b2-reformulating-sources", "reformulating-sources", [
    [
      { subSkill: "faithful-main-idea", prompt: "Une source affirme : « Les bibliothèques devraient ouvrir le dimanche car les personnes qui travaillent en semaine pourraient enfin y accéder. »", instructions: "Choisissez la reformulation la plus fidèle.", options: ["La source dit que les bibliothèques sont inutiles en semaine.", "Selon cette source, ouvrir les bibliothèques le dimanche permettrait à davantage de salariés et d'étudiants d'en profiter.", "La source exige que toutes les bibliothèques restent ouvertes toute la nuit.", "Les bibliothèques sont réservées aux personnes qui travaillent."], correctAnswer: "Selon cette source, ouvrir les bibliothèques le dimanche permettrait à davantage de salariés et d'étudiants d'en profiter.", acceptedAnswers: [], explanation: "La reformulation conserve l'idée principale et le groupe concerné, sans reprendre exactement les mots de la source.", targetLanguageFeature: "reformulation fidèle d'une idée principale", tags: ["reformulation", "sources", "recognize"] },
      { subSkill: "faithful-main-idea-alternative", prompt: "Une source affirme : « Les cours en ligne offrent plus de souplesse aux étudiants qui habitent loin de leur établissement. »", instructions: "Choisissez la reformulation correcte.", options: ["La source pense que les cours en ligne sont plus faciles.", "D'après cette source, l'enseignement à distance peut faciliter l'accès aux études pour les personnes éloignées.", "La source veut supprimer toutes les universités.", "Les étudiants ne devraient plus se déplacer."], correctAnswer: "D'après cette source, l'enseignement à distance peut faciliter l'accès aux études pour les personnes éloignées.", acceptedAnswers: [], explanation: "La reformulation garde le lien entre distance et accessibilité sans ajouter une conclusion non présente dans le document.", targetLanguageFeature: "fidélité sans copie", tags: ["reformulation", "recognize", "variant"] },
    ],
    [
      { subSkill: "source-attribution", prompt: "Vous rapportez l'idée d'un premier document sur les jardins partagés.", instructions: "Complétez : « Selon le premier document, les jardins partagés ______ renforcer les liens entre les habitants. »", options: [], correctAnswer: "peuvent", acceptedAnswers: ["pourraient", "permettent de"], explanation: "L'attribution montre que l'idée appartient à la source et non encore à votre position personnelle.", targetLanguageFeature: "attribution à une source", tags: ["reformulation", "complete", "sources"] },
      { subSkill: "source-attribution-alternative", prompt: "Vous rapportez une source sur les écrans à l'école.", instructions: "Complétez : « D'après cette source, les outils numériques ______ soutenir certains apprentissages lorsqu'ils sont utilisés avec un objectif précis. »", options: [], correctAnswer: "peuvent", acceptedAnswers: ["pourraient", "sont susceptibles de"], explanation: "La formule attribue clairement l'argument au document tout en évitant de le présenter comme une vérité générale.", targetLanguageFeature: "verbe de reformulation attribuée", tags: ["reformulation", "complete", "variant"] },
    ],
    [
      { subSkill: "copy-to-paraphrase", prompt: "Reformulez sans copier : « La circulation automobile est responsable d'une grande partie de la pollution en ville. »", instructions: "Conservez l'idée et attribuez-la à la source.", options: [], correctAnswer: null, acceptedAnswers: ["Selon cette source, les voitures contribuent fortement à la pollution dans les zones urbaines.", "Le document souligne que le trafic routier est une cause importante de pollution dans les villes."], explanation: "Une reformulation change les mots et la structure tout en restant fidèle au message du document.", targetLanguageFeature: "paraphrase avec attribution", tags: ["reformulation", "transform", "sources"] },
      { subSkill: "copy-to-paraphrase-alternative", prompt: "Reformulez sans copier : « Les repas végétariens permettent de réduire l'impact environnemental de la restauration collective. »", instructions: "Gardez l'idée principale et mentionnez qu'elle vient de la source.", options: [], correctAnswer: null, acceptedAnswers: ["Le document estime que proposer davantage de menus végétariens peut limiter les effets écologiques de la restauration collective.", "Selon cette source, les choix alimentaires sans viande peuvent rendre les cantines plus respectueuses de l'environnement."], explanation: "La paraphrase remplace les mots de la source sans modifier son lien logique.", targetLanguageFeature: "reformulation sans déformation", tags: ["reformulation", "transform", "variant"] },
    ],
    [
      { subSkill: "two-source-summary-order", prompt: "Deux sources discutent du télétravail. L'une souligne la réduction des trajets ; l'autre craint la perte de liens entre collègues.", instructions: "Mettez les phrases dans l'ordre d'une synthèse courte et claire.", options: ["En revanche, la seconde source rappelle que le travail à distance peut isoler certains salariés.", "La première source met en avant le temps gagné grâce à l'absence de déplacements.", "Ces documents présentent donc à la fois un avantage pratique et une limite relationnelle."], correctAnswer: ["La première source met en avant le temps gagné grâce à l'absence de déplacements.", "En revanche, la seconde source rappelle que le travail à distance peut isoler certains salariés.", "Ces documents présentent donc à la fois un avantage pratique et une limite relationnelle."], acceptedAnswers: [], explanation: "On attribue chaque idée à son document, puis on relie les deux apports sans donner encore son opinion.", targetLanguageFeature: "source 1 → source 2 → synthèse", tags: ["reformulation", "organization", "sources"] },
      { subSkill: "two-source-summary-order-alternative", prompt: "Deux sources parlent de la gratuité des transports. L'une défend l'accès pour les personnes modestes ; l'autre évoque le coût pour les villes.", instructions: "Organisez ce court résumé.", options: ["La seconde souligne toutefois la difficulté de financer durablement cette mesure.", "La première source considère que la gratuité faciliterait les déplacements des personnes aux revenus limités.", "Les documents opposent ainsi un objectif d'égalité à une question de financement."], correctAnswer: ["La première source considère que la gratuité faciliterait les déplacements des personnes aux revenus limités.", "La seconde souligne toutefois la difficulté de financer durablement cette mesure.", "Les documents opposent ainsi un objectif d'égalité à une question de financement."], acceptedAnswers: [], explanation: "L'ordre permet de restituer les deux sources et de dégager leur opposition principale.", targetLanguageFeature: "résumé de deux points de vue", tags: ["reformulation", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-faithful-synthesis", prompt: "La première source défend l'installation de fontaines publiques pour réduire les bouteilles en plastique. La seconde craint le coût de leur entretien.", instructions: "Rédigez 3 ou 4 phrases : reformulez fidèlement chaque idée, attribuez-la au bon document et terminez par une phrase qui indique le débat commun.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le but est de restituer les sources avec vos propres mots, sans les confondre ni ajouter votre avis.", targetLanguageFeature: "synthèse guidée et fidèle", tags: ["reformulation", "development", "sources"], selfCheck: ["J'attribue clairement chaque idée à une source.", "Je reformule sans reprendre des expressions entières.", "Ma dernière phrase relie les deux idées sans introduire mon opinion."] },
      { subSkill: "guided-faithful-synthesis-alternative", prompt: "Une source soutient les cours de musique obligatoires à l'école pour favoriser la créativité. L'autre estime que les élèves ont déjà un emploi du temps trop chargé.", instructions: "Rédigez 3 ou 4 phrases qui reformulent les deux positions et font apparaître le point de désaccord.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une bonne synthèse B2 fait comprendre le désaccord tout en respectant les deux documents.", targetLanguageFeature: "reformulation de deux positions", tags: ["reformulation", "development", "variant"], selfCheck: ["Les deux points de vue sont présentés de manière distincte.", "Je garde les idées importantes sans ajouter d'argument personnel.", "Le désaccord est formulé clairement dans une phrase de synthèse."] },
    ],
    [
      { subSkill: "independent-faithful-synthesis", prompt: "Deux sources débattent de la création de marchés de producteurs dans les quartiers : l'une met en avant les produits locaux et les rencontres, l'autre s'inquiète des prix pour certains habitants.", instructions: "Rédigez 60 à 80 mots : reformulez les deux idées avec vos propres mots, attribuez-les clairement et indiquez l'enjeu qui les oppose, sans donner encore votre avis.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production B2 autonome doit laisser au lecteur la possibilité de reconnaître les deux sources avant votre prise de position.", targetLanguageFeature: "synthèse autonome de deux sources", tags: ["reformulation", "production", "sources"], selfCheck: ["Les deux sources sont clairement distinguées.", "Je reformule les idées principales sans les déformer.", "Je ne donne pas encore mon opinion personnelle."] },
      { subSkill: "independent-faithful-synthesis-alternative", prompt: "Deux documents discutent de la rénovation énergétique obligatoire des logements : l'un souligne les économies d'énergie, l'autre craint la charge financière pour les propriétaires.", instructions: "Rédigez 60 à 80 mots qui présentent fidèlement les deux points de vue et le débat commun, sans choisir encore une solution.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une synthèse réussie conserve l'équilibre entre les sources et prépare la future prise de position.", targetLanguageFeature: "synthèse autonome équilibrée", tags: ["reformulation", "production", "variant"], selfCheck: ["Chaque source est présentée de façon fidèle et équilibrée.", "Je reformule les idées avec mes propres mots.", "Je fais apparaître l'enjeu commun sans annoncer ma conclusion."] },
    ],
  ]),
];
