import type { PracticeExercise } from "./practice-curriculum";

/**
 * Fixed, editor-reviewed Task 3 C1 data, authored in its own module to avoid
 * touching practice-curriculum.ts while other agents edit it concurrently.
 * The helper only attaches the deterministic six-stage metadata; all
 * learning content is static below. justifying-position and
 * counterarguments already ship from practice-curriculum.ts directly.
 */
type AuthoredVariant = Omit<
  PracticeExercise,
  "id" | "task" | "level" | "skill" | "exerciseType" | "difficulty" | "sequenceOrder" | "prerequisiteExerciseId"
>;

const STAGES: readonly PracticeExercise["exerciseType"][] = [
  "recognize",
  "complete",
  "transform",
  "organize",
  "develop",
  "produce",
];

const taskThreeC1Path = (
  prefix: string,
  skill: string,
  stages: readonly (readonly [AuthoredVariant, AuthoredVariant])[],
): readonly PracticeExercise[] =>
  stages.flatMap(([primary, alternative], index) => {
    const sequenceOrder = (index + 1) as 1 | 2 | 3 | 4 | 5 | 6;
    const shared = {
      task: "TASK_3" as const,
      level: "C1" as const,
      skill,
      exerciseType: STAGES[index]!,
      difficulty: sequenceOrder,
      sequenceOrder,
      prerequisiteExerciseId: index === 0 ? null : `${prefix}-${index}`,
    };
    return [
      { id: `${prefix}-${sequenceOrder}`, ...shared, ...primary },
      { id: `${prefix}-a${sequenceOrder}`, ...shared, ...alternative },
    ];
  });

export const TASK_3_C1_EXERCISES: readonly PracticeExercise[] = [
  ...taskThreeC1Path("t3-c1-introducing-topic", "introducing-topic", [
    [
      { subSkill: "problematize-tension", prompt: "Deux documents portent sur l'instauration d'un jour de télétravail obligatoire : l'un souligne les gains de productivité, l'autre les risques pour la cohésion d'équipe.", instructions: "Choisissez la phrase qui pose une véritable problématique, plutôt que de seulement présenter le thème.", options: ["Le télétravail est de plus en plus répandu dans les entreprises.", "La question se pose de savoir si un jour de télétravail imposé peut renforcer l'efficacité individuelle sans fragiliser le collectif.", "Le télétravail obligatoire divise les salariés.", "Il existe plusieurs avis sur le télétravail."], correctAnswer: "La question se pose de savoir si un jour de télétravail imposé peut renforcer l'efficacité individuelle sans fragiliser le collectif.", acceptedAnswers: [], explanation: "Cette phrase formule une véritable problématique : elle met en tension deux enjeux identifiés par les sources, plutôt que d'annoncer un thème ou une opposition brute.", targetLanguageFeature: "problématique articulée en tension", tags: ["introduction", "synthesis", "recognize"] },
      { subSkill: "problematize-tension-alternative", prompt: "Deux documents portent sur l'encadrement de l'intelligence artificielle dans le recrutement : l'un souligne les gains d'efficacité, l'autre les risques de biais.", instructions: "Choisissez la phrase qui pose une véritable problématique.", options: ["L'intelligence artificielle est utilisée dans le recrutement.", "La question se pose de savoir si l'automatisation du tri des candidatures peut gagner en efficacité sans reproduire les biais qu'elle prétend corriger.", "L'IA dans le recrutement fait débat.", "Plusieurs entreprises utilisent l'IA."], correctAnswer: "La question se pose de savoir si l'automatisation du tri des candidatures peut gagner en efficacité sans reproduire les biais qu'elle prétend corriger.", acceptedAnswers: [], explanation: "La phrase met en tension deux enjeux réels, au lieu de simplement constater l'usage de l'IA.", targetLanguageFeature: "problématique articulée en tension", tags: ["introduction", "recognize", "variant"] },
    ],
    [
      { subSkill: "problematizing-verb", prompt: "Vous formulez la problématique du débat sur le télétravail imposé.", instructions: "Complétez : « La question ______ de savoir si un jour de télétravail obligatoire peut concilier efficacité individuelle et cohésion d'équipe. »", options: [], correctAnswer: "se pose", acceptedAnswers: ["se trouve posée"], explanation: "Cette formule introduit une problématique ouverte, sans trancher d'avance.", targetLanguageFeature: "formulation d'une problématique", tags: ["introduction", "complete", "question"] },
      { subSkill: "problematizing-verb-alternative", prompt: "Vous formulez la problématique du débat sur l'IA dans le recrutement.", instructions: "Complétez : « La question ______ de savoir si l'automatisation du recrutement peut gagner en efficacité sans reproduire des biais. »", options: [], correctAnswer: "se pose", acceptedAnswers: ["se trouve posée"], explanation: "La même formule reste utile pour introduire une problématique ouverte.", targetLanguageFeature: "formulation d'une problématique", tags: ["introduction", "complete", "variant"] },
    ],
    [
      { subSkill: "opinion-to-problematic", prompt: "Transformez cette présentation neutre mais plate en une véritable problématique : « Le télétravail obligatoire a des avantages et des inconvénients. »", instructions: "Reformulez pour poser une problématique qui met les enjeux en tension.", options: [], correctAnswer: null, acceptedAnswers: ["La question est de savoir si un jour de télétravail imposé peut réellement améliorer l'efficacité sans nuire à la cohésion des équipes.", "Un jour de télétravail obligatoire peut-il gagner en efficacité ce qu'il risque de perdre en esprit d'équipe ?"], explanation: "La problématique nomme explicitement la tension entre les deux enjeux, plutôt que de juxtaposer des avantages et des inconvénients.", targetLanguageFeature: "passage d'un constat plat à une problématique", tags: ["introduction", "transform", "neutrality"] },
      { subSkill: "opinion-to-problematic-alternative", prompt: "Transformez : « L'IA dans le recrutement a des avantages et des inconvénients. »", instructions: "Reformulez pour poser une problématique qui met les enjeux en tension.", options: [], correctAnswer: null, acceptedAnswers: ["La question est de savoir si l'automatisation du recrutement peut réellement gagner en efficacité sans reproduire les biais qu'elle prétend éliminer.", "L'IA dans le recrutement peut-elle gagner en objectivité ce qu'elle risque de perdre en discernement humain ?"], explanation: "La problématique met en tension deux enjeux précis plutôt que de les juxtaposer.", targetLanguageFeature: "passage d'un constat plat à une problématique", tags: ["introduction", "transform", "variant"] },
    ],
    [
      { subSkill: "problematic-intro-order", prompt: "Vous construisez une introduction qui pose une problématique sur le télétravail imposé.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Le télétravail imposé un jour par semaine se généralise dans de nombreuses entreprises.", "La question est de savoir si cette mesure améliore réellement l'efficacité sans fragiliser la cohésion des équipes.", "C'est ce que les deux documents permettent d'examiner."], correctAnswer: ["Le télétravail imposé un jour par semaine se généralise dans de nombreuses entreprises.", "La question est de savoir si cette mesure améliore réellement l'efficacité sans fragiliser la cohésion des équipes.", "C'est ce que les deux documents permettent d'examiner."], acceptedAnswers: [], explanation: "L'introduction va du constat général à la problématique précise, puis annonce l'analyse des sources.", targetLanguageFeature: "constat → problématique → annonce", tags: ["introduction", "organization", "synthesis"] },
      { subSkill: "problematic-intro-order-alternative", prompt: "Vous construisez une introduction qui pose une problématique sur l'IA dans le recrutement.", instructions: "Remettez ces éléments dans l'ordre.", options: ["L'IA occupe une place croissante dans les processus de recrutement.", "La question est de savoir si cette automatisation gagne en efficacité sans reproduire les biais qu'elle prétend corriger.", "C'est ce que les deux documents permettent d'examiner."], correctAnswer: ["L'IA occupe une place croissante dans les processus de recrutement.", "La question est de savoir si cette automatisation gagne en efficacité sans reproduire les biais qu'elle prétend corriger.", "C'est ce que les deux documents permettent d'examiner."], acceptedAnswers: [], explanation: "Même structure : constat, puis problématique, puis annonce de l'analyse.", targetLanguageFeature: "constat → problématique → annonce", tags: ["introduction", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-problematic-intro", prompt: "Idée de départ : vous introduisez un débat sur l'instauration d'une taxe carbone aux frontières.", instructions: "Rédigez 2 à 3 phrases qui posent une véritable problématique (une tension, pas seulement un thème).", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La problématique doit exprimer une tension réelle entre deux enjeux, sans prise de position.", targetLanguageFeature: "problématique articulée", tags: ["introduction", "development"], selfCheck: ["La problématique formule une tension réelle, pas seulement un thème.", "La formulation reste neutre, sans prise de position.", "Le lien avec le débat des sources est clair."] },
      { subSkill: "guided-problematic-intro-alternative", prompt: "Idée de départ : vous introduisez un débat sur la limitation du temps d'écran des enfants à l'école.", instructions: "Rédigez 2 à 3 phrases qui posent une véritable problématique.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La problématique doit exprimer une tension réelle, sans prise de position.", targetLanguageFeature: "problématique articulée", tags: ["introduction", "development", "variant"], selfCheck: ["La problématique formule une tension réelle, pas seulement un thème.", "La formulation reste neutre, sans prise de position.", "Le lien avec le débat des sources est clair."] },
    ],
    [
      { subSkill: "independent-problematic-intro", prompt: "Vous introduisez un débat sur l'obligation du service civique pour les jeunes.", instructions: "Rédigez 2 à 3 phrases qui posent une problématique claire, sans prise de position.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une introduction C1 réussie pose une problématique précise, en tension, avant toute analyse.", targetLanguageFeature: "problématique autonome", tags: ["introduction", "production"], selfCheck: ["La problématique formule une tension réelle.", "Aucune position personnelle n'apparaît encore.", "L'introduction annonce l'examen des sources."] },
      { subSkill: "independent-problematic-intro-alternative", prompt: "Vous introduisez un débat sur la suppression des notes à l'école primaire.", instructions: "Rédigez 2 à 3 phrases qui posent une problématique claire, sans prise de position.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une introduction C1 réussie pose une problématique précise, en tension, avant toute analyse.", targetLanguageFeature: "problématique autonome", tags: ["introduction", "production", "variant"], selfCheck: ["La problématique formule une tension réelle.", "Aucune position personnelle n'apparaît encore.", "L'introduction annonce l'examen des sources."] },
    ],
  ]),

  ...taskThreeC1Path("t3-c1-reformulating-sources", "reformulating-sources", [
    [
      { subSkill: "faithful-distinct-reformulation", prompt: "Deux sources s'opposent sur les écrans à l'école : la première affirme qu'ils réduisent la capacité d'attention ; la seconde soutient qu'ils favorisent le travail collaboratif.", instructions: "Choisissez la reformulation la plus fidèle, qui distingue clairement les deux points de vue.", options: ["Les écrans sont mauvais pour l'attention mais bons pour le travail en groupe.", "Selon la première source, les écrans nuiraient à la concentration, tandis que la seconde y voit un outil au service du travail collaboratif.", "Les deux sources pensent la même chose sur les écrans.", "Les écrans sont un sujet débattu."], correctAnswer: "Selon la première source, les écrans nuiraient à la concentration, tandis que la seconde y voit un outil au service du travail collaboratif.", acceptedAnswers: [], explanation: "Cette reformulation attribue chaque idée à sa source et reste fidèle à la nuance de chacune.", targetLanguageFeature: "reformulation fidèle et attribuée", tags: ["sources", "recognize"] },
      { subSkill: "faithful-distinct-reformulation-alternative", prompt: "Deux sources s'opposent sur les compléments alimentaires : la première signale des risques sanitaires mal contrôlés, la seconde met en avant des bénéfices nutritionnels validés par des études.", instructions: "Choisissez la reformulation la plus fidèle, qui distingue clairement les deux points de vue.", options: ["Les compléments alimentaires sont dangereux mais utiles.", "Selon la première source, ces produits présenteraient des risques insuffisamment encadrés, tandis que la seconde souligne des bénéfices confirmés par la recherche.", "Les deux sources pensent la même chose.", "Les compléments alimentaires sont un sujet débattu."], correctAnswer: "Selon la première source, ces produits présenteraient des risques insuffisamment encadrés, tandis que la seconde souligne des bénéfices confirmés par la recherche.", acceptedAnswers: [], explanation: "Chaque idée reste attribuée à sa source, sans confusion ni déformation.", targetLanguageFeature: "reformulation fidèle et attribuée", tags: ["sources", "recognize", "variant"] },
    ],
    [
      { subSkill: "attribution-verb", prompt: "Vous reformulez fidèlement deux points de vue opposés.", instructions: "Complétez : « Alors que la première source ______ un effet négatif sur l'attention, la seconde met en avant un bénéfice pour la coopération. »", options: [], correctAnswer: "pointe", acceptedAnswers: ["souligne", "dénonce"], explanation: "Ce verbe attribue clairement l'idée à la première source, sans la mêler à la seconde.", targetLanguageFeature: "verbe d'attribution", tags: ["sources", "complete"] },
      { subSkill: "attribution-verb-alternative", prompt: "Vous reformulez fidèlement deux points de vue opposés.", instructions: "Complétez : « Alors que la première source ______ des risques sanitaires, la seconde met en avant des bénéfices validés par la recherche. »", options: [], correctAnswer: "pointe", acceptedAnswers: ["souligne", "dénonce"], explanation: "Le même type de verbe d'attribution reste utile ici.", targetLanguageFeature: "verbe d'attribution", tags: ["sources", "complete", "variant"] },
    ],
    [
      { subSkill: "unmix-sources", prompt: "Reformulez fidèlement, en distinguant les deux sources, ce résumé qui les confond : « Les écrans à l'école, c'est compliqué, il y a du bon et du mauvais. »", instructions: "Réécrivez en attribuant clairement chaque idée à sa source.", options: [], correctAnswer: null, acceptedAnswers: ["La première source met en garde contre une baisse de concentration, tandis que la seconde souligne un potentiel pour le travail en équipe.", "D'un côté, une source signale un risque pour l'attention ; de l'autre, une seconde y voit un levier pour la collaboration."], explanation: "La reformulation distingue nettement les deux sources au lieu de les fondre en un jugement général.", targetLanguageFeature: "distinction des sources", tags: ["sources", "transform"] },
      { subSkill: "unmix-sources-alternative", prompt: "Reformulez fidèlement, en distinguant les deux sources, ce résumé qui les confond : « Les compléments alimentaires, c'est compliqué, il y a du bon et du mauvais. »", instructions: "Réécrivez en attribuant clairement chaque idée à sa source.", options: [], correctAnswer: null, acceptedAnswers: ["La première source met en garde contre des risques sanitaires insuffisamment encadrés, tandis que la seconde souligne des bénéfices reconnus par la recherche.", "D'un côté, une source alerte sur des risques mal maîtrisés ; de l'autre, une seconde souligne des bénéfices validés scientifiquement."], explanation: "La reformulation distingue nettement les deux sources.", targetLanguageFeature: "distinction des sources", tags: ["sources", "transform", "variant"] },
    ],
    [
      { subSkill: "distinct-reformulation-order", prompt: "Vous reformulez fidèlement deux sources sur le télétravail des enseignants.", instructions: "Remettez ces éléments dans l'ordre.", options: ["La première source estime que le télétravail des enseignants complique le suivi des élèves en difficulté.", "La seconde, à l'inverse, souligne le gain de temps qu'il permet pour la préparation des cours.", "Ces deux points de vue restent difficiles à concilier."], correctAnswer: ["La première source estime que le télétravail des enseignants complique le suivi des élèves en difficulté.", "La seconde, à l'inverse, souligne le gain de temps qu'il permet pour la préparation des cours.", "Ces deux points de vue restent difficiles à concilier."], acceptedAnswers: [], explanation: "Chaque source est présentée avant le constat final de tension entre les deux.", targetLanguageFeature: "organisation d'une reformulation distinguée", tags: ["sources", "organization"] },
      { subSkill: "distinct-reformulation-order-alternative", prompt: "Vous reformulez fidèlement deux sources sur la vidéosurveillance dans les lycées.", instructions: "Remettez ces éléments dans l'ordre.", options: ["La première source estime que la vidéosurveillance dans les lycées dissuade les incidents.", "La seconde, à l'inverse, souligne le climat de méfiance qu'elle peut installer.", "Ces deux points de vue restent difficiles à concilier."], correctAnswer: ["La première source estime que la vidéosurveillance dans les lycées dissuade les incidents.", "La seconde, à l'inverse, souligne le climat de méfiance qu'elle peut installer.", "Ces deux points de vue restent difficiles à concilier."], acceptedAnswers: [], explanation: "Même organisation : chaque source, puis le constat de tension.", targetLanguageFeature: "organisation d'une reformulation distinguée", tags: ["sources", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-distinct-reformulation", prompt: "Idée de départ : deux sources sur la suppression des devoirs à la maison, l'une soulignant un allègement de la charge mentale des élèves, l'autre un risque de creuser les inégalités entre familles.", instructions: "Rédigez 2 à 3 phrases qui reformulent fidèlement chaque source, en les distinguant clairement.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Chaque source doit rester identifiable et la reformulation ne doit pas déformer ses propos.", targetLanguageFeature: "reformulation fidèle et distinguée", tags: ["sources", "development"], selfCheck: ["Chaque source est clairement identifiée et distinguée.", "La reformulation reste fidèle, sans déformer les propos.", "Aucun jugement personnel ne s'ajoute aux deux points de vue."] },
      { subSkill: "guided-distinct-reformulation-alternative", prompt: "Idée de départ : deux sources sur la généralisation des menus végétariens dans les cantines, l'une soulignant un bénéfice environnemental, l'autre un risque de carences si mal encadré.", instructions: "Rédigez 2 à 3 phrases qui reformulent fidèlement chaque source, en les distinguant clairement.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Chaque source doit rester identifiable et la reformulation ne doit pas déformer ses propos.", targetLanguageFeature: "reformulation fidèle et distinguée", tags: ["sources", "development", "variant"], selfCheck: ["Chaque source est clairement identifiée et distinguée.", "La reformulation reste fidèle, sans déformer les propos.", "Aucun jugement personnel ne s'ajoute aux deux points de vue."] },
    ],
    [
      { subSkill: "independent-distinct-reformulation", prompt: "Vous reformulez fidèlement deux sources sur l'usage des drones de livraison en ville, l'une insistant sur le gain de temps, l'autre sur les nuisances sonores.", instructions: "Rédigez 2 à 3 phrases qui reformulent fidèlement chaque source, en les distinguant clairement.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une reformulation C1 réussie attribue chaque idée à sa source sans les mélanger.", targetLanguageFeature: "reformulation fidèle et distinguée, autonome", tags: ["sources", "production"], selfCheck: ["Chaque source est clairement identifiée.", "La reformulation reste fidèle à chaque propos.", "Aucun jugement personnel ne s'ajoute."] },
      { subSkill: "independent-distinct-reformulation-alternative", prompt: "Vous reformulez fidèlement deux sources sur l'usage obligatoire du casque à vélo en ville, l'une insistant sur la sécurité, l'autre sur la liberté individuelle réduite.", instructions: "Rédigez 2 à 3 phrases qui reformulent fidèlement chaque source, en les distinguant clairement.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une reformulation C1 réussie attribue chaque idée à sa source sans les mélanger.", targetLanguageFeature: "reformulation fidèle et distinguée, autonome", tags: ["sources", "production", "variant"], selfCheck: ["Chaque source est clairement identifiée.", "La reformulation reste fidèle à chaque propos.", "Aucun jugement personnel ne s'ajoute."] },
    ],
  ]),

  ...taskThreeC1Path("t3-c1-identifying-arguments", "identifying-arguments", [
    [
      { subSkill: "distinguish-argument-justification", prompt: "Dans un texte défendant la semaine de 4 jours à l'école, on trouve : « La semaine de 4 jours améliore la concentration des élèves, car elle réduit la fatigue accumulée en fin de semaine. »", instructions: "Choisissez la phrase qui identifie correctement l'argument et sa justification.", options: ["L'argument est que la semaine dure 4 jours.", "L'argument est que la concentration s'améliore ; la justification est la réduction de la fatigue en fin de semaine.", "La justification est que les élèves aiment avoir un jour de repos.", "L'argument et la justification sont la même chose ici."], correctAnswer: "L'argument est que la concentration s'améliore ; la justification est la réduction de la fatigue en fin de semaine.", acceptedAnswers: [], explanation: "L'argument est l'affirmation défendue ; la justification est la raison qui la soutient. Ici, elles sont distinctes.", targetLanguageFeature: "distinction argument / justification", tags: ["argumentation", "recognize"] },
      { subSkill: "distinguish-argument-justification-alternative", prompt: "Dans un texte défendant le revenu universel, on trouve : « Le revenu universel réduirait la précarité, car il garantit un socle financier indépendant de l'emploi. »", instructions: "Choisissez la phrase qui identifie correctement l'argument et sa justification.", options: ["L'argument est que le revenu universel existe.", "L'argument est une réduction de la précarité ; la justification est la garantie d'un socle financier indépendant de l'emploi.", "La justification est que tout le monde touche de l'argent.", "L'argument et la justification sont la même chose ici."], correctAnswer: "L'argument est une réduction de la précarité ; la justification est la garantie d'un socle financier indépendant de l'emploi.", acceptedAnswers: [], explanation: "L'argument (réduction de la précarité) reste distinct de sa justification (le socle garanti).", targetLanguageFeature: "distinction argument / justification", tags: ["argumentation", "recognize", "variant"] },
    ],
    [
      { subSkill: "justification-verb", prompt: "Vous distinguez un argument de sa justification.", instructions: "Complétez : « L'argument avancé est une amélioration de la concentration ; il ______ par la baisse de fatigue en fin de semaine. »", options: [], correctAnswer: "se justifie", acceptedAnswers: ["s'explique"], explanation: "Ce verbe relie explicitement l'argument à sa justification sans les confondre.", targetLanguageFeature: "verbe de mise en relation argument/justification", tags: ["argumentation", "complete"] },
      { subSkill: "justification-verb-alternative", prompt: "Vous distinguez un argument de sa justification.", instructions: "Complétez : « L'argument avancé est une réduction de la précarité ; il ______ par la garantie d'un revenu indépendant de l'emploi. »", options: [], correctAnswer: "se justifie", acceptedAnswers: ["s'explique"], explanation: "Le même verbe relie ici l'argument à sa justification.", targetLanguageFeature: "verbe de mise en relation argument/justification", tags: ["argumentation", "complete", "variant"] },
    ],
    [
      { subSkill: "separate-argument-justification", prompt: "Ce passage mélange argument et justification sans les distinguer : « La semaine de 4 jours, c'est bien parce que les élèves sont moins fatigués et donc plus concentrés. »", instructions: "Réécrivez en séparant clairement l'argument (l'affirmation) de sa justification (la raison).", options: [], correctAnswer: null, acceptedAnswers: ["La semaine de 4 jours améliorerait la concentration des élèves ; cet effet s'expliquerait par une fatigue réduite en fin de semaine.", "L'argument central est celui d'une meilleure concentration, justifié par la diminution de la fatigue accumulée."], explanation: "La réécriture rend visible la structure argument puis justification, au lieu de les fondre en une seule affirmation.", targetLanguageFeature: "séparation argument / justification", tags: ["argumentation", "transform"] },
      { subSkill: "separate-argument-justification-alternative", prompt: "Ce passage mélange argument et justification : « Le revenu universel, c'est bien parce que les gens ont un filet de sécurité et donc moins de précarité. »", instructions: "Réécrivez en séparant clairement l'argument de sa justification.", options: [], correctAnswer: null, acceptedAnswers: ["Le revenu universel réduirait la précarité ; cet effet s'expliquerait par la garantie d'un socle financier indépendant de l'emploi.", "L'argument central est celui d'une précarité réduite, justifié par la garantie d'un revenu de base."], explanation: "La structure argument puis justification devient explicite.", targetLanguageFeature: "séparation argument / justification", tags: ["argumentation", "transform", "variant"] },
    ],
    [
      { subSkill: "argument-justification-order", prompt: "Vous distinguez argument et justification dans un texte sur le vote obligatoire.", instructions: "Remettez ces éléments dans l'ordre.", options: ["L'argument central est que le vote obligatoire renforcerait la légitimité des élus.", "Cette affirmation se justifie par une participation plus représentative de l'ensemble de la population.", "Ce lien entre argument et justification mérite d'être examiné avec attention."], correctAnswer: ["L'argument central est que le vote obligatoire renforcerait la légitimité des élus.", "Cette affirmation se justifie par une participation plus représentative de l'ensemble de la population.", "Ce lien entre argument et justification mérite d'être examiné avec attention."], acceptedAnswers: [], explanation: "L'argument est posé avant sa justification, puis vient un recul critique sur ce lien.", targetLanguageFeature: "organisation argument → justification", tags: ["argumentation", "organization"] },
      { subSkill: "argument-justification-order-alternative", prompt: "Vous distinguez argument et justification dans un texte sur l'allongement du congé parental.", instructions: "Remettez ces éléments dans l'ordre.", options: ["L'argument central est que l'allongement du congé parental favoriserait le développement de l'enfant.", "Cette affirmation se justifie par un temps de présence parentale prolongé durant les premiers mois.", "Ce lien entre argument et justification mérite d'être examiné avec attention."], correctAnswer: ["L'argument central est que l'allongement du congé parental favoriserait le développement de l'enfant.", "Cette affirmation se justifie par un temps de présence parentale prolongé durant les premiers mois.", "Ce lien entre argument et justification mérite d'être examiné avec attention."], acceptedAnswers: [], explanation: "Même organisation : argument, puis justification, puis recul critique.", targetLanguageFeature: "organisation argument → justification", tags: ["argumentation", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-argument-justification", prompt: "Idée de départ : un texte affirme que l'interdiction des sacs plastiques réduit la pollution des océans.", instructions: "Rédigez 2 à 3 phrases qui distinguent clairement cet argument de sa justification (la raison qui le soutient).", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "L'argument (l'affirmation) doit rester distinct de sa justification (la raison).", targetLanguageFeature: "distinction argument / justification", tags: ["argumentation", "development"], selfCheck: ["L'argument (l'affirmation) est clairement identifié.", "La justification (la raison) est distincte de l'argument.", "Le lien logique entre les deux est explicite."] },
      { subSkill: "guided-argument-justification-alternative", prompt: "Idée de départ : un texte affirme que la taxation des produits ultra-transformés améliorerait la santé publique.", instructions: "Rédigez 2 à 3 phrases qui distinguent clairement cet argument de sa justification.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "L'argument doit rester distinct de sa justification.", targetLanguageFeature: "distinction argument / justification", tags: ["argumentation", "development", "variant"], selfCheck: ["L'argument (l'affirmation) est clairement identifié.", "La justification (la raison) est distincte de l'argument.", "Le lien logique entre les deux est explicite."] },
    ],
    [
      { subSkill: "independent-argument-justification", prompt: "Vous analysez un texte qui affirme que la généralisation du covoiturage réduirait les embouteillages urbains.", instructions: "Rédigez 2 à 3 phrases qui distinguent clairement cet argument de sa justification.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une analyse C1 réussie distingue nettement l'argument de sa justification.", targetLanguageFeature: "distinction argument / justification, autonome", tags: ["argumentation", "production"], selfCheck: ["L'argument est clairement identifié.", "La justification est distincte de l'argument.", "Le lien logique entre les deux est explicite."] },
      { subSkill: "independent-argument-justification-alternative", prompt: "Vous analysez un texte qui affirme que la généralisation du vélo électrique en libre-service réduirait la pollution urbaine.", instructions: "Rédigez 2 à 3 phrases qui distinguent clairement cet argument de sa justification.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une analyse C1 réussie distingue nettement l'argument de sa justification.", targetLanguageFeature: "distinction argument / justification, autonome", tags: ["argumentation", "production", "variant"], selfCheck: ["L'argument est clairement identifié.", "La justification est distincte de l'argument.", "Le lien logique entre les deux est explicite."] },
    ],
  ]),

  ...taskThreeC1Path("t3-c1-comparing-viewpoints", "comparing-viewpoints", [
    [
      { subSkill: "organize-agreement-disagreement", prompt: "Deux sources sur les cours en ligne à l'université s'accordent sur la souplesse qu'ils offrent, mais divergent sur leurs effets sociaux : la première n'y voit pas de problème, la seconde s'inquiète de l'isolement des étudiants.", instructions: "Choisissez la phrase qui organise le mieux cet accord et ce désaccord.", options: ["Les deux sources ne sont pas d'accord sur les cours en ligne.", "Si les deux sources reconnaissent la souplesse qu'apportent les cours en ligne, elles s'opposent sur le risque d'isolement qu'ils feraient courir aux étudiants.", "Les cours en ligne sont flexibles.", "Une source aime les cours en ligne, l'autre non."], correctAnswer: "Si les deux sources reconnaissent la souplesse qu'apportent les cours en ligne, elles s'opposent sur le risque d'isolement qu'ils feraient courir aux étudiants.", acceptedAnswers: [], explanation: "Cette phrase organise clairement un accord partagé puis un désaccord précis, au lieu de juxtaposer les deux sources.", targetLanguageFeature: "comparaison organisée accord / désaccord", tags: ["comparison", "recognize"] },
      { subSkill: "organize-agreement-disagreement-alternative", prompt: "Deux sources sur la semaine de travail de 4 jours en entreprise s'accordent sur le bien-être des salariés, mais divergent sur sa faisabilité : la première la juge réalisable partout, la seconde la limite aux grandes entreprises.", instructions: "Choisissez la phrase qui organise le mieux cet accord et ce désaccord.", options: ["Les deux sources ne sont pas d'accord sur la semaine de 4 jours.", "Si les deux sources reconnaissent le bien-être qu'apporte la semaine de 4 jours, elles s'opposent sur sa faisabilité selon la taille de l'entreprise.", "La semaine de 4 jours est agréable pour les salariés.", "Une source aime la semaine de 4 jours, l'autre non."], correctAnswer: "Si les deux sources reconnaissent le bien-être qu'apporte la semaine de 4 jours, elles s'opposent sur sa faisabilité selon la taille de l'entreprise.", acceptedAnswers: [], explanation: "L'accord partagé est nommé avant le désaccord précis sur la faisabilité.", targetLanguageFeature: "comparaison organisée accord / désaccord", tags: ["comparison", "recognize", "variant"] },
    ],
    [
      { subSkill: "agreement-verb", prompt: "Vous comparez deux sources de façon organisée.", instructions: "Complétez : « Si les deux sources ______ sur la souplesse des cours en ligne, elles divergent sur leurs conséquences sociales. »", options: [], correctAnswer: "s'accordent", acceptedAnswers: ["convergent"], explanation: "Ce verbe nomme explicitement l'accord partagé avant d'introduire le désaccord.", targetLanguageFeature: "verbe d'accord partagé", tags: ["comparison", "complete"] },
      { subSkill: "agreement-verb-alternative", prompt: "Vous comparez deux sources de façon organisée.", instructions: "Complétez : « Si les deux sources ______ sur le bien-être des salariés, elles divergent sur la faisabilité de la mesure. »", options: [], correctAnswer: "s'accordent", acceptedAnswers: ["convergent"], explanation: "Le même verbe nomme ici l'accord partagé.", targetLanguageFeature: "verbe d'accord partagé", tags: ["comparison", "complete", "variant"] },
    ],
    [
      { subSkill: "relate-juxtaposed-viewpoints", prompt: "Réorganisez cette comparaison qui juxtapose sans relier : « Une source parle de souplesse. L'autre parle d'isolement. »", instructions: "Réécrivez en reliant explicitement l'accord et le désaccord entre les deux sources.", options: [], correctAnswer: null, acceptedAnswers: ["Si les deux sources s'accordent sur la souplesse offerte par les cours en ligne, elles s'opposent sur le risque d'isolement qu'ils représentent pour les étudiants.", "Les deux sources reconnaissent un même avantage, la flexibilité, mais elles ne s'entendent pas sur les conséquences sociales de cette flexibilité."], explanation: "La réécriture relie les deux sources par une structure de concession/opposition plutôt que de les juxtaposer.", targetLanguageFeature: "mise en relation accord / désaccord", tags: ["comparison", "transform"] },
      { subSkill: "relate-juxtaposed-viewpoints-alternative", prompt: "Réorganisez cette comparaison qui juxtapose sans relier : « Une source parle de bien-être. L'autre parle de faisabilité limitée. »", instructions: "Réécrivez en reliant explicitement l'accord et le désaccord entre les deux sources.", options: [], correctAnswer: null, acceptedAnswers: ["Si les deux sources s'accordent sur le bien-être qu'apporte la semaine de 4 jours, elles s'opposent sur sa faisabilité, jugée limitée aux grandes structures par la seconde.", "Les deux sources reconnaissent un même bénéfice pour les salariés, mais elles ne s'entendent pas sur la possibilité de généraliser la mesure."], explanation: "La réécriture relie les deux sources par une structure de concession/opposition.", targetLanguageFeature: "mise en relation accord / désaccord", tags: ["comparison", "transform", "variant"] },
    ],
    [
      { subSkill: "comparison-order", prompt: "Vous comparez deux sources sur la réforme des retraites de façon organisée.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Les deux sources reconnaissent la nécessité de réformer le système actuel.", "Elles s'opposent en revanche sur le rôle que devrait jouer l'État dans la garantie d'un minimum de pension.", "Ce désaccord touche donc moins le principe de la réforme que ses modalités."], correctAnswer: ["Les deux sources reconnaissent la nécessité de réformer le système actuel.", "Elles s'opposent en revanche sur le rôle que devrait jouer l'État dans la garantie d'un minimum de pension.", "Ce désaccord touche donc moins le principe de la réforme que ses modalités."], acceptedAnswers: [], explanation: "L'accord partagé est nommé avant le désaccord précis, puis vient une mise en perspective du désaccord.", targetLanguageFeature: "organisation d'une comparaison", tags: ["comparison", "organization"] },
      { subSkill: "comparison-order-alternative", prompt: "Vous comparez deux sources sur l'encadrement des loyers de façon organisée.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Les deux sources reconnaissent la difficulté d'accès au logement dans les grandes villes.", "Elles s'opposent en revanche sur l'efficacité de l'encadrement des loyers pour résoudre ce problème.", "Ce désaccord touche donc moins le constat initial que la solution à privilégier."], correctAnswer: ["Les deux sources reconnaissent la difficulté d'accès au logement dans les grandes villes.", "Elles s'opposent en revanche sur l'efficacité de l'encadrement des loyers pour résoudre ce problème.", "Ce désaccord touche donc moins le constat initial que la solution à privilégier."], acceptedAnswers: [], explanation: "Même organisation : accord, puis désaccord, puis mise en perspective.", targetLanguageFeature: "organisation d'une comparaison", tags: ["comparison", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-agreement-disagreement", prompt: "Idée de départ : deux sources sur l'IA générative dans l'enseignement s'accordent sur le gain de temps qu'elle offre pour préparer des cours, mais divergent sur le risque de dépendance des enseignants.", instructions: "Rédigez 2 à 3 phrases qui organisent clairement cet accord partagé et ce désaccord.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La comparaison doit nommer l'accord avant d'introduire le désaccord précis.", targetLanguageFeature: "comparaison organisée", tags: ["comparison", "development"], selfCheck: ["L'accord partagé entre les deux sources est nommé.", "Le désaccord précis est distinct de l'accord.", "La comparaison reste organisée, pas juxtaposée."] },
      { subSkill: "guided-agreement-disagreement-alternative", prompt: "Idée de départ : deux sources sur la généralisation des visioconférences professionnelles s'accordent sur le gain de temps, mais divergent sur la qualité des échanges.", instructions: "Rédigez 2 à 3 phrases qui organisent clairement cet accord partagé et ce désaccord.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La comparaison doit nommer l'accord avant d'introduire le désaccord précis.", targetLanguageFeature: "comparaison organisée", tags: ["comparison", "development", "variant"], selfCheck: ["L'accord partagé entre les deux sources est nommé.", "Le désaccord précis est distinct de l'accord.", "La comparaison reste organisée, pas juxtaposée."] },
    ],
    [
      { subSkill: "independent-agreement-disagreement", prompt: "Vous comparez deux sources sur la généralisation du compostage obligatoire en ville, qui s'accordent sur le bénéfice environnemental mais divergent sur la charge logistique pour les habitants.", instructions: "Rédigez 2 à 3 phrases qui organisent clairement cet accord et ce désaccord.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une comparaison C1 réussie organise l'accord partagé et le désaccord précis, sans les juxtaposer.", targetLanguageFeature: "comparaison organisée, autonome", tags: ["comparison", "production"], selfCheck: ["L'accord partagé est nommé.", "Le désaccord précis est distinct.", "La comparaison reste organisée."] },
      { subSkill: "independent-agreement-disagreement-alternative", prompt: "Vous comparez deux sources sur la suppression des billets papier dans les transports, qui s'accordent sur la simplicité pour la majorité mais divergent sur l'exclusion des personnes âgées peu connectées.", instructions: "Rédigez 2 à 3 phrases qui organisent clairement cet accord et ce désaccord.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une comparaison C1 réussie organise l'accord partagé et le désaccord précis.", targetLanguageFeature: "comparaison organisée, autonome", tags: ["comparison", "production", "variant"], selfCheck: ["L'accord partagé est nommé.", "Le désaccord précis est distinct.", "La comparaison reste organisée."] },
    ],
  ]),

  ...taskThreeC1Path("t3-c1-synthesizing", "synthesizing", [
    [
      { subSkill: "link-synthesis-to-position", prompt: "Après avoir analysé deux sources sur le télétravail obligatoire, vous rédigez une synthèse qui doit annoncer votre position à venir.", instructions: "Choisissez la phrase qui relie le mieux la synthèse des sources à une position personnelle qui va suivre.", options: ["Voilà donc ce que disent les deux sources sur le télétravail.", "De cette confrontation entre gains d'efficacité et risques pour la cohésion, il me semble qu'une position équilibrée reste possible.", "Le télétravail a des avantages et des inconvénients.", "Les sources ne sont pas d'accord."], correctAnswer: "De cette confrontation entre gains d'efficacité et risques pour la cohésion, il me semble qu'une position équilibrée reste possible.", acceptedAnswers: [], explanation: "Cette phrase relie explicitement la synthèse à la position qui va être développée, au lieu de simplement clore l'analyse.", targetLanguageFeature: "synthèse reliée à une position", tags: ["synthesis", "recognize"] },
      { subSkill: "link-synthesis-to-position-alternative", prompt: "Après avoir analysé deux sources sur l'encadrement des influenceurs sur les réseaux sociaux, vous rédigez une synthèse qui doit annoncer votre position à venir.", instructions: "Choisissez la phrase qui relie le mieux la synthèse des sources à une position personnelle qui va suivre.", options: ["Voilà donc ce que disent les deux sources sur les influenceurs.", "De cette tension entre liberté d'expression et protection des publics vulnérables, il me semble qu'un encadrement ciblé reste préférable.", "Les influenceurs ont des avantages et des inconvénients.", "Les sources ne sont pas d'accord."], correctAnswer: "De cette tension entre liberté d'expression et protection des publics vulnérables, il me semble qu'un encadrement ciblé reste préférable.", acceptedAnswers: [], explanation: "La phrase relie la synthèse à une position à venir, sans se contenter de clore l'analyse.", targetLanguageFeature: "synthèse reliée à une position", tags: ["synthesis", "recognize", "variant"] },
    ],
    [
      { subSkill: "synthesis-bridge-verb", prompt: "Vous reliez votre synthèse à votre position à venir.", instructions: "Complétez : « Cette synthèse ______ à penser qu'une solution intermédiaire mérite d'être envisagée. »", options: [], correctAnswer: "m'amène", acceptedAnswers: ["me conduit", "m'invite"], explanation: "Ce verbe relie explicitement la synthèse des sources à une réflexion personnelle qui en découle.", targetLanguageFeature: "verbe de transition synthèse → position", tags: ["synthesis", "complete"] },
      { subSkill: "synthesis-bridge-verb-alternative", prompt: "Vous reliez votre synthèse à votre position à venir.", instructions: "Complétez : « Cette synthèse ______ à penser qu'un encadrement ciblé serait préférable à une interdiction totale. »", options: [], correctAnswer: "m'amène", acceptedAnswers: ["me conduit", "m'invite"], explanation: "Le même verbe relie ici la synthèse à la position à venir.", targetLanguageFeature: "verbe de transition synthèse → position", tags: ["synthesis", "complete", "variant"] },
    ],
    [
      { subSkill: "connect-disconnected-synthesis", prompt: "Reliez cette synthèse déconnectée de la position qui suit : « Les deux sources ont chacune leurs arguments. Passons à mon avis. »", instructions: "Réécrivez pour que la synthèse annonce naturellement la position qui va suivre.", options: [], correctAnswer: null, acceptedAnswers: ["Cette confrontation entre les deux sources m'amène à penser qu'une solution mesurée, plutôt qu'une adoption totale ou un refus, serait la plus raisonnable.", "Face à ces deux logiques opposées, il me semble qu'une voie intermédiaire mérite d'être défendue."], explanation: "La réécriture fait de la synthèse le point de départ logique de la position, plutôt qu'une simple transition artificielle.", targetLanguageFeature: "synthèse reliée organiquement à la position", tags: ["synthesis", "transform"] },
      { subSkill: "connect-disconnected-synthesis-alternative", prompt: "Reliez cette synthèse déconnectée de la position qui suit : « Les deux sources ont chacune leurs arguments sur les influenceurs. Passons à mon avis. »", instructions: "Réécrivez pour que la synthèse annonce naturellement la position qui va suivre.", options: [], correctAnswer: null, acceptedAnswers: ["Cette confrontation entre liberté d'expression et protection des publics m'amène à penser qu'un encadrement ciblé serait la voie la plus raisonnable.", "Face à ces deux logiques opposées, il me semble qu'un encadrement mesuré mérite d'être défendu."], explanation: "La synthèse devient le point de départ logique de la position.", targetLanguageFeature: "synthèse reliée organiquement à la position", tags: ["synthesis", "transform", "variant"] },
    ],
    [
      { subSkill: "synthesis-to-position-order", prompt: "Vous rédigez une synthèse reliée à votre position sur la suppression des notes chiffrées à l'école.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Les deux sources s'accordent sur la nécessité de repenser l'évaluation, mais divergent sur les moyens.", "Cette tension non résolue par les documents appelle une prise de position personnelle.", "C'est précisément ce que je me propose de faire à présent."], correctAnswer: ["Les deux sources s'accordent sur la nécessité de repenser l'évaluation, mais divergent sur les moyens.", "Cette tension non résolue par les documents appelle une prise de position personnelle.", "C'est précisément ce que je me propose de faire à présent."], acceptedAnswers: [], explanation: "La synthèse expose la tension, puis annonce explicitement la position qui va suivre.", targetLanguageFeature: "organisation synthèse → annonce de position", tags: ["synthesis", "organization"] },
      { subSkill: "synthesis-to-position-order-alternative", prompt: "Vous rédigez une synthèse reliée à votre position sur l'instauration d'un revenu de base pour les étudiants.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Les deux sources s'accordent sur la précarité étudiante, mais divergent sur la solution à privilégier.", "Cette tension non résolue par les documents appelle une prise de position personnelle.", "C'est précisément ce que je me propose de faire à présent."], correctAnswer: ["Les deux sources s'accordent sur la précarité étudiante, mais divergent sur la solution à privilégier.", "Cette tension non résolue par les documents appelle une prise de position personnelle.", "C'est précisément ce que je me propose de faire à présent."], acceptedAnswers: [], explanation: "Même organisation : synthèse, puis annonce de la position.", targetLanguageFeature: "organisation synthèse → annonce de position", tags: ["synthesis", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-synthesis-to-position", prompt: "Idée de départ : vous synthétisez deux sources sur la suppression des notes chiffrées à l'école, avant d'annoncer votre position.", instructions: "Rédigez 2 à 3 phrases qui font de la synthèse le point de départ logique de votre position à venir.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La synthèse doit préparer explicitement la position, sans rupture artificielle.", targetLanguageFeature: "synthèse reliée à une position", tags: ["synthesis", "development"], selfCheck: ["La synthèse résume fidèlement la tension entre les sources.", "Le lien vers la position à venir est explicite.", "Il n'y a pas de rupture artificielle entre synthèse et position."] },
      { subSkill: "guided-synthesis-to-position-alternative", prompt: "Idée de départ : vous synthétisez deux sources sur l'instauration d'un revenu de base pour les étudiants, avant d'annoncer votre position.", instructions: "Rédigez 2 à 3 phrases qui font de la synthèse le point de départ logique de votre position à venir.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La synthèse doit préparer explicitement la position, sans rupture artificielle.", targetLanguageFeature: "synthèse reliée à une position", tags: ["synthesis", "development", "variant"], selfCheck: ["La synthèse résume fidèlement la tension entre les sources.", "Le lien vers la position à venir est explicite.", "Il n'y a pas de rupture artificielle entre synthèse et position."] },
    ],
    [
      { subSkill: "independent-synthesis-to-position", prompt: "Vous synthétisez deux sources sur l'encadrement de la publicité ciblant les enfants, avant d'annoncer votre position.", instructions: "Rédigez 2 à 3 phrases qui font de la synthèse le point de départ logique de votre position.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une synthèse C1 réussie prépare la position sans rupture artificielle.", targetLanguageFeature: "synthèse reliée à une position, autonome", tags: ["synthesis", "production"], selfCheck: ["La synthèse résume fidèlement la tension entre les sources.", "Le lien vers la position est explicite.", "Il n'y a pas de rupture artificielle."] },
      { subSkill: "independent-synthesis-to-position-alternative", prompt: "Vous synthétisez deux sources sur la généralisation du vote électronique, avant d'annoncer votre position.", instructions: "Rédigez 2 à 3 phrases qui font de la synthèse le point de départ logique de votre position.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une synthèse C1 réussie prépare la position sans rupture artificielle.", targetLanguageFeature: "synthèse reliée à une position, autonome", tags: ["synthesis", "production", "variant"], selfCheck: ["La synthèse résume fidèlement la tension entre les sources.", "Le lien vers la position est explicite.", "Il n'y a pas de rupture artificielle."] },
    ],
  ]),

  ...taskThreeC1Path("t3-c1-taking-position", "taking-position", [
    [
      { subSkill: "position-acknowledging-other-view", prompt: "Vous prenez position sur le télétravail obligatoire après avoir reconnu les préoccupations de la seconde source.", instructions: "Choisissez la phrase qui prend position tout en reconnaissant l'autre perspective.", options: ["Le télétravail obligatoire est une bonne idée.", "Même si le risque de perte de cohésion est réel, je pense qu'un jour de télétravail bien organisé reste bénéfique.", "Certains sont pour, d'autres sont contre.", "Je ne sais pas quoi penser du télétravail."], correctAnswer: "Même si le risque de perte de cohésion est réel, je pense qu'un jour de télétravail bien organisé reste bénéfique.", acceptedAnswers: [], explanation: "La position est affirmée après une concession explicite à l'autre perspective, ce qui la rend plus crédible qu'une affirmation isolée.", targetLanguageFeature: "position avec reconnaissance concessive", tags: ["position", "recognize"] },
      { subSkill: "position-acknowledging-other-view-alternative", prompt: "Vous prenez position sur l'encadrement des influenceurs après avoir reconnu les préoccupations liées à la liberté d'expression.", instructions: "Choisissez la phrase qui prend position tout en reconnaissant l'autre perspective.", options: ["L'encadrement des influenceurs est nécessaire.", "Même si la liberté d'expression mérite d'être protégée, je pense qu'un encadrement ciblé reste justifié pour les publics vulnérables.", "Certains sont pour, d'autres sont contre.", "Je ne sais pas quoi penser des influenceurs."], correctAnswer: "Même si la liberté d'expression mérite d'être protégée, je pense qu'un encadrement ciblé reste justifié pour les publics vulnérables.", acceptedAnswers: [], explanation: "La position est affirmée après une concession explicite à l'autre perspective.", targetLanguageFeature: "position avec reconnaissance concessive", tags: ["position", "recognize", "variant"] },
    ],
    [
      { subSkill: "concessive-connector", prompt: "Vous prenez position après avoir reconnu une autre perspective.", instructions: "Complétez : « ______ le risque de perte de cohésion soit réel, je pense qu'un jour de télétravail bien organisé reste bénéfique. »", options: [], correctAnswer: "Bien que", acceptedAnswers: ["Même si"], explanation: "Ce connecteur introduit la concession avant l'affirmation de la position.", targetLanguageFeature: "connecteur concessif", tags: ["position", "complete"] },
      { subSkill: "concessive-connector-alternative", prompt: "Vous prenez position après avoir reconnu une autre perspective.", instructions: "Complétez : « ______ la liberté d'expression mérite d'être protégée, je pense qu'un encadrement ciblé reste justifié. »", options: [], correctAnswer: "Bien que", acceptedAnswers: ["Même si"], explanation: "Le même connecteur introduit ici la concession.", targetLanguageFeature: "connecteur concessif", tags: ["position", "complete", "variant"] },
    ],
    [
      { subSkill: "add-concession-to-position", prompt: "Transformez cette position isolée en une position qui reconnaît d'abord l'autre perspective : « Le télétravail obligatoire est une bonne mesure. »", instructions: "Réécrivez en ajoutant une reconnaissance explicite du point de vue opposé.", options: [], correctAnswer: null, acceptedAnswers: ["Même si la cohésion d'équipe peut en pâtir, je pense que le télétravail obligatoire reste une mesure bénéfique si elle est bien encadrée.", "S'il est vrai que certains risquent de s'isoler, je considère néanmoins que le télétravail obligatoire apporte un bénéfice net."], explanation: "La position devient plus nuancée et plus crédible en reconnaissant d'abord l'objection principale.", targetLanguageFeature: "ajout d'une concession à une position", tags: ["position", "transform"] },
      { subSkill: "add-concession-to-position-alternative", prompt: "Transformez cette position isolée : « L'encadrement des influenceurs est nécessaire. »", instructions: "Réécrivez en ajoutant une reconnaissance explicite du point de vue opposé.", options: [], correctAnswer: null, acceptedAnswers: ["Même si la liberté d'expression doit être préservée, je pense qu'un encadrement ciblé reste nécessaire pour protéger les publics vulnérables.", "S'il est vrai qu'un encadrement trop large menacerait la liberté d'expression, je considère néanmoins qu'un encadrement ciblé reste justifié."], explanation: "La position devient plus nuancée en reconnaissant d'abord l'objection principale.", targetLanguageFeature: "ajout d'une concession à une position", tags: ["position", "transform", "variant"] },
    ],
    [
      { subSkill: "concessive-position-order", prompt: "Vous prenez position sur la réforme des retraites en reconnaissant l'autre perspective.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Certes, une réforme trop rapide pourrait fragiliser les personnes proches de la retraite.", "Il me semble néanmoins qu'une évolution du système reste nécessaire.", "à condition d'être accompagnée de mesures de transition pour les plus vulnérables."], correctAnswer: ["Certes, une réforme trop rapide pourrait fragiliser les personnes proches de la retraite.", "Il me semble néanmoins qu'une évolution du système reste nécessaire.", "à condition d'être accompagnée de mesures de transition pour les plus vulnérables."], acceptedAnswers: [], explanation: "La concession vient en premier, suivie de la position, puis d'une condition qui la précise.", targetLanguageFeature: "organisation concession → position → condition", tags: ["position", "organization"] },
      { subSkill: "concessive-position-order-alternative", prompt: "Vous prenez position sur la généralisation du vote électronique en reconnaissant l'autre perspective.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Certes, les risques de piratage ne peuvent être totalement écartés.", "Il me semble néanmoins que le vote électronique reste une évolution souhaitable.", "à condition d'être accompagné de garanties techniques solides."], correctAnswer: ["Certes, les risques de piratage ne peuvent être totalement écartés.", "Il me semble néanmoins que le vote électronique reste une évolution souhaitable.", "à condition d'être accompagné de garanties techniques solides."], acceptedAnswers: [], explanation: "Même organisation : concession, puis position, puis condition.", targetLanguageFeature: "organisation concession → position → condition", tags: ["position", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-concessive-position", prompt: "Idée de départ : vous prenez position sur la suppression des notes chiffrées à l'école, après avoir reconnu que cette suppression pourrait rendre le suivi des progrès moins lisible pour les familles.", instructions: "Rédigez 2 à 3 phrases qui prennent position tout en reconnaissant explicitement cette autre perspective.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La position doit être affirmée après une reconnaissance explicite du point de vue opposé.", targetLanguageFeature: "position avec reconnaissance concessive", tags: ["position", "development"], selfCheck: ["L'autre perspective est reconnue explicitement.", "La position personnelle reste claire malgré la concession.", "La concession ne dilue pas la position."] },
      { subSkill: "guided-concessive-position-alternative", prompt: "Idée de départ : vous prenez position sur l'instauration d'un revenu de base pour les étudiants, après avoir reconnu que cette mesure représenterait un coût important pour les finances publiques.", instructions: "Rédigez 2 à 3 phrases qui prennent position tout en reconnaissant explicitement cette autre perspective.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La position doit être affirmée après une reconnaissance explicite du point de vue opposé.", targetLanguageFeature: "position avec reconnaissance concessive", tags: ["position", "development", "variant"], selfCheck: ["L'autre perspective est reconnue explicitement.", "La position personnelle reste claire malgré la concession.", "La concession ne dilue pas la position."] },
    ],
    [
      { subSkill: "independent-concessive-position", prompt: "Vous prenez position sur l'encadrement de la publicité ciblant les enfants, en reconnaissant les préoccupations économiques des annonceurs.", instructions: "Rédigez 2 à 3 phrases qui prennent position tout en reconnaissant explicitement cette autre perspective.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une position C1 réussie reconnaît explicitement l'autre perspective sans se diluer.", targetLanguageFeature: "position avec reconnaissance concessive, autonome", tags: ["position", "production"], selfCheck: ["L'autre perspective est reconnue explicitement.", "La position personnelle reste claire.", "La concession ne dilue pas la position."] },
      { subSkill: "independent-concessive-position-alternative", prompt: "Vous prenez position sur la généralisation du compostage obligatoire en ville, en reconnaissant la charge logistique qu'il représente pour certains habitants.", instructions: "Rédigez 2 à 3 phrases qui prennent position tout en reconnaissant explicitement cette autre perspective.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une position C1 réussie reconnaît explicitement l'autre perspective sans se diluer.", targetLanguageFeature: "position avec reconnaissance concessive, autonome", tags: ["position", "production", "variant"], selfCheck: ["L'autre perspective est reconnue explicitement.", "La position personnelle reste claire.", "La concession ne dilue pas la position."] },
    ],
  ]),

  ...taskThreeC1Path("t3-c1-responding-counterarguments", "responding-counterarguments", [
    [
      { subSkill: "distinguish-valid-limited", prompt: "Une objection affirme : « Le télétravail obligatoire isole les salariés. »", instructions: "Choisissez la réponse qui distingue le mieux ce qui est valable et ce qui est limité dans cette objection.", options: ["Cette objection est fausse, le télétravail n'isole personne.", "Cette objection est fondée pour les équipes peu autonomes, mais elle néglige les outils de communication qui limitent aujourd'hui ce risque.", "Cette objection a raison sur toute la ligne.", "Le télétravail a des avantages et des inconvénients."], correctAnswer: "Cette objection est fondée pour les équipes peu autonomes, mais elle néglige les outils de communication qui limitent aujourd'hui ce risque.", acceptedAnswers: [], explanation: "La réponse reconnaît une part de vérité dans l'objection tout en précisant sa limite, plutôt que de la rejeter ou de l'accepter en bloc.", targetLanguageFeature: "réponse distinguant valable et limité", tags: ["counterargument", "recognize"] },
      { subSkill: "distinguish-valid-limited-alternative", prompt: "Une objection affirme : « L'encadrement des influenceurs limite la liberté d'expression. »", instructions: "Choisissez la réponse qui distingue le mieux ce qui est valable et ce qui est limité dans cette objection.", options: ["Cette objection est fausse, il n'y a aucun risque pour la liberté d'expression.", "Cette objection est fondée si l'encadrement devient trop large, mais elle néglige qu'un encadrement ciblé protège justement certains publics sans museler les autres.", "Cette objection a raison sur toute la ligne.", "L'encadrement a des avantages et des inconvénients."], correctAnswer: "Cette objection est fondée si l'encadrement devient trop large, mais elle néglige qu'un encadrement ciblé protège justement certains publics sans museler les autres.", acceptedAnswers: [], explanation: "La réponse reconnaît une part de vérité tout en précisant sa limite.", targetLanguageFeature: "réponse distinguant valable et limité", tags: ["counterargument", "recognize", "variant"] },
    ],
    [
      { subSkill: "concession-limit-connector", prompt: "Vous répondez à une objection en distinguant ce qui est valable et ce qui est limité.", instructions: "Complétez : « Cette objection est fondée dans certains cas, ______ elle ne tient pas compte des outils qui limitent aujourd'hui ce risque. »", options: [], correctAnswer: "mais", acceptedAnswers: ["toutefois"], explanation: "Ce connecteur introduit la limite après avoir reconnu la validité partielle de l'objection.", targetLanguageFeature: "connecteur de limite après concession", tags: ["counterargument", "complete"] },
      { subSkill: "concession-limit-connector-alternative", prompt: "Vous répondez à une objection en distinguant ce qui est valable et ce qui est limité.", instructions: "Complétez : « Cette objection est fondée dans certains cas, ______ elle néglige la protection qu'apporte un encadrement ciblé. »", options: [], correctAnswer: "mais", acceptedAnswers: ["toutefois"], explanation: "Le même connecteur introduit ici la limite.", targetLanguageFeature: "connecteur de limite après concession", tags: ["counterargument", "complete", "variant"] },
    ],
    [
      { subSkill: "avoid-caricature-response", prompt: "Réécrivez cette réponse qui caricature l'objection au lieu de la nuancer : « De toute façon, cette objection sur l'isolement ne tient pas debout. »", instructions: "Réécrivez en distinguant ce qui est valable et ce qui est limité dans l'objection.", options: [], correctAnswer: null, acceptedAnswers: ["Cette objection est fondée pour les équipes qui manquent d'autonomie, mais elle sous-estime les outils de communication qui réduisent aujourd'hui ce risque.", "S'il est vrai qu'un isolement reste possible sans accompagnement, cette objection néglige les dispositifs qui permettent aujourd'hui de le prévenir."], explanation: "La réponse nuancée évite de rejeter l'objection en bloc et précise sa portée réelle.", targetLanguageFeature: "réponse nuancée sans caricature", tags: ["counterargument", "transform"] },
      { subSkill: "avoid-caricature-response-alternative", prompt: "Réécrivez cette réponse qui caricature l'objection : « De toute façon, cette objection sur la liberté d'expression ne tient pas debout. »", instructions: "Réécrivez en distinguant ce qui est valable et ce qui est limité dans l'objection.", options: [], correctAnswer: null, acceptedAnswers: ["Cette objection est fondée si l'encadrement devient excessif, mais elle sous-estime la protection qu'apporte un encadrement ciblé.", "S'il est vrai qu'un encadrement mal conçu menacerait la liberté d'expression, cette objection néglige qu'un encadrement ciblé peut l'éviter."], explanation: "La réponse nuancée évite de rejeter l'objection en bloc.", targetLanguageFeature: "réponse nuancée sans caricature", tags: ["counterargument", "transform", "variant"] },
    ],
    [
      { subSkill: "nuanced-response-order", prompt: "Vous répondez à une objection sur la réforme des retraites en distinguant ce qui est valable et ce qui est limité.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Cette objection a raison de souligner le risque pour les personnes proches de la retraite.", "Elle néglige néanmoins les mesures de transition qui peuvent atténuer ce risque.", "La réforme reste donc défendable si elle s'accompagne de ces garanties."], correctAnswer: ["Cette objection a raison de souligner le risque pour les personnes proches de la retraite.", "Elle néglige néanmoins les mesures de transition qui peuvent atténuer ce risque.", "La réforme reste donc défendable si elle s'accompagne de ces garanties."], acceptedAnswers: [], explanation: "La part valable de l'objection est reconnue avant sa limite, puis vient la conclusion qui en découle.", targetLanguageFeature: "organisation valable → limité → conclusion", tags: ["counterargument", "organization"] },
      { subSkill: "nuanced-response-order-alternative", prompt: "Vous répondez à une objection sur le vote électronique en distinguant ce qui est valable et ce qui est limité.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Cette objection a raison de souligner les risques de piratage.", "Elle néglige néanmoins les garanties techniques qui peuvent réduire ce risque.", "Le vote électronique reste donc défendable si ces garanties sont assurées."], correctAnswer: ["Cette objection a raison de souligner les risques de piratage.", "Elle néglige néanmoins les garanties techniques qui peuvent réduire ce risque.", "Le vote électronique reste donc défendable si ces garanties sont assurées."], acceptedAnswers: [], explanation: "Même organisation : valable, puis limité, puis conclusion.", targetLanguageFeature: "organisation valable → limité → conclusion", tags: ["counterargument", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-nuanced-response", prompt: "Idée de départ : une objection affirme que la suppression des notes chiffrées rendrait le suivi des progrès illisible pour les familles.", instructions: "Rédigez 2 à 3 phrases qui distinguent ce qui est valable dans cette objection de ce qui en limite la portée.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La réponse doit reconnaître une part de vérité avant d'en préciser la limite.", targetLanguageFeature: "réponse distinguant valable et limité", tags: ["counterargument", "development"], selfCheck: ["La part valable de l'objection est reconnue.", "La limite de l'objection est expliquée, pas juste affirmée.", "L'objection n'est ni rejetée en bloc ni acceptée en bloc."] },
      { subSkill: "guided-nuanced-response-alternative", prompt: "Idée de départ : une objection affirme que le revenu de base pour les étudiants représenterait un coût trop important pour les finances publiques.", instructions: "Rédigez 2 à 3 phrases qui distinguent ce qui est valable dans cette objection de ce qui en limite la portée.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La réponse doit reconnaître une part de vérité avant d'en préciser la limite.", targetLanguageFeature: "réponse distinguant valable et limité", tags: ["counterargument", "development", "variant"], selfCheck: ["La part valable de l'objection est reconnue.", "La limite de l'objection est expliquée, pas juste affirmée.", "L'objection n'est ni rejetée en bloc ni acceptée en bloc."] },
    ],
    [
      { subSkill: "independent-nuanced-response", prompt: "Vous répondez à une objection affirmant que l'encadrement de la publicité ciblant les enfants nuirait au modèle économique de nombreux médias.", instructions: "Rédigez 2 à 3 phrases qui distinguent ce qui est valable dans cette objection de ce qui en limite la portée.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une réponse C1 réussie distingue nettement ce qui est valable de ce qui est limité.", targetLanguageFeature: "réponse distinguant valable et limité, autonome", tags: ["counterargument", "production"], selfCheck: ["La part valable de l'objection est reconnue.", "La limite est expliquée, pas juste affirmée.", "L'objection n'est ni rejetée ni acceptée en bloc."] },
      { subSkill: "independent-nuanced-response-alternative", prompt: "Vous répondez à une objection affirmant que le compostage obligatoire représenterait une charge excessive pour les habitants les plus âgés.", instructions: "Rédigez 2 à 3 phrases qui distinguent ce qui est valable dans cette objection de ce qui en limite la portée.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une réponse C1 réussie distingue nettement ce qui est valable de ce qui est limité.", targetLanguageFeature: "réponse distinguant valable et limité, autonome", tags: ["counterargument", "production", "variant"], selfCheck: ["La part valable de l'objection est reconnue.", "La limite est expliquée, pas juste affirmée.", "L'objection n'est ni rejetée ni acceptée en bloc."] },
    ],
  ]),

  ...taskThreeC1Path("t3-c1-nuancing-position", "nuancing-position", [
    [
      { subSkill: "context-dependent-nuance", prompt: "Vous nuancez votre position favorable au télétravail obligatoire selon le contexte.", instructions: "Choisissez la phrase qui nuance le mieux selon des contextes différents.", options: ["Le télétravail obligatoire est une bonne chose.", "Cette mesure profite surtout aux équipes déjà autonomes, alors qu'elle risque de fragiliser les collaborateurs récemment arrivés.", "Le télétravail a des avantages et des inconvénients.", "Tout dépend des gens."], correctAnswer: "Cette mesure profite surtout aux équipes déjà autonomes, alors qu'elle risque de fragiliser les collaborateurs récemment arrivés.", acceptedAnswers: [], explanation: "La nuance identifie deux contextes précis et leurs conséquences différentes, plutôt qu'une réserve vague.", targetLanguageFeature: "nuance contextualisée", tags: ["nuance", "recognize"] },
      { subSkill: "context-dependent-nuance-alternative", prompt: "Vous nuancez votre position favorable à l'encadrement des influenceurs selon le contexte.", instructions: "Choisissez la phrase qui nuance le mieux selon des contextes différents.", options: ["L'encadrement des influenceurs est une bonne chose.", "Cet encadrement se justifie pleinement pour les publics les plus jeunes, alors qu'il devient plus discutable pour un public averti et consentant.", "L'encadrement a des avantages et des inconvénients.", "Tout dépend des gens."], correctAnswer: "Cet encadrement se justifie pleinement pour les publics les plus jeunes, alors qu'il devient plus discutable pour un public averti et consentant.", acceptedAnswers: [], explanation: "La nuance distingue deux contextes précis, pas une réserve vague.", targetLanguageFeature: "nuance contextualisée", tags: ["nuance", "recognize", "variant"] },
    ],
    [
      { subSkill: "context-connector", prompt: "Vous nuancez votre position selon le contexte.", instructions: "Complétez : « Cette mesure profite aux équipes autonomes, ______ elle risque de fragiliser les nouveaux arrivants. »", options: [], correctAnswer: "alors que", acceptedAnswers: ["tandis que"], explanation: "Ce connecteur met en regard deux contextes aux conséquences opposées.", targetLanguageFeature: "connecteur de contraste contextuel", tags: ["nuance", "complete"] },
      { subSkill: "context-connector-alternative", prompt: "Vous nuancez votre position selon le contexte.", instructions: "Complétez : « Cet encadrement se justifie pour les jeunes publics, ______ il devient plus discutable pour un public averti. »", options: [], correctAnswer: "alors que", acceptedAnswers: ["tandis que"], explanation: "Le même connecteur met ici en regard deux contextes différents.", targetLanguageFeature: "connecteur de contraste contextuel", tags: ["nuance", "complete", "variant"] },
    ],
    [
      { subSkill: "add-context-to-vague-nuance", prompt: "Précisez cette nuance trop vague par des contextes concrets : « Ça dépend des cas. »", instructions: "Réécrivez en donnant deux contextes précis et leurs conséquences différentes, à propos du télétravail obligatoire.", options: [], correctAnswer: null, acceptedAnswers: ["Cette mesure convient bien aux équipes déjà rodées au travail à distance, mais elle peut fragiliser l'intégration des nouveaux employés.", "Selon que l'équipe dispose ou non d'une culture du travail à distance établie, les effets de cette mesure varient sensiblement."], explanation: "La nuance devient utile lorsqu'elle précise les contextes et leurs conséquences, plutôt que de rester une réserve générale.", targetLanguageFeature: "nuance précisée par des contextes", tags: ["nuance", "transform"] },
      { subSkill: "add-context-to-vague-nuance-alternative", prompt: "Précisez cette nuance trop vague par des contextes concrets : « Ça dépend des cas. »", instructions: "Réécrivez en donnant deux contextes précis et leurs conséquences différentes, à propos de l'encadrement des influenceurs.", options: [], correctAnswer: null, acceptedAnswers: ["Cet encadrement se justifie pleinement face à un jeune public, mais il devient plus contestable face à un public adulte et averti.", "Selon l'âge et la vulnérabilité du public visé, la légitimité de cet encadrement varie sensiblement."], explanation: "La nuance devient utile lorsqu'elle précise les contextes.", targetLanguageFeature: "nuance précisée par des contextes", tags: ["nuance", "transform", "variant"] },
    ],
    [
      { subSkill: "nuance-order", prompt: "Vous nuancez votre position sur la réforme des retraites selon le contexte.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Ma position favorable à la réforme ne vaut pas de façon uniforme.", "Elle profite aux nouvelles générations, mais elle fragilise ceux qui sont proches du départ à la retraite.", "C'est cette différence de contexte qui justifie des mesures de transition ciblées."], correctAnswer: ["Ma position favorable à la réforme ne vaut pas de façon uniforme.", "Elle profite aux nouvelles générations, mais elle fragilise ceux qui sont proches du départ à la retraite.", "C'est cette différence de contexte qui justifie des mesures de transition ciblées."], acceptedAnswers: [], explanation: "La nuance annonce d'abord la variation, puis la précise par contexte, puis en tire une conséquence pratique.", targetLanguageFeature: "organisation d'une nuance contextualisée", tags: ["nuance", "organization"] },
      { subSkill: "nuance-order-alternative", prompt: "Vous nuancez votre position sur le vote électronique selon le contexte.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Ma position favorable au vote électronique ne vaut pas de façon uniforme.", "Elle se justifie pour les scrutins à faible enjeu, mais elle reste plus risquée pour les élections majeures.", "C'est cette différence de contexte qui justifie une généralisation progressive."], correctAnswer: ["Ma position favorable au vote électronique ne vaut pas de façon uniforme.", "Elle se justifie pour les scrutins à faible enjeu, mais elle reste plus risquée pour les élections majeures.", "C'est cette différence de contexte qui justifie une généralisation progressive."], acceptedAnswers: [], explanation: "Même organisation : annonce de la variation, précision par contexte, conséquence pratique.", targetLanguageFeature: "organisation d'une nuance contextualisée", tags: ["nuance", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-context-nuance", prompt: "Idée de départ : vous nuancez votre position favorable à la suppression des notes chiffrées à l'école, selon que les familles concernées disposent ou non d'autres moyens de suivre les progrès de leur enfant.", instructions: "Rédigez 2 à 3 phrases qui nuancent votre position selon ces contextes différents.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La nuance doit préciser des contextes concrets et leurs conséquences différentes.", targetLanguageFeature: "nuance contextualisée", tags: ["nuance", "development"], selfCheck: ["La nuance précise au moins deux contextes concrets.", "Les conséquences varient réellement selon ces contextes.", "La nuance ne reste pas une réserve vague."] },
      { subSkill: "guided-context-nuance-alternative", prompt: "Idée de départ : vous nuancez votre position favorable au revenu de base pour les étudiants, selon que ceux-ci disposent ou non déjà d'un soutien familial suffisant.", instructions: "Rédigez 2 à 3 phrases qui nuancent votre position selon ces contextes différents.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La nuance doit préciser des contextes concrets et leurs conséquences différentes.", targetLanguageFeature: "nuance contextualisée", tags: ["nuance", "development", "variant"], selfCheck: ["La nuance précise au moins deux contextes concrets.", "Les conséquences varient réellement selon ces contextes.", "La nuance ne reste pas une réserve vague."] },
    ],
    [
      { subSkill: "independent-context-nuance", prompt: "Vous nuancez votre position favorable à l'encadrement de la publicité ciblant les enfants, selon l'âge du public visé.", instructions: "Rédigez 2 à 3 phrases qui nuancent votre position selon ces contextes différents.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une nuance C1 réussie précise des contextes concrets et leurs conséquences différentes.", targetLanguageFeature: "nuance contextualisée, autonome", tags: ["nuance", "production"], selfCheck: ["La nuance précise au moins deux contextes concrets.", "Les conséquences varient réellement selon ces contextes.", "La nuance ne reste pas vague."] },
      { subSkill: "independent-context-nuance-alternative", prompt: "Vous nuancez votre position favorable au compostage obligatoire, selon que les habitants disposent ou non d'un espace extérieur adapté.", instructions: "Rédigez 2 à 3 phrases qui nuancent votre position selon ces contextes différents.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une nuance C1 réussie précise des contextes concrets et leurs conséquences différentes.", targetLanguageFeature: "nuance contextualisée, autonome", tags: ["nuance", "production", "variant"], selfCheck: ["La nuance précise au moins deux contextes concrets.", "Les conséquences varient réellement selon ces contextes.", "La nuance ne reste pas vague."] },
    ],
  ]),

  ...taskThreeC1Path("t3-c1-conclusion", "conclusion", [
    [
      { subSkill: "conclude-with-complexity", prompt: "Vous concluez une analyse sur le télétravail obligatoire en tenant compte de la complexité du débat.", instructions: "Choisissez la conclusion la plus adaptée au niveau C1.", options: ["Le télétravail obligatoire est donc une bonne chose.", "Sans offrir de solution universelle, un jour de télétravail bien encadré semble constituer un compromis raisonnable entre efficacité et cohésion.", "Voilà pour le télétravail.", "Chacun peut avoir son avis sur le télétravail."], correctAnswer: "Sans offrir de solution universelle, un jour de télétravail bien encadré semble constituer un compromis raisonnable entre efficacité et cohésion.", acceptedAnswers: [], explanation: "Cette conclusion reconnaît explicitement l'absence de solution unique, ce qui reflète la complexité déjà mise en évidence dans l'analyse.", targetLanguageFeature: "conclusion tenant compte de la complexité", tags: ["conclusion", "recognize"] },
      { subSkill: "conclude-with-complexity-alternative", prompt: "Vous concluez une analyse sur l'encadrement des influenceurs en tenant compte de la complexité du débat.", instructions: "Choisissez la conclusion la plus adaptée au niveau C1.", options: ["L'encadrement des influenceurs est donc nécessaire.", "Sans offrir de solution universelle, un encadrement ciblé sur les publics les plus vulnérables semble constituer un compromis raisonnable.", "Voilà pour les influenceurs.", "Chacun peut avoir son avis sur les influenceurs."], correctAnswer: "Sans offrir de solution universelle, un encadrement ciblé sur les publics les plus vulnérables semble constituer un compromis raisonnable.", acceptedAnswers: [], explanation: "La conclusion reconnaît l'absence de solution unique, reflétant la complexité du débat.", targetLanguageFeature: "conclusion tenant compte de la complexité", tags: ["conclusion", "recognize", "variant"] },
    ],
    [
      { subSkill: "complexity-acknowledging-phrase", prompt: "Vous concluez en tenant compte de la complexité du débat.", instructions: "Complétez : « ______ offrir de solution universelle, un compromis encadré semble raisonnable. »", options: [], correctAnswer: "Sans", acceptedAnswers: ["Sans prétendre"], explanation: "Cette formule reconnaît explicitement les limites de la conclusion proposée.", targetLanguageFeature: "formule de reconnaissance des limites", tags: ["conclusion", "complete"] },
      { subSkill: "complexity-acknowledging-phrase-alternative", prompt: "Vous concluez en tenant compte de la complexité du débat.", instructions: "Complétez : « ______ offrir de solution universelle, un encadrement ciblé semble raisonnable. »", options: [], correctAnswer: "Sans", acceptedAnswers: ["Sans prétendre"], explanation: "La même formule reconnaît ici les limites de la conclusion.", targetLanguageFeature: "formule de reconnaissance des limites", tags: ["conclusion", "complete", "variant"] },
    ],
    [
      { subSkill: "add-complexity-to-flat-conclusion", prompt: "Transformez cette conclusion trop tranchée pour qu'elle tienne compte de la complexité du débat : « Le télétravail obligatoire est donc la meilleure solution. »", instructions: "Réécrivez en reconnaissant la complexité du débat.", options: [], correctAnswer: null, acceptedAnswers: ["Sans offrir de solution universelle, un jour de télétravail bien encadré semble constituer un compromis raisonnable entre efficacité et cohésion.", "Si aucune mesure ne fait totalement consensus, un télétravail encadré et progressif paraît la voie la plus équilibrée."], explanation: "La conclusion nuancée reconnaît l'absence de solution parfaite, ce qui reflète mieux la complexité du débat analysé.", targetLanguageFeature: "conclusion tenant compte de la complexité", tags: ["conclusion", "transform"] },
      { subSkill: "add-complexity-to-flat-conclusion-alternative", prompt: "Transformez cette conclusion trop tranchée : « L'encadrement des influenceurs est donc la meilleure solution. »", instructions: "Réécrivez en reconnaissant la complexité du débat.", options: [], correctAnswer: null, acceptedAnswers: ["Sans offrir de solution universelle, un encadrement ciblé sur les publics les plus vulnérables semble constituer un compromis raisonnable.", "Si aucune mesure ne fait totalement consensus, un encadrement progressif et ciblé paraît la voie la plus équilibrée."], explanation: "La conclusion nuancée reconnaît l'absence de solution parfaite.", targetLanguageFeature: "conclusion tenant compte de la complexité", tags: ["conclusion", "transform", "variant"] },
    ],
    [
      { subSkill: "complex-conclusion-order", prompt: "Vous concluez une analyse sur la réforme des retraites en tenant compte de sa complexité.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Cette analyse a montré qu'aucune solution ne satisfait pleinement tous les intérêts en jeu.", "Une réforme progressive, accompagnée de mesures de transition, semble néanmoins la voie la plus raisonnable.", "Elle ne résoudra pas pour autant toutes les tensions identifiées plus haut."], correctAnswer: ["Cette analyse a montré qu'aucune solution ne satisfait pleinement tous les intérêts en jeu.", "Une réforme progressive, accompagnée de mesures de transition, semble néanmoins la voie la plus raisonnable.", "Elle ne résoudra pas pour autant toutes les tensions identifiées plus haut."], acceptedAnswers: [], explanation: "La conclusion reconnaît d'abord la complexité, propose ensuite une voie raisonnable, puis rappelle les limites de cette proposition.", targetLanguageFeature: "organisation d'une conclusion complexe", tags: ["conclusion", "organization"] },
      { subSkill: "complex-conclusion-order-alternative", prompt: "Vous concluez une analyse sur le vote électronique en tenant compte de sa complexité.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Cette analyse a montré qu'aucune solution ne satisfait pleinement tous les intérêts en jeu.", "Une généralisation progressive, accompagnée de garanties techniques, semble néanmoins la voie la plus raisonnable.", "Elle ne résoudra pas pour autant toutes les inquiétudes identifiées plus haut."], correctAnswer: ["Cette analyse a montré qu'aucune solution ne satisfait pleinement tous les intérêts en jeu.", "Une généralisation progressive, accompagnée de garanties techniques, semble néanmoins la voie la plus raisonnable.", "Elle ne résoudra pas pour autant toutes les inquiétudes identifiées plus haut."], acceptedAnswers: [], explanation: "Même organisation : complexité, voie raisonnable, limites.", targetLanguageFeature: "organisation d'une conclusion complexe", tags: ["conclusion", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-complex-conclusion", prompt: "Idée de départ : vous concluez une analyse sur la suppression des notes chiffrées à l'école, un débat où aucune des deux sources n'apporte de solution pleinement satisfaisante.", instructions: "Rédigez 2 à 3 phrases de conclusion qui tiennent compte de cette complexité, sans la réduire à une position tranchée.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La conclusion doit reconnaître explicitement la complexité du débat plutôt que de la simplifier.", targetLanguageFeature: "conclusion tenant compte de la complexité", tags: ["conclusion", "development"], selfCheck: ["La conclusion reconnaît explicitement la complexité du débat.", "Une position ou une voie raisonnable est tout de même proposée.", "La conclusion n'introduit pas de nouvel argument."] },
      { subSkill: "guided-complex-conclusion-alternative", prompt: "Idée de départ : vous concluez une analyse sur l'instauration d'un revenu de base pour les étudiants, un débat où aucune des deux sources n'apporte de solution pleinement satisfaisante.", instructions: "Rédigez 2 à 3 phrases de conclusion qui tiennent compte de cette complexité, sans la réduire à une position tranchée.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La conclusion doit reconnaître explicitement la complexité du débat.", targetLanguageFeature: "conclusion tenant compte de la complexité", tags: ["conclusion", "development", "variant"], selfCheck: ["La conclusion reconnaît explicitement la complexité du débat.", "Une position ou une voie raisonnable est tout de même proposée.", "La conclusion n'introduit pas de nouvel argument."] },
    ],
    [
      { subSkill: "independent-complex-conclusion", prompt: "Vous concluez une analyse sur l'encadrement de la publicité ciblant les enfants, un débat où aucune des deux sources n'apporte de solution pleinement satisfaisante.", instructions: "Rédigez 2 à 3 phrases de conclusion qui tiennent compte de cette complexité.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une conclusion C1 réussie reconnaît la complexité du débat tout en proposant une voie raisonnable.", targetLanguageFeature: "conclusion tenant compte de la complexité, autonome", tags: ["conclusion", "production"], selfCheck: ["La conclusion reconnaît explicitement la complexité du débat.", "Une voie raisonnable est tout de même proposée.", "La conclusion n'introduit pas de nouvel argument."] },
      { subSkill: "independent-complex-conclusion-alternative", prompt: "Vous concluez une analyse sur la généralisation du compostage obligatoire en ville, un débat où aucune des deux sources n'apporte de solution pleinement satisfaisante.", instructions: "Rédigez 2 à 3 phrases de conclusion qui tiennent compte de cette complexité.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une conclusion C1 réussie reconnaît la complexité du débat tout en proposant une voie raisonnable.", targetLanguageFeature: "conclusion tenant compte de la complexité, autonome", tags: ["conclusion", "production", "variant"], selfCheck: ["La conclusion reconnaît explicitement la complexité du débat.", "Une voie raisonnable est tout de même proposée.", "La conclusion n'introduit pas de nouvel argument."] },
    ],
  ]),
];
