import type { PracticeExercise } from "./practice-curriculum";

/**
 * Fixed, editor-reviewed C2 material for Task 1. The helper below only
 * assigns the deterministic IDs and scaffold metadata; every prompt, answer,
 * explanation and self-check is authored in the static data below.
 */
type AuthoredVariant = Omit<
  PracticeExercise,
  "id" | "task" | "level" | "skill" | "exerciseType" | "difficulty" | "sequenceOrder" | "prerequisiteExerciseId"
>;

const STAGES: readonly PracticeExercise["exerciseType"][] = [
  "recognize",
  "complete",
  "transform",
  "organize",
  "develop",
  "produce",
];

const taskOneC2Path = (
  prefix: string,
  skill: string,
  stages: readonly (readonly [AuthoredVariant, AuthoredVariant])[],
): readonly PracticeExercise[] =>
  stages.flatMap(([primary, alternative], index) => {
    const sequenceOrder = (index + 1) as 1 | 2 | 3 | 4 | 5 | 6;
    const prerequisiteExerciseId = index === 0 ? null : `${prefix}-${index}`;
    const shared = {
      task: "TASK_1" as const,
      level: "C2" as const,
      skill,
      exerciseType: STAGES[index]!,
      difficulty: sequenceOrder,
      sequenceOrder,
      prerequisiteExerciseId,
    };

    return [
      { id: `${prefix}-${sequenceOrder}`, ...shared, ...primary },
      { id: `${prefix}-a${sequenceOrder}`, ...shared, ...alternative },
    ];
  });

export const TASK_1_C2_EXERCISES: readonly PracticeExercise[] = [
  ...taskOneC2Path("t1-c2-suggestions-invitations", "suggestions-invitations", [
    [
      { subSkill: "strategic-proposal-calibration", prompt: "Vous proposez à deux associations partenaires de mutualiser une campagne, mais l'une craint de perdre la visibilité de son propre projet.", instructions: "Choisissez la proposition qui tient réellement compte de cet enjeu sans renoncer au projet commun.", options: ["Faisons une seule campagne, ce sera plus simple.", "Nous pourrions envisager une campagne commune dont chaque association conserverait un volet identifiable ; si vous le jugez pertinent, définissons ensemble les messages qui doivent rester propres à chaque projet.", "Votre association aura moins de visibilité, mais ce n'est pas grave.", "Acceptez la campagne commune, c'est décidé."], correctAnswer: "Nous pourrions envisager une campagne commune dont chaque association conserverait un volet identifiable ; si vous le jugez pertinent, définissons ensemble les messages qui doivent rester propres à chaque projet.", acceptedAnswers: [], explanation: "La proposition C2 nomme l'enjeu relationnel, protège l'autonomie du partenaire et transforme la réserve en point de conception commun.", targetLanguageFeature: "proposition stratégique et inclusive", tags: ["suggestions", "strategy", "recognize"] },
      { subSkill: "strategic-proposal-calibration-alternative", prompt: "Vous proposez à une collectivité de cofinancer un projet avec une entreprise locale qui redoute une récupération de son image.", instructions: "Choisissez la formulation qui protège l'intérêt des deux parties.", options: ["L'entreprise donnera l'argent et la collectivité fera la communication.", "Nous pourrions définir un partenariat dans lequel la collectivité garantit l'intérêt général du projet tandis que l'entreprise dispose d'une visibilité sobre, convenue à l'avance et proportionnée à son soutien.", "L'entreprise n'a qu'à accepter, elle y gagnera de la publicité.", "On verra la communication plus tard."], correctAnswer: "Nous pourrions définir un partenariat dans lequel la collectivité garantit l'intérêt général du projet tandis que l'entreprise dispose d'une visibilité sobre, convenue à l'avance et proportionnée à son soutien.", acceptedAnswers: [], explanation: "La proposition C2 rend les intérêts compatibles sans réduire l'un des partenaires à un simple moyen pour l'autre.", targetLanguageFeature: "équilibre des intérêts dans une proposition", tags: ["suggestions", "strategy", "recognize", "variant"] },
    ],
    [
      { subSkill: "conditional-scope-control", prompt: "Vous proposez une expérimentation à un partenaire qui craint un engagement trop long.", instructions: "Complétez : « Nous pourrions, dans un premier temps, limiter l'expérimentation à deux mois, ______ cela vous permettrait d'en évaluer les effets sans vous engager au-delà. »", options: [], correctAnswer: "ce qui", acceptedAnswers: ["ainsi"], explanation: "La formulation délimite l'engagement et justifie cette limite par l'autonomie de décision du partenaire.", targetLanguageFeature: "maîtrise de la portée d'une proposition", tags: ["suggestions", "scope", "complete"] },
      { subSkill: "conditional-scope-control-alternative", prompt: "Vous proposez d'associer un expert extérieur à un projet, mais l'équipe craint de perdre la maîtrise du contenu.", instructions: "Complétez : « Son intervention pourrait être limitée à une relecture ciblée, ______ l'équipe conserverait la responsabilité des choix finaux. »", options: [], correctAnswer: "de sorte que", acceptedAnswers: ["ainsi"], explanation: "La phrase délimite le rôle proposé et explicite l'autonomie qui reste à l'équipe.", targetLanguageFeature: "délimitation d'un rôle", tags: ["suggestions", "scope", "complete", "variant"] },
    ],
    [
      { subSkill: "resolve-objection-through-design", prompt: "Reformulez : « On devrait déplacer l'événement dans vos locaux, ce sera plus pratique. » Le partenaire craint que son équipe doive tout organiser.", instructions: "Proposez le changement en reconnaissant cette réserve et en précisant une répartition réaliste des responsabilités.", options: [], correctAnswer: null, acceptedAnswers: ["Nous pourrions envisager vos locaux si cela vous paraît pertinent ; afin de ne pas alourdir la charge de votre équipe, nous pourrions prendre en charge l'accueil et la logistique, en vous laissant valider les aspects qui vous concernent.", "Si le lieu vous convient, nous serions prêts à organiser l'événement dans vos locaux tout en assumant la préparation opérationnelle ; nous pourrions convenir ensemble des points qui nécessitent votre intervention."], explanation: "Au C2, une proposition répond à l'objection par un dispositif concret plutôt que par une promesse vague.", targetLanguageFeature: "intégration d'une réserve dans la proposition", tags: ["suggestions", "negotiation", "transform"] },
      { subSkill: "resolve-objection-through-design-alternative", prompt: "Reformulez : « Il faut publier le rapport dès lundi. » Le partenaire demande du temps pour vérifier les données qui le concernent.", instructions: "Faites une proposition qui conserve l'objectif de publication tout en intégrant un mécanisme de vérification crédible.", options: [], correctAnswer: null, acceptedAnswers: ["Nous pourrions viser une publication lundi, sous réserve de vous transmettre dès aujourd'hui les données qui vous concernent afin que vous puissiez les vérifier ; à défaut, nous pourrions publier la synthèse et différer l'annexe concernée.", "Afin de préserver l'échéance de lundi sans vous priver d'une vérification nécessaire, nous pourrions convenir d'un relecteur et d'un délai précis, ou dissocier les données à confirmer du reste du rapport."], explanation: "La reformulation C2 maintient l'objectif, organise la réserve et prévoit ce qui se passe si elle ne peut être levée à temps.", targetLanguageFeature: "proposition avec condition et solution de repli", tags: ["suggestions", "transform", "variant"] },
    ],
    [
      { subSkill: "shared-decision-order", prompt: "Vous proposez à une équipe de tester un nouvel outil, alors que certains craignent la perte de temps liée à la formation.", instructions: "Organisez le passage de manière à reconnaître la réserve, borner l'essai et ouvrir une décision commune.", options: ["Cette réserve justifie, me semble-t-il, de limiter l'essai à un petit groupe volontaire pendant un mois.", "Si les résultats sont concluants, nous pourrions ensuite décider ensemble de son éventuelle extension.", "Plusieurs collègues ont souligné, à juste titre, que la prise en main d'un nouvel outil demande du temps."], correctAnswer: ["Plusieurs collègues ont souligné, à juste titre, que la prise en main d'un nouvel outil demande du temps.", "Cette réserve justifie, me semble-t-il, de limiter l'essai à un petit groupe volontaire pendant un mois.", "Si les résultats sont concluants, nous pourrions ensuite décider ensemble de son éventuelle extension."], acceptedAnswers: [], explanation: "L'ordre donne une place réelle à la réserve, propose une expérimentation limitée, puis reporte toute généralisation à une décision informée.", targetLanguageFeature: "réserve → essai limité → décision partagée", tags: ["suggestions", "organization", "strategy"] },
      { subSkill: "shared-decision-order-alternative", prompt: "Vous proposez à une équipe de modifier une procédure dont certains redoutent les effets sur les usagers.", instructions: "Mettez les phrases dans l'ordre qui rend la décision prudente et partagée.", options: ["Nous pourrions donc tester la modification sur un nombre limité de dossiers et recueillir les retours des usagers concernés.", "Avant toute généralisation, nous déciderions ensemble à partir de ces retours et des critères convenus.", "Plusieurs collègues ont relevé que cette modification pourrait compliquer l'accès de certains usagers au service."], correctAnswer: ["Plusieurs collègues ont relevé que cette modification pourrait compliquer l'accès de certains usagers au service.", "Nous pourrions donc tester la modification sur un nombre limité de dossiers et recueillir les retours des usagers concernés.", "Avant toute généralisation, nous déciderions ensemble à partir de ces retours et des critères convenus."], acceptedAnswers: [], explanation: "La progression reconnaît le risque, encadre l'essai et conditionne la décision à des éléments examinés collectivement.", targetLanguageFeature: "décision progressive et étayée", tags: ["suggestions", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-high-stakes-proposal", prompt: "Vous proposez à un partenaire public de repousser le lancement d'un projet de deux semaines afin d'intégrer les retours des habitants. Ce report peut compliquer son calendrier politique.", instructions: "Rédigez 4 ou 5 phrases : reconnaissez l'enjeu du calendrier, expliquez la valeur du report sans l'exagérer, proposez un cadre limité et ouvrez une alternative si le décalage est impossible.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une proposition C2 préserve la relation quand les intérêts ne sont pas parfaitement alignés : elle nomme le coût, justifie le choix et garde une issue praticable.", targetLanguageFeature: "proposition à enjeux contradictoires", tags: ["suggestions", "development", "diplomacy"], selfCheck: ["Je reconnais clairement la contrainte du partenaire.", "Je justifie le report par un effet concret et proportionné.", "Je propose une limite ou une alternative qui rend la décision praticable."] },
      { subSkill: "guided-high-stakes-proposal-alternative", prompt: "Vous souhaitez proposer à une organisation partenaire d'accueillir un public supplémentaire dans son programme, mais elle craint de dégrader la qualité de l'accompagnement.", instructions: "Rédigez 4 ou 5 phrases : prenez cette crainte au sérieux, proposez un accueil progressif avec des critères de suivi et indiquez la condition à laquelle l'extension serait réexaminée.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le C2 ne promet pas que tout se passera bien : il propose un cadre qui permet de décider à partir d'effets observables.", targetLanguageFeature: "proposition progressive avec critères", tags: ["suggestions", "development", "variant"], selfCheck: ["Je reformule la crainte sans la minimiser.", "L'expérimentation est limitée et accompagnée de critères concrets.", "Je précise comment et à quelle condition une suite serait décidée."] },
    ],
    [
      { subSkill: "independent-strategic-proposal", prompt: "Vous écrivez à une fondation qui finance votre projet. Vous souhaitez proposer une modification du programme pour répondre à un besoin apparu sur le terrain, mais la fondation doit conserver des indicateurs comparables.", instructions: "Rédigez un passage de 90 à 110 mots : formulez la proposition avec précision, montrez que vous comprenez la contrainte de la fondation, expliquez comment la modification resterait évaluable et invitez-la à décider avec vous.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production C2 doit concilier une adaptation nécessaire, un cadre mesurable et l'autorité de décision du partenaire.", targetLanguageFeature: "proposition autonome à enjeux institutionnels", tags: ["suggestions", "production", "institutional"], selfCheck: ["La modification proposée est précise et reliée à un besoin identifié.", "Je reconnais explicitement la contrainte d'évaluation de la fondation.", "Je propose un cadre qui permet une décision partagée et mesurable."] },
      { subSkill: "independent-strategic-proposal-alternative", prompt: "Vous écrivez à un réseau d'associations pour proposer une campagne commune, alors que leurs publics et leurs contraintes de communication ne sont pas identiques.", instructions: "Rédigez un passage de 90 à 110 mots : formulez une proposition souple, montrez comment chaque association pourrait conserver son identité, prévoyez une phase d'essai et invitez-les à définir ensemble les critères de réussite.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une production C2 réussie propose une coopération concrète sans effacer les différences légitimes entre les partenaires.", targetLanguageFeature: "proposition partenariale nuancée", tags: ["suggestions", "production", "variant"], selfCheck: ["La proposition respecte l'identité et les contraintes de chaque partenaire.", "Je prévois un essai limité plutôt qu'un engagement indéfini.", "Je rends explicites les critères qui permettront une décision commune."] },
    ],
  ]),
  ...taskOneC2Path("t1-c2-message-purpose", "message-purpose", [
    [
      { subSkill: "precise-purpose-with-scope", prompt: "Vous écrivez à une administration partenaire après avoir reçu une information contradictoire sur l'éligibilité de votre dossier.", instructions: "Choisissez la phrase qui annonce un but précis sans tirer de conclusion hâtive.", options: ["Je vous écris parce que votre réponse est incompréhensible.", "Afin de clarifier l'éligibilité de notre dossier, je souhaiterais vérifier avec vous quel critère s'applique à notre situation avant de poursuivre la procédure.", "Votre service doit nous dire ce qui se passe.", "Nous avons besoin d'une réponse, merci."], correctAnswer: "Afin de clarifier l'éligibilité de notre dossier, je souhaiterais vérifier avec vous quel critère s'applique à notre situation avant de poursuivre la procédure.", acceptedAnswers: [], explanation: "Le but C2 définit l'incertitude, la question à trancher et l'action qui en dépend, sans accuser le destinataire.", targetLanguageFeature: "but précis avec portée délimitée", tags: ["purpose", "recognize", "precision"] },
      { subSkill: "precise-purpose-with-scope-alternative", prompt: "Vous écrivez à un partenaire après avoir découvert que deux versions d'un accord circulent.", instructions: "Choisissez l'ouverture qui annonce le but avec la précision nécessaire.", options: ["Il y a un problème avec l'accord.", "Je me permets de vous contacter afin de convenir de la version de référence de notre accord, les documents actuellement en circulation comportant deux formulations différentes sur le calendrier.", "Vos documents sont mal faits.", "Pouvez-vous corriger cela ?"], correctAnswer: "Je me permets de vous contacter afin de convenir de la version de référence de notre accord, les documents actuellement en circulation comportant deux formulations différentes sur le calendrier.", acceptedAnswers: [], explanation: "La phrase circonscrit le désaccord et indique le résultat recherché sans faire porter la faute à l'autre partie.", targetLanguageFeature: "objet et résultat recherchés", tags: ["purpose", "recognize", "variant"] },
    ],
    [
      { subSkill: "purpose-for-decision", prompt: "Vous demandez à une responsable de confirmer un point avant d'engager une dépense.", instructions: "Complétez : « Je vous écris afin de ______ si cette dépense peut être engagée dans le cadre du budget actuel. »", options: [], correctAnswer: "confirmer", acceptedAnswers: ["vérifier", "m'assurer"], explanation: "Le verbe introduit une démarche de vérification liée à une décision précise, et non une demande vague d'information.", targetLanguageFeature: "but lié à une décision", tags: ["purpose", "complete", "decision"] },
      { subSkill: "purpose-for-decision-alternative", prompt: "Vous souhaitez agir après un échange verbal dont un point reste ambigu.", instructions: "Complétez : « Je reviens vers vous afin de ______ le périmètre exact de notre intervention avant de confirmer les prochaines étapes. »", options: [], correctAnswer: "préciser", acceptedAnswers: ["clarifier", "délimiter"], explanation: "Le but est de lever une ambiguïté concrète avant une action ultérieure.", targetLanguageFeature: "clarification préalable à l'action", tags: ["purpose", "complete", "variant"] },
    ],
    [
      { subSkill: "vague-to-delimited-purpose", prompt: "Reformulez : « Je vous écris pour le projet. » Vous devez obtenir l'accord sur une modification qui touche seulement la phase de test.", instructions: "Annoncez le but en précisant l'objet limité de votre demande et l'action attendue.", options: [], correctAnswer: null, acceptedAnswers: ["Je vous écris afin d'obtenir votre accord sur l'ajustement proposé pour la seule phase de test du projet.", "Je souhaiterais vous soumettre une modification limitée à la phase de test et vérifier qu'elle recueille votre accord avant sa mise en œuvre."], explanation: "Le C2 remplace un thème général par un objet circonscrit, une décision attendue et un moment d'action clair.", targetLanguageFeature: "délimitation précise du but", tags: ["purpose", "transform", "scope"] },
      { subSkill: "vague-to-delimited-purpose-alternative", prompt: "Reformulez : « Je vous contacte à propos du rapport. » Vous voulez savoir si une donnée peut être retirée avant publication.", instructions: "Formulez un but précis, sans supposer que la donnée doit nécessairement être retirée.", options: [], correctAnswer: null, acceptedAnswers: ["Je vous contacte afin d'examiner avec vous s'il serait justifié de retirer cette donnée avant la publication du rapport.", "Avant publication, je souhaiterais vérifier avec vous si cette donnée doit être maintenue au regard des éléments disponibles."], explanation: "La formulation C2 pose une question de méthode au lieu d'annoncer une conclusion ou une exigence non fondée.", targetLanguageFeature: "but conditionnel et non présupposé", tags: ["purpose", "transform", "variant"] },
    ],
    [
      { subSkill: "context-purpose-condition-order", prompt: "Vous écrivez à un financeur : un nouvel élément de terrain peut modifier une action prévue, mais vous ne souhaitez rien changer sans son accord.", instructions: "Mettez les éléments dans l'ordre d'une ouverture précise.", options: ["Cette évolution nous conduit à solliciter votre accord avant de modifier l'action prévue.", "Depuis le lancement, la fréquentation du dispositif a évolué de manière inattendue.", "Nous avons identifié une adaptation limitée qui permettrait de répondre à ce besoin sans modifier les objectifs du programme."], correctAnswer: ["Depuis le lancement, la fréquentation du dispositif a évolué de manière inattendue.", "Nous avons identifié une adaptation limitée qui permettrait de répondre à ce besoin sans modifier les objectifs du programme.", "Cette évolution nous conduit à solliciter votre accord avant de modifier l'action prévue."], acceptedAnswers: [], explanation: "Le contexte établi justifie l'adaptation, qui conduit ensuite à une demande d'accord clairement délimitée.", targetLanguageFeature: "contexte → option → but", tags: ["purpose", "organization", "reasoning"] },
      { subSkill: "context-purpose-condition-order-alternative", prompt: "Vous écrivez à une direction après avoir reçu une instruction dont le champ d'application est incertain.", instructions: "Organisez l'ouverture de façon à demander une clarification sans bloquer inutilement le travail.", options: ["Afin d'appliquer cette instruction de manière cohérente, nous souhaiterions confirmer si elle concerne également les dossiers déjà ouverts.", "La note transmise hier prévoit une nouvelle procédure à compter du 1er juin.", "Son application aux dossiers en cours n'est toutefois pas explicitée."], correctAnswer: ["La note transmise hier prévoit une nouvelle procédure à compter du 1er juin.", "Son application aux dossiers en cours n'est toutefois pas explicitée.", "Afin d'appliquer cette instruction de manière cohérente, nous souhaiterions confirmer si elle concerne également les dossiers déjà ouverts."], acceptedAnswers: [], explanation: "L'ouverture présente le document, nomme l'ambiguïté puis annonce l'objectif pratique de la demande.", targetLanguageFeature: "document → ambiguïté → clarification", tags: ["purpose", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-purpose-with-institutional-stakes", prompt: "Vous écrivez à une organisation partenaire : une décision annoncée oralement semble avoir des effets différents de ceux compris par votre équipe.", instructions: "Rédigez 3 ou 4 phrases qui situent l'échange, identifient précisément ce qui doit être clarifié et expliquent pourquoi cette clarification est nécessaire avant toute suite.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le but C2 prend appui sur un désaccord d'interprétation sans le présenter comme une faute, et relie la clarification à une prochaine action.", targetLanguageFeature: "but institutionnel avec enjeu", tags: ["purpose", "development", "institutional"], selfCheck: ["Je situe l'échange ou le document concerné avec précision.", "Je distingue le point à clarifier de toute accusation générale.", "J'explique quelle action dépend de cette clarification."] },
      { subSkill: "guided-purpose-with-institutional-stakes-alternative", prompt: "Vous écrivez à un partenaire après avoir constaté que le calendrier annoncé risque de compromettre une étape de validation essentielle.", instructions: "Rédigez 3 ou 4 phrases : annoncez le but de votre message, décrivez l'enjeu sans dramatiser et demandez l'examen d'une option concrète.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une formulation C2 transforme un risque en objet de discussion précis, au lieu de réclamer un changement non justifié.", targetLanguageFeature: "but précis face à un risque", tags: ["purpose", "development", "variant"], selfCheck: ["Le calendrier et l'étape concernée sont clairement identifiables.", "Je formule le risque avec une portée proportionnée.", "Je demande l'examen d'une option concrète, sans la présenter comme acquise."] },
    ],
    [
      { subSkill: "independent-purpose-with-governance", prompt: "Vous écrivez à un partenaire institutionnel pour demander qu'une décision soit réexaminée : de nouvelles données peuvent modifier son effet sur un public précis, mais vous ne contestez pas son principe.", instructions: "Rédigez 90 à 110 mots : situez la décision, annoncez exactement l'objet du réexamen, expliquez l'enjeu des nouvelles données et indiquez la suite que vous sollicitez.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production C2 doit tenir ensemble la légitimité de la décision initiale, un motif précis de réexamen et une demande de procédure praticable.", targetLanguageFeature: "but autonome dans une relation institutionnelle", tags: ["purpose", "production", "institutional"], selfCheck: ["Je distingue la décision initiale du point limité que je demande de réexaminer.", "Les nouvelles données et leur effet sont formulés avec précision.", "La suite sollicitée est concrète et respecte le rôle du destinataire."] },
      { subSkill: "independent-purpose-with-governance-alternative", prompt: "Vous écrivez à une fondation avant de modifier un projet financé : le besoin de terrain a évolué, mais les objectifs contractuels doivent rester traçables.", instructions: "Rédigez 90 à 110 mots : présentez le contexte, formulez le but exact de votre démarche, montrez le lien entre l'adaptation et les objectifs, puis sollicitez un échange ou un accord défini.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une production C2 formule une adaptation comme une décision à instruire avec le financeur, non comme un fait accompli.", targetLanguageFeature: "but autonome et traçable", tags: ["purpose", "production", "variant"], selfCheck: ["Le contexte et le besoin nouveau sont clairement définis.", "Je précise l'adaptation envisagée sans la présenter comme déjà approuvée.", "Je relie ma demande à une étape de décision ou de validation identifiable."] },
    ],
  ]),
  ...taskOneC2Path("t1-c2-giving-information", "giving-information", [
    [
      { subSkill: "fact-source-impact-hierarchy", prompt: "Vous informez un partenaire d'un incident qui a touché une partie de votre service, sans encore connaître toutes les causes.", instructions: "Choisissez la formulation qui distingue correctement le fait établi, l'incertitude et l'effet concret.", options: ["Tout le système est tombé à cause d'une erreur grave.", "Depuis ce matin, l'accès au portail est interrompu pour certains usagers ; l'origine fait encore l'objet de vérifications, mais les rendez-vous prévus en ligne doivent être reprogrammés.", "Le portail ne marche plus, on cherche pourquoi.", "Il y a probablement un gros problème technique."], correctAnswer: "Depuis ce matin, l'accès au portail est interrompu pour certains usagers ; l'origine fait encore l'objet de vérifications, mais les rendez-vous prévus en ligne doivent être reprogrammés.", acceptedAnswers: [], explanation: "L'information C2 sépare le fait observé de l'hypothèse et indique immédiatement la conséquence qui permet d'agir.", targetLanguageFeature: "fait, incertitude et conséquence", tags: ["information", "recognize", "precision"] },
      { subSkill: "fact-source-impact-hierarchy-alternative", prompt: "Vous transmettez à une direction un constat issu de plusieurs retours de terrain, sans pouvoir l'ériger encore en conclusion générale.", instructions: "Choisissez la phrase la plus rigoureuse.", options: ["Le nouveau dispositif ne fonctionne pas du tout.", "Les retours recueillis auprès de six équipes font apparaître une difficulté récurrente d'accès ; cette tendance devra être confirmée, mais elle justifie déjà un suivi ciblé.", "Tout le monde est contre le nouveau dispositif.", "On sait que cette mesure est inefficace."], correctAnswer: "Les retours recueillis auprès de six équipes font apparaître une difficulté récurrente d'accès ; cette tendance devra être confirmée, mais elle justifie déjà un suivi ciblé.", acceptedAnswers: [], explanation: "La formulation donne la source, limite la portée de l'inférence et explique pourquoi l'information reste utile dès maintenant.", targetLanguageFeature: "portée maîtrisée d'une information", tags: ["information", "recognize", "variant"] },
    ],
    [
      { subSkill: "qualified-cause", prompt: "Vous décrivez un retard de traitement dont la cause n'est pas certaine.", instructions: "Complétez : « Ce retard semble ______ à la mise à jour récente du système, sans que cette hypothèse puisse encore être confirmée. »", options: [], correctAnswer: "lié", acceptedAnswers: ["être lié", "probablement lié"], explanation: "Le qualificatif maintient la distinction entre une cause possible et un fait établi.", targetLanguageFeature: "cause qualifiée", tags: ["information", "complete", "qualification"] },
      { subSkill: "qualified-cause-alternative", prompt: "Vous décrivez un écart constaté dans des données sans connaître encore son origine.", instructions: "Complétez : « Cet écart pourrait ______ d'une saisie incomplète sur certains dossiers. »", options: [], correctAnswer: "provenir", acceptedAnswers: ["résulter", "être la conséquence"], explanation: "Le conditionnel indique une piste d'explication sans transformer l'hypothèse en affirmation.", targetLanguageFeature: "hypothèse explicitement limitée", tags: ["information", "complete", "variant"] },
    ],
    [
      { subSkill: "enumeration-to-hierarchy", prompt: "Reformulez ces informations : « Trois personnes ont signalé un problème. Le formulaire change parfois de langue. On ne sait pas encore pourquoi. Les inscriptions peuvent être retardées. »", instructions: "Produisez une ou deux phrases qui hiérarchisent le fait principal, l'incertitude et l'effet attendu.", options: [], correctAnswer: null, acceptedAnswers: ["Trois usagers ont signalé que le formulaire bascule parfois dans une autre langue ; la cause reste à déterminer, mais ce dysfonctionnement pourrait retarder leurs inscriptions.", "Des changements de langue imprévus, signalés par trois personnes, risquent de retarder certaines inscriptions, même si leur origine n'est pas encore établie."], explanation: "Le C2 organise les informations selon leur rôle au lieu de les accumuler dans l'ordre où elles ont été apprises.", targetLanguageFeature: "hiérarchisation d'informations incertaines", tags: ["information", "transform", "organization"] },
      { subSkill: "enumeration-to-hierarchy-alternative", prompt: "Reformulez : « La réunion a été annulée. Le formateur est malade. Une autre date sera proposée. On ne sait pas encore quand. »", instructions: "Faites apparaître l'information essentielle, ce qui est certain et ce qui reste ouvert.", options: [], correctAnswer: null, acceptedAnswers: ["La réunion est annulée en raison de l'indisponibilité du formateur ; une nouvelle date sera proposée dès que son calendrier pourra être confirmé.", "En raison de l'indisponibilité du formateur, la réunion ne pourra avoir lieu comme prévu ; nous vous communiquerons une nouvelle date lorsque celle-ci sera arrêtée."], explanation: "Une formulation précise sépare l'annulation, sa cause connue et le point qui reste à confirmer.", targetLanguageFeature: "fait établi et suite conditionnelle", tags: ["information", "transform", "variant"] },
    ],
    [
      { subSkill: "evidence-impact-action-order", prompt: "Vous devez informer une équipe qu'un changement de procédure produit un effet inattendu et qu'une mesure provisoire est nécessaire.", instructions: "Mettez les éléments dans l'ordre le plus utile pour décider.", options: ["Dans l'attente d'une analyse complète, il paraît prudent de maintenir l'ancienne procédure pour les dossiers urgents.", "Depuis lundi, plusieurs équipes signalent que la nouvelle procédure allonge fortement le délai de validation.", "Les premières données disponibles confirment que les dossiers urgents sont les plus touchés."], correctAnswer: ["Depuis lundi, plusieurs équipes signalent que la nouvelle procédure allonge fortement le délai de validation.", "Les premières données disponibles confirment que les dossiers urgents sont les plus touchés.", "Dans l'attente d'une analyse complète, il paraît prudent de maintenir l'ancienne procédure pour les dossiers urgents."], acceptedAnswers: [], explanation: "On présente le constat, précise l'effet étayé, puis propose une mesure proportionnée à l'incertitude restante.", targetLanguageFeature: "constat → impact → mesure provisoire", tags: ["information", "organization", "evidence"] },
      { subSkill: "evidence-impact-action-order-alternative", prompt: "Vous informez un partenaire que la fréquentation d'un service a changé depuis une campagne de communication.", instructions: "Organisez le passage de manière rigoureuse.", options: ["Il conviendrait donc d'observer cette évolution sur un mois supplémentaire avant d'ajuster les moyens affectés.", "Les données de la dernière quinzaine montrent une hausse nette des demandes sur ce service.", "Cette hausse coïncide avec la campagne, sans suffire à établir qu'elle en est l'unique cause."], correctAnswer: ["Les données de la dernière quinzaine montrent une hausse nette des demandes sur ce service.", "Cette hausse coïncide avec la campagne, sans suffire à établir qu'elle en est l'unique cause.", "Il conviendrait donc d'observer cette évolution sur un mois supplémentaire avant d'ajuster les moyens affectés."], acceptedAnswers: [], explanation: "L'ordre distingue l'observation, la limite de l'interprétation et la décision prudente qui en découle.", targetLanguageFeature: "observation → limite → suivi", tags: ["information", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-evidence-based-information", prompt: "Vous informez une direction qu'un test mené auprès de quelques usagers révèle une difficulté d'accès, mais l'échantillon reste limité.", instructions: "Rédigez 3 ou 4 phrases : présentez le constat, indiquez ce que les données permettent et ne permettent pas d'affirmer, puis proposez une suite adaptée.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Au C2, une information utile ne masque ni la source ni les limites de ce qu'elle permet de conclure.", targetLanguageFeature: "information étayée et nuancée", tags: ["information", "development", "evidence"], selfCheck: ["Je précise la source ou le périmètre du constat.", "Je distingue clairement l'observation de l'interprétation.", "La suite proposée est proportionnée au niveau de certitude."] },
      { subSkill: "guided-evidence-based-information-alternative", prompt: "Vous signalez à un partenaire une baisse de participation observée sur deux semaines, sans savoir encore si elle est liée au nouveau lieu ou au changement d'horaire.", instructions: "Rédigez 3 ou 4 phrases : donnez les faits, formulez les hypothèses avec prudence et indiquez l'information qui permettrait de décider.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le développement C2 maintient plusieurs explications possibles plutôt que de choisir arbitrairement une cause.", targetLanguageFeature: "hypothèses et données manquantes", tags: ["information", "development", "variant"], selfCheck: ["Les faits observés sont séparés des hypothèses.", "Je n'attribue pas la baisse à une cause non vérifiée.", "Je précise quelle information supplémentaire aiderait à décider."] },
    ],
    [
      { subSkill: "independent-evidence-based-information", prompt: "Vous écrivez à un partenaire institutionnel après avoir constaté que des usagers renoncent à une démarche en ligne. Les retours disponibles sont partiels, mais l'effet peut être important.", instructions: "Rédigez 90 à 110 mots : présentez les éléments établis, la limite des données, les conséquences possibles et la mesure provisoire que vous recommandez.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production C2 doit rendre une décision possible sans présenter un dossier encore incomplet comme une certitude.", targetLanguageFeature: "information autonome, rigoureuse et actionnable", tags: ["information", "production", "institutional"], selfCheck: ["Je distingue les faits observés, les limites et les conséquences possibles.", "Je ne tire pas de conclusion plus large que les données ne le permettent.", "La mesure proposée est provisoire et reliée au risque identifié."] },
      { subSkill: "independent-evidence-based-information-alternative", prompt: "Vous rédigez une note à votre direction après un incident qui a affecté un service pendant une demi-journée. L'origine technique est en cours d'analyse, mais les équipes ont déjà identifié des effets sur le public.", instructions: "Rédigez 90 à 110 mots : hiérarchisez les faits, les incertitudes et les impacts, puis indiquez le suivi ou l'information que vous préconisez.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une note C2 fiable permet d'agir malgré l'incertitude, à condition de nommer ce qui reste à vérifier.", targetLanguageFeature: "note factuelle avec incertitude maîtrisée", tags: ["information", "production", "variant"], selfCheck: ["Le fait principal, son impact et la cause encore incertaine sont clairement distingués.", "Je hiérarchise les informations au lieu de les énumérer.", "Je propose un suivi concret correspondant au niveau d'incertitude."] },
    ],
  ]),
  ...taskOneC2Path("t1-c2-asking-information", "asking-information", [
    [
      { subSkill: "decision-relevant-question", prompt: "Vous devez choisir entre deux dispositifs de formation et écrivez à l'organisme qui les propose.", instructions: "Choisissez la question qui permet réellement de décider sans demander une information trop générale.", options: ["Pouvez-vous m'en dire plus ?", "Pourriez-vous préciser quels accompagnements restent accessibles après les séances et selon quels critères les participants y sont orientés ?", "Votre formation est-elle bien ?", "Combien ça coûte exactement ?"], correctAnswer: "Pourriez-vous préciser quels accompagnements restent accessibles après les séances et selon quels critères les participants y sont orientés ?", acceptedAnswers: [], explanation: "La question C2 cible une information qui change la décision et demande les conditions de son application.", targetLanguageFeature: "question ciblée sur un critère de décision", tags: ["questions", "recognize", "precision"] },
      { subSkill: "decision-relevant-question-alternative", prompt: "Vous envisagez un partenariat avec un prestataire qui annonce un délai de mise en œuvre très court.", instructions: "Choisissez la question la plus utile avant de vous engager.", options: ["Vous êtes sûrs que ce sera rapide ?", "Pourriez-vous indiquer quelles étapes doivent encore être validées avant le démarrage et quel élément pourrait, le cas échéant, modifier le délai annoncé ?", "Ça prend combien de temps ?", "Vous commencez lundi, n'est-ce pas ?"], correctAnswer: "Pourriez-vous indiquer quelles étapes doivent encore être validées avant le démarrage et quel élément pourrait, le cas échéant, modifier le délai annoncé ?", acceptedAnswers: [], explanation: "La formulation cherche les conditions et les risques de variation, plutôt qu'une promesse simplifiée.", targetLanguageFeature: "question sur conditions et incertitude", tags: ["questions", "recognize", "variant"] },
    ],
    [
      { subSkill: "scope-question-marker", prompt: "Vous cherchez à savoir si une règle s'applique à une situation particulière.", instructions: "Complétez : « Pourriez-vous m'indiquer ______ cette règle s'applique également aux dossiers déjà engagés ? »", options: [], correctAnswer: "dans quelle mesure", acceptedAnswers: ["si", "à quelles conditions"], explanation: "La formule permet de demander la portée d'une règle sans présupposer une réponse binaire.", targetLanguageFeature: "interrogation sur la portée", tags: ["questions", "complete", "scope"] },
      { subSkill: "scope-question-marker-alternative", prompt: "Vous voulez comprendre les limites d'un accompagnement annoncé par un organisme.", instructions: "Complétez : « Serait-il possible de préciser ______ les participants peuvent solliciter cet accompagnement après la fin du programme ? »", options: [], correctAnswer: "dans quelles conditions", acceptedAnswers: ["à quelles conditions", "jusqu'à quel point"], explanation: "La question demande les critères d'accès et non une assurance générale.", targetLanguageFeature: "conditions d'accès", tags: ["questions", "complete", "variant"] },
    ],
    [
      { subSkill: "vague-to-operational-question", prompt: "Reformulez : « Est-ce que vous pouvez m'aider pour le dossier ? » Vous devez savoir qui peut vérifier les pièces et dans quel délai.", instructions: "Rédigez une question précise qui permette au destinataire de répondre de manière actionnable.", options: [], correctAnswer: null, acceptedAnswers: ["Pourriez-vous m'indiquer quel service peut vérifier les pièces de mon dossier et sous quel délai je peux espérer un retour ?", "Afin de finaliser mon dossier, je souhaiterais savoir à qui transmettre les pièces pour vérification et quel délai de traitement est habituellement prévu."], explanation: "La reformulation C2 découpe une demande floue en informations nécessaires à l'action : interlocuteur, opération et délai.", targetLanguageFeature: "question opérationnelle", tags: ["questions", "transform", "decision"] },
      { subSkill: "vague-to-operational-question-alternative", prompt: "Reformulez : « Vous avez des règles pour les modifications ? » Vous devez savoir si un changement est encore possible et sur quels critères.", instructions: "Formulez une question qui ne suppose pas que la modification sera acceptée.", options: [], correctAnswer: null, acceptedAnswers: ["Pourriez-vous préciser si une modification demeure envisageable à ce stade et, le cas échéant, quels critères guideraient son examen ?", "Je souhaiterais savoir dans quelles conditions une modification pourrait encore être étudiée et quelle procédure conviendrait de suivre."], explanation: "La question demande une possibilité, des critères et une procédure sans présenter le changement comme un droit acquis.", targetLanguageFeature: "question conditionnelle et non présupposée", tags: ["questions", "transform", "variant"] },
    ],
    [
      { subSkill: "context-question-decision-order", prompt: "Vous avez reçu une réponse qui confirme un principe mais ne précise pas ses effets sur votre calendrier.", instructions: "Organisez votre demande de clarification.", options: ["Cette confirmation nous permet de poursuivre la préparation, mais nous devons encore savoir si elle autorise le lancement avant la validation finale.", "Votre message du 12 mai confirme que le principe du projet est retenu.", "Pourriez-vous nous indiquer quelle étape doit encore être franchie et selon quel calendrier ?"], correctAnswer: ["Votre message du 12 mai confirme que le principe du projet est retenu.", "Cette confirmation nous permet de poursuivre la préparation, mais nous devons encore savoir si elle autorise le lancement avant la validation finale.", "Pourriez-vous nous indiquer quelle étape doit encore être franchie et selon quel calendrier ?"], acceptedAnswers: [], explanation: "La demande part d'un point établi, explique précisément ce qui reste incertain, puis formule les informations nécessaires.", targetLanguageFeature: "acquis → incertitude → question ciblée", tags: ["questions", "organization", "reasoning"] },
      { subSkill: "context-question-decision-order-alternative", prompt: "Vous préparez une inscription pour un groupe, mais une règle de priorité peut affecter certaines personnes.", instructions: "Mettez les éléments dans l'ordre le plus clair.", options: ["Avant de confirmer les inscriptions, nous devons déterminer si certains participants relèvent de cette priorité.", "Votre règlement indique que l'accès peut dépendre de critères de priorité.", "Pourriez-vous préciser quels justificatifs seraient nécessaires et à quel moment ils devraient être transmis ?"], correctAnswer: ["Votre règlement indique que l'accès peut dépendre de critères de priorité.", "Avant de confirmer les inscriptions, nous devons déterminer si certains participants relèvent de cette priorité.", "Pourriez-vous préciser quels justificatifs seraient nécessaires et à quel moment ils devraient être transmis ?"], acceptedAnswers: [], explanation: "L'ordre fait apparaître la règle, l'enjeu concret, puis la demande de procédure et de calendrier.", targetLanguageFeature: "règle → enjeu → procédure", tags: ["questions", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-multi-criteria-inquiry", prompt: "Vous souhaitez intégrer un programme pilote pour lequel les places sont limitées. Vous devez comprendre la sélection, les engagements demandés et la possibilité de vous retirer si votre situation évolue.", instructions: "Rédigez 3 ou 4 questions organisées : distinguez les critères de sélection, les engagements et les conditions de retrait.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Au C2, des questions multiples sont regroupées par fonction et rendent visible ce qui est nécessaire à une décision éclairée.", targetLanguageFeature: "questionnement structuré par critères", tags: ["questions", "development", "decision"], selfCheck: ["Chaque question correspond à un critère de décision distinct.", "Je ne présuppose pas que ma candidature ou mon retrait sera accepté.", "Les questions suivent un ordre qui aide le destinataire à répondre."] },
      { subSkill: "guided-multi-criteria-inquiry-alternative", prompt: "Vous envisagez de confier une mission à un prestataire, mais son offre ne précise ni les livrables, ni la responsabilité en cas de retard, ni les conditions de modification.", instructions: "Rédigez 3 ou 4 questions ciblées qui permettraient de lever ces incertitudes avant un accord.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le développement C2 identifie les zones qui structurent un engagement, au lieu de demander simplement davantage de détails.", targetLanguageFeature: "questions de cadrage contractuel", tags: ["questions", "development", "variant"], selfCheck: ["Mes questions distinguent livrables, responsabilités et modifications.", "Leur formulation reste factuelle et non accusatrice.", "Elles permettent d'obtenir une réponse utilisable avant de s'engager."] },
    ],
    [
      { subSkill: "independent-due-diligence-inquiry", prompt: "Vous écrivez à une administration avant d'orienter un groupe d'usagers vers un nouveau dispositif. Les conditions d'accès, le traitement des données et les possibilités de recours doivent être clairs.", instructions: "Rédigez 90 à 110 mots : situez votre démarche, posez des questions structurées sur ces trois points et indiquez pourquoi ces réponses sont nécessaires avant votre orientation.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une demande C2 autonomise la décision sans transférer au destinataire une inquiétude vague ou disproportionnée.", targetLanguageFeature: "questionnement autonome de vérification", tags: ["questions", "production", "institutional"], selfCheck: ["Je distingue les conditions d'accès, les données et les recours.", "Chaque question est précise et ne suppose pas une réponse favorable.", "Je relie ces informations à la responsabilité de l'orientation envisagée."] },
      { subSkill: "independent-due-diligence-inquiry-alternative", prompt: "Vous écrivez à un organisme partenaire avant de signer un accord de coopération. Vous devez préciser la gouvernance, les modalités de suivi et ce qui se passe en cas de désaccord.", instructions: "Rédigez 90 à 110 mots : organisez des questions ciblées et expliquez en une phrase pourquoi elles sont nécessaires pour sécuriser une collaboration durable.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production C2 vérifie les mécanismes d'une relation sans traiter le partenaire comme s'il était de mauvaise foi.", targetLanguageFeature: "questionnement autonome de gouvernance", tags: ["questions", "production", "variant"], selfCheck: ["Les questions portent sur des mécanismes précis de collaboration.", "Le ton est rigoureux sans être suspicieux.", "Je montre le lien entre ces réponses et une coopération durable."] },
    ],
  ]),
  ...taskOneC2Path("t1-c2-making-requests", "making-requests", [
    [
      { subSkill: "firm-request-with-basis", prompt: "Vous demandez à un prestataire de corriger rapidement une erreur qui affecte un échéancier commun, mais vous souhaitez préserver la relation.", instructions: "Choisissez la demande la plus ferme et la plus coopérative.", options: ["Corrigez votre erreur aujourd'hui.", "Compte tenu de l'échéance commune, serait-il possible de corriger ce point avant demain midi et de nous confirmer la solution retenue afin que nous puissions ajuster notre propre calendrier ?", "Vous avez tout retardé.", "Faites ce qu'il faut au plus vite."], correctAnswer: "Compte tenu de l'échéance commune, serait-il possible de corriger ce point avant demain midi et de nous confirmer la solution retenue afin que nous puissions ajuster notre propre calendrier ?", acceptedAnswers: [], explanation: "La demande C2 donne son fondement, précise l'action et l'échéance, puis explique l'effet sans accuser le prestataire.", targetLanguageFeature: "demande ferme, fondée et coopérative", tags: ["requests", "recognize", "diplomacy"] },
      { subSkill: "firm-request-with-basis-alternative", prompt: "Vous demandez à une administration de réexaminer un dossier après avoir identifié une pièce qui n'a pas été prise en compte.", instructions: "Choisissez la formulation la plus adaptée.", options: ["Vous avez mal lu le dossier, recommencez.", "Au regard de la pièce transmise le 6 avril, qui ne semble pas figurer dans la décision, serait-il envisageable de réexaminer ce point avant la clôture de la procédure ?", "Je veux que vous changiez votre décision.", "Votre réponse n'est pas acceptable."], correctAnswer: "Au regard de la pièce transmise le 6 avril, qui ne semble pas figurer dans la décision, serait-il envisageable de réexaminer ce point avant la clôture de la procédure ?", acceptedAnswers: [], explanation: "La formulation appuie la demande sur une pièce traçable, limite son objet et respecte la procédure du destinataire.", targetLanguageFeature: "demande de réexamen étayée", tags: ["requests", "recognize", "variant"] },
    ],
    [
      { subSkill: "conditional-request-formula", prompt: "Vous demandez une exception limitée à un règlement pour éviter une conséquence disproportionnée.", instructions: "Complétez : « Au regard de cette situation particulière, serait-il ______ d'envisager une dérogation limitée à cette échéance ? »", options: [], correctAnswer: "envisageable", acceptedAnswers: ["possible", "possible, à titre exceptionnel"], explanation: "La formule demande l'examen d'une exception sans la présenter comme un droit automatique.", targetLanguageFeature: "demande conditionnelle d'exception", tags: ["requests", "complete", "condition"] },
      { subSkill: "conditional-request-formula-alternative", prompt: "Vous souhaitez qu'un partenaire adapte un format, sans pouvoir imposer cette modification.", instructions: "Complétez : « Si cela ne compromet pas vos contraintes techniques, pourriez-vous ______ le document dans un format accessible ? »", options: [], correctAnswer: "transmettre", acceptedAnswers: ["nous transmettre", "nous le faire parvenir"], explanation: "La condition reconnaît une contrainte possible et la demande conserve un objet concret.", targetLanguageFeature: "demande sous condition", tags: ["requests", "complete", "variant"] },
    ],
    [
      { subSkill: "directive-to-negotiated-request", prompt: "Reformulez : « Décalez votre décision d'une semaine. » Vous devez obtenir du temps pour compléter une consultation importante.", instructions: "Formulez une demande qui explicite l'enjeu, la durée limitée et une solution si le report ne peut être accordé.", options: [], correctAnswer: null, acceptedAnswers: ["Afin d'intégrer les derniers retours de la consultation, serait-il possible de différer votre décision d'une semaine ; si ce calendrier ne peut être modifié, nous pourrions vous transmettre une note intermédiaire avant l'échéance actuelle.", "Nous souhaiterions solliciter un report limité d'une semaine pour finaliser la consultation ; à défaut, pourriez-vous nous indiquer quels éléments devraient impérativement être fournis à la date prévue ?"], explanation: "Le C2 justifie la demande, en borne la portée et prépare une issue de repli au lieu de formuler un ordre.", targetLanguageFeature: "demande négociée avec solution de repli", tags: ["requests", "transform", "negotiation"] },
      { subSkill: "directive-to-negotiated-request-alternative", prompt: "Reformulez : « Retirez cette phrase du communiqué. » Vous pensez qu'elle peut être mal interprétée, mais le partenaire en est l'auteur.", instructions: "Demandez une modification sans contester l'autorité du partenaire sur le texte.", options: [], correctAnswer: null, acceptedAnswers: ["Afin d'éviter une interprétation qui ne correspondrait pas à l'accord conclu, accepteriez-vous d'examiner la possibilité de reformuler ce passage avant publication ?", "Ce passage pouvant prêter à confusion, nous souhaiterions vous proposer une reformulation et savoir si elle pourrait être intégrée au communiqué."], explanation: "La demande C2 cible l'effet du passage, respecte le rôle de l'auteur et propose une action déterminée.", targetLanguageFeature: "demande de correction diplomatique", tags: ["requests", "transform", "variant"] },
    ],
    [
      { subSkill: "impact-request-alternative-order", prompt: "Vous demandez à un partenaire de communiquer une information qui conditionne le travail de plusieurs équipes.", instructions: "Mettez les éléments dans l'ordre qui explique la demande sans la rendre impérative.", options: ["Serait-il possible de nous confirmer ce point avant jeudi, ou de nous signaler si un élément vous empêche de le faire dans ce délai ?", "Sans cette confirmation, les équipes ne peuvent pas arrêter leur planification.", "La version transmise ne précise pas si la mesure concerne également les sites pilotes."], correctAnswer: ["La version transmise ne précise pas si la mesure concerne également les sites pilotes.", "Sans cette confirmation, les équipes ne peuvent pas arrêter leur planification.", "Serait-il possible de nous confirmer ce point avant jeudi, ou de nous signaler si un élément vous empêche de le faire dans ce délai ?"], acceptedAnswers: [], explanation: "L'ordre expose le point manquant, son effet concret, puis une demande qui prévoit une réponse alternative.", targetLanguageFeature: "objet → impact → demande ajustable", tags: ["requests", "organization", "reasoning"] },
      { subSkill: "impact-request-alternative-order-alternative", prompt: "Vous demandez à une responsable de valider une option avant une échéance, mais une validation complète peut être difficile à obtenir si vite.", instructions: "Organisez le passage le plus réaliste.", options: ["À défaut d'une validation complète, un accord sur les principes permettrait déjà de préserver l'échéance.", "Le calendrier de mise en œuvre suppose de retenir une option avant le 20 juin.", "Serait-il possible de valider cette option avant cette date, ou d'indiquer les réserves qui devraient être levées ensuite ?"], correctAnswer: ["Le calendrier de mise en œuvre suppose de retenir une option avant le 20 juin.", "À défaut d'une validation complète, un accord sur les principes permettrait déjà de préserver l'échéance.", "Serait-il possible de valider cette option avant cette date, ou d'indiquer les réserves qui devraient être levées ensuite ?"], acceptedAnswers: [], explanation: "La clôture de la demande distingue ce qui est nécessaire maintenant de ce qui peut être traité ultérieurement.", targetLanguageFeature: "demande graduée", tags: ["requests", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-request-with-proportional-remedy", prompt: "Vous demandez à un partenaire de revoir un choix qui a des conséquences pour votre public, mais vous reconnaissez que ce choix répondait à une contrainte réelle.", instructions: "Rédigez 4 ou 5 phrases : reconnaissez la contrainte, expliquez l'effet concret, demandez un réexamen limité et proposez une option qui réduirait l'impact sans exiger un changement total.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une demande C2 peut rester ferme tout en cherchant un remède proportionné et praticable pour les deux parties.", targetLanguageFeature: "demande avec remède proportionné", tags: ["requests", "development", "diplomacy"], selfCheck: ["Je reconnais la contrainte sans abandonner la demande.", "L'effet sur le public est concret et proportionné.", "Je formule un réexamen limité ou une option de compromis praticable."] },
      { subSkill: "guided-request-with-proportional-remedy-alternative", prompt: "Vous demandez à un prestataire de reprendre une livraison incomplète alors que l'échéance approche et que son équipe est déjà mobilisée sur un autre projet.", instructions: "Rédigez 4 ou 5 phrases : décrivez l'écart, demandez une correction prioritaire, expliquez la conséquence et ouvrez une modalité réaliste de résolution.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le C2 rend l'urgence visible sans transformer la demande en reproche ou en injonction impossible.", targetLanguageFeature: "demande urgente et réaliste", tags: ["requests", "development", "variant"], selfCheck: ["L'écart et la correction attendue sont précisément formulés.", "J'explique l'urgence par une conséquence concrète.", "Je laisse une modalité de résolution compatible avec la contrainte du prestataire."] },
    ],
    [
      { subSkill: "independent-request-with-procedure", prompt: "Vous écrivez à une administration pour demander la révision d'une décision qui affecte un groupe d'usagers. Une procédure existe, mais le délai est presque expiré.", instructions: "Rédigez 90 à 110 mots : fondez votre demande sur un élément précis, expliquez pourquoi le délai est important, demandez une étape de procédure identifiable et gardez une position ferme mais non accusatrice.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production C2 associe la rigueur procédurale, l'urgence et le respect de l'institution au lieu d'opposer ces exigences.", targetLanguageFeature: "demande autonome dans un cadre procédural", tags: ["requests", "production", "institutional"], selfCheck: ["Je fonde la demande sur un élément traçable et limité.", "L'urgence est expliquée sans dramatisation.", "Je sollicite une étape de procédure ou une décision précise dans un ton ferme et respectueux."] },
      { subSkill: "independent-request-with-procedure-alternative", prompt: "Vous écrivez à un partenaire pour demander qu'un engagement soit formalisé avant de mobiliser vos équipes. Vous souhaitez éviter que cette demande soit interprétée comme un manque de confiance.", instructions: "Rédigez 90 à 110 mots : rappelez l'accord de principe, expliquez l'utilité de la formalisation, formulez une demande précise et proposez une manière simple de la satisfaire.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une demande C2 peut sécuriser une coopération sans mettre en doute la bonne foi du partenaire.", targetLanguageFeature: "demande autonome de formalisation", tags: ["requests", "production", "variant"], selfCheck: ["Je reconnais l'accord ou la relation existante.", "J'explique la formalisation comme un besoin opérationnel, non comme une suspicion.", "La demande et le moyen de la satisfaire sont précis et réalistes."] },
    ],
  ]),
  ...taskOneC2Path("t1-c2-register", "register", [
    [
      { subSkill: "diplomatic-firmness", prompt: "Vous écrivez à un partenaire qui a communiqué publiquement une information inexacte sur votre organisation. Vous devez demander une correction sans mettre en cause sa bonne foi.", instructions: "Choisissez la formulation la plus précise et diplomatique.", options: ["Votre communiqué est faux, corrigez-le immédiatement.", "Je me permets d'attirer votre attention sur un élément du communiqué qui pourrait prêter à confusion concernant notre rôle ; afin d'éviter toute interprétation inexacte, accepteriez-vous d'envisager la formulation suivante ?", "Vous avez encore fait une erreur.", "Ce passage est inacceptable."], correctAnswer: "Je me permets d'attirer votre attention sur un élément du communiqué qui pourrait prêter à confusion concernant notre rôle ; afin d'éviter toute interprétation inexacte, accepteriez-vous d'envisager la formulation suivante ?", acceptedAnswers: [], explanation: "Le registre C2 cible l'effet du texte, ne prête pas d'intention et propose immédiatement une réparation concrète.", targetLanguageFeature: "fermeté diplomatique", tags: ["register", "recognize", "diplomacy"] },
      { subSkill: "diplomatic-firmness-alternative", prompt: "Vous écrivez à un média partenaire dont un article a simplifié à l'excès les résultats de votre étude.", instructions: "Choisissez la formulation qui demande une correction sans contester inutilement le travail du journaliste.", options: ["Votre article déforme totalement notre étude.", "Certaines formulations de l'article pourraient laisser entendre une conclusion plus générale que celle établie par l'étude ; accepteriez-vous d'ajouter la précision méthodologique ci-dessous afin d'en préserver la portée exacte ?", "Vous n'avez rien compris à notre étude.", "Publiez notre texte à la place."], correctAnswer: "Certaines formulations de l'article pourraient laisser entendre une conclusion plus générale que celle établie par l'étude ; accepteriez-vous d'ajouter la précision méthodologique ci-dessous afin d'en préserver la portée exacte ?", acceptedAnswers: [], explanation: "Le message cible la portée du texte et propose une correction vérifiable, sans attaquer son auteur.", targetLanguageFeature: "correction précise et non défensive", tags: ["register", "recognize", "variant"] },
    ],
    [
      { subSkill: "precise-reservation", prompt: "Vous répondez à un fournisseur qui vous demande d'approuver une modification de contrat dans un délai très court.", instructions: "Complétez : « Je peux comprendre la nécessité d'une décision rapide ; ______, je ne serais pas en mesure de valider cette modification sans avoir examiné ses incidences. »", options: [], correctAnswer: "toutefois", acceptedAnswers: ["néanmoins", "pour autant"], explanation: "La réserve C2 reconnaît l'enjeu de l'autre partie tout en fixant une limite claire et justifiée.", targetLanguageFeature: "limite ferme et justifiée", tags: ["register", "complete", "concession"] },
      { subSkill: "precise-reservation-alternative", prompt: "Vous répondez à une proposition qui vous semble prématurée.", instructions: "Complétez : « La solution envisagée présente des avantages ; ______, il nous paraît nécessaire d'en mesurer les effets pour les usagers avant de l'adopter. »", options: [], correctAnswer: "pour autant", acceptedAnswers: ["toutefois", "néanmoins"], explanation: "La concession est réelle, mais elle ne transforme pas l'avantage reconnu en accord automatique.", targetLanguageFeature: "concession sans renoncement", tags: ["register", "complete", "variant"] },
    ],
    [
      { subSkill: "accusation-to-verifiable-reservation", prompt: "Reformulez : « Vous avez caché les coûts supplémentaires pour nous forcer à payer. »", instructions: "Exprimez une réserve ferme fondée sur un élément vérifiable et ouvrez une demande de clarification.", options: [], correctAnswer: null, acceptedAnswers: ["Les coûts supplémentaires mentionnés dans la dernière facture ne figuraient pas, sauf erreur de ma part, dans l'estimation initiale ; pourriez-vous nous préciser sur quel fondement ils ont été ajoutés ?", "Nous constatons un écart entre l'estimation transmise et la facture finale ; nous vous remercions de bien vouloir en détailler l'origine avant toute validation."], explanation: "La reformulation C2 retire l'attribution d'intention, conserve le désaccord et rend la vérification possible.", targetLanguageFeature: "réserve factuelle à forte portée", tags: ["register", "transform", "diplomacy"] },
      { subSkill: "accusation-to-verifiable-reservation-alternative", prompt: "Reformulez : « Vous avez ignoré nos remarques parce qu'elles vous dérangeaient. »", instructions: "Exprimez le problème à partir d'un écart observable et demandez une clarification sans prêter d'intention.", options: [], correctAnswer: null, acceptedAnswers: ["Les remarques que nous avons transmises le 12 juin ne semblent pas apparaître dans la version finale ; pourriez-vous nous indiquer comment elles ont été examinées ?", "Nous constatons que plusieurs points soulevés dans notre note du 12 juin n'ont pas été repris ; nous souhaiterions comprendre les critères qui ont conduit à cette version finale."], explanation: "Une réserve solide s'appuie sur un document et une date, puis demande un éclaircissement au lieu d'interpréter les intentions.", targetLanguageFeature: "désaccord fondé sur des traces", tags: ["register", "transform", "variant"] },
    ],
    [
      { subSkill: "relationship-protected-boundary-order", prompt: "Vous devez refuser une demande urgente d'un partenaire parce qu'elle engagerait votre organisation au-delà de ce qui a été convenu.", instructions: "Mettez les phrases dans l'ordre qui protège la relation tout en posant une limite nette.", options: ["Nous ne pourrons donc pas nous engager sur ce point avant validation interne, mais nous pouvons vous proposer un calendrier de décision précis.", "Je mesure l'importance que cette échéance revêt pour votre équipe.", "La demande reçue implique toutefois une extension du périmètre initialement validé."], correctAnswer: ["Je mesure l'importance que cette échéance revêt pour votre équipe.", "La demande reçue implique toutefois une extension du périmètre initialement validé.", "Nous ne pourrons donc pas nous engager sur ce point avant validation interne, mais nous pouvons vous proposer un calendrier de décision précis."], acceptedAnswers: [], explanation: "L'ordre reconnaît l'enjeu, explique objectivement la limite, puis formule une issue sans laisser croire à un accord implicite.", targetLanguageFeature: "reconnaissance → limite → solution", tags: ["register", "organization", "boundary"] },
      { subSkill: "relationship-protected-boundary-order-alternative", prompt: "Un partenaire vous demande de communiquer des données qui ne peuvent pas encore être diffusées.", instructions: "Organisez ce refus de manière claire, responsable et coopérative.", options: ["Nous ne pouvons donc pas les transmettre avant la validation prévue, mais nous pourrons vous communiquer les éléments autorisés dès cette étape franchie.", "Je comprends que ces données soient importantes pour la préparation de votre réunion.", "À ce stade, plusieurs des données demandées sont encore soumises à une procédure de validation."], correctAnswer: ["Je comprends que ces données soient importantes pour la préparation de votre réunion.", "À ce stade, plusieurs des données demandées sont encore soumises à une procédure de validation.", "Nous ne pouvons donc pas les transmettre avant la validation prévue, mais nous pourrons vous communiquer les éléments autorisés dès cette étape franchie."], acceptedAnswers: [], explanation: "Le message reconnaît l'intérêt du partenaire, explique une limite non négociable, puis propose une information fiable sur la suite.", targetLanguageFeature: "refus responsable avec alternative", tags: ["register", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-sensitive-register", prompt: "Un partenaire vous reproche publiquement un retard dont la responsabilité est partagée. Vous souhaitez rectifier les faits sans répondre sur le même ton ni dégrader la collaboration.", instructions: "Rédigez 4 ou 5 phrases : reconnaissez la difficulté, apportez une précision factuelle, délimitez ce que vous acceptez de prendre en charge et proposez un échange ou une suite concrète.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le registre C2 est capable de corriger le récit sans se justifier de manière défensive ni laisser une accusation imprécise s'installer.", targetLanguageFeature: "correction diplomatique d'un reproche", tags: ["register", "development", "diplomacy"], selfCheck: ["Je reconnais l'enjeu ou la difficulté sans accepter une responsabilité indéfinie.", "La précision apportée est factuelle et vérifiable.", "Je pose une limite claire tout en proposant une suite constructive."] },
      { subSkill: "guided-sensitive-register-alternative", prompt: "Vous devez informer un partenaire que son logo ne pourra pas apparaître aussi visiblement que prévu sur un support commun, en raison de règles de financement récemment clarifiées.", instructions: "Rédigez 4 ou 5 phrases : expliquez la contrainte sans vous défausser, reconnaissez l'importance du partenariat et proposez une alternative de visibilité proportionnée.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le registre C2 porte une déception réelle tout en évitant le flou, l'excuse excessive et la promesse impraticable.", targetLanguageFeature: "annonce diplomatique d'une contrainte", tags: ["register", "development", "variant"], selfCheck: ["La contrainte est expliquée de manière claire et assumée.", "Je reconnais l'enjeu pour le partenaire sans promettre l'impossible.", "Je propose une alternative concrète et proportionnée."] },
    ],
    [
      { subSkill: "independent-institutional-diplomacy", prompt: "Vous écrivez à une administration partenaire qui a annoncé une décision affectant votre public sans vous consulter. Vous devez demander une révision de la procédure tout en préservant la possibilité de travailler avec elle.", instructions: "Rédigez 90 à 110 mots : décrivez l'effet de la décision, formulez votre réserve avec une portée exacte, demandez une étape de concertation et maintenez un registre institutionnel ferme et ouvert.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production C2 doit tenir ensemble le désaccord, la relation institutionnelle et une demande de procédure praticable.", targetLanguageFeature: "registre institutionnel diplomatique", tags: ["register", "production", "institutional"], selfCheck: ["Je décris l'effet de la décision sans attribuer d'intention.", "Ma réserve est précise et ne se réduit pas à un jugement général.", "Je demande une concertation ou une procédure concrète, dans un ton ferme et ouvert."] },
      { subSkill: "independent-institutional-diplomacy-alternative", prompt: "Vous écrivez à un prestataire dont une livraison incomplète met en difficulté un projet commun. Vous avez besoin d'un correctif rapide, mais la relation doit être préservée car vous dépendrez encore de lui.", instructions: "Rédigez 90 à 110 mots : décrivez l'écart, demandez une action et une échéance, précisez la conséquence sans dramatiser et gardez un registre ferme, fiable et coopératif.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une production C2 peut exiger une correction rapide sans sacrifier une relation de travail nécessaire.", targetLanguageFeature: "fermeté coopérative à fort enjeu", tags: ["register", "production", "variant"], selfCheck: ["L'écart et l'action attendue sont formulés précisément.", "J'indique une conséquence réelle sans jugement excessif.", "Le ton permet de poursuivre la relation tout en rendant l'urgence lisible."] },
    ],
  ]),
  ...taskOneC2Path("t1-c2-closing-message", "closing-message", [
    [
      { subSkill: "conditional-commitment-closing", prompt: "Vous terminez un message à un partenaire après avoir convenu d'un principe de collaboration, mais un point juridique doit encore être validé.", instructions: "Choisissez la conclusion qui confirme l'accord sans présenter comme acquis ce qui reste à valider.", options: ["C'est réglé, nous commencerons lundi.", "Sous réserve de la validation juridique attendue, nous pourrons engager la phase préparatoire dès réception de votre accord ; je vous proposerai alors un calendrier détaillé.", "On commence dès que possible.", "Merci, à bientôt."], correctAnswer: "Sous réserve de la validation juridique attendue, nous pourrons engager la phase préparatoire dès réception de votre accord ; je vous proposerai alors un calendrier détaillé.", acceptedAnswers: [], explanation: "La clôture C2 distingue l'accord de principe, la condition restante et l'engagement qui suivra, sans créer d'ambiguïté.", targetLanguageFeature: "engagement conditionnel précis", tags: ["closing", "recognize", "commitment"] },
      { subSkill: "conditional-commitment-closing-alternative", prompt: "Vous terminez un échange avec un partenaire qui accepte le principe d'une adaptation, mais doit encore vérifier ses moyens.", instructions: "Choisissez la conclusion la plus exacte.", options: ["Parfait, l'adaptation est donc confirmée.", "Si votre vérification confirme la disponibilité des moyens nécessaires, nous pourrons arrêter ensemble les modalités d'application et en informer les équipes.", "Merci de nous dire quand vous commencerez.", "Nous allons appliquer l'adaptation dès demain."], correctAnswer: "Si votre vérification confirme la disponibilité des moyens nécessaires, nous pourrons arrêter ensemble les modalités d'application et en informer les équipes.", acceptedAnswers: [], explanation: "La formulation ne transforme pas une intention en engagement définitif et précise le chemin vers la décision.", targetLanguageFeature: "condition et prochaine étape", tags: ["closing", "recognize", "variant"] },
    ],
    [
      { subSkill: "conditional-deadline", prompt: "Vous terminez un échange avec une collectivité qui doit vous transmettre une version validée d'un document.", instructions: "Complétez : « Dès réception de la version validée, nous pourrons finaliser la mise en page ; ______, pourriez-vous nous indiquer si ce retour peut intervenir avant le 15 septembre ? »", options: [], correctAnswer: "dans cette perspective", acceptedAnswers: ["à cette fin", "d'ici là"], explanation: "La formule relie l'échéance à une étape précise du travail plutôt qu'à une pression indifférenciée.", targetLanguageFeature: "échéance liée à une condition", tags: ["closing", "complete", "deadline"] },
      { subSkill: "conditional-deadline-alternative", prompt: "Vous attendez un arbitrage avant de pouvoir informer des usagers.", instructions: "Complétez : « Une fois cet arbitrage rendu, nous pourrons communiquer une information fiable ; ______, seriez-vous en mesure de nous préciser le calendrier prévisionnel de votre décision ? »", options: [], correctAnswer: "dans l'intervalle", acceptedAnswers: ["d'ici là", "à ce stade"], explanation: "La demande de calendrier est justifiée par la dépendance entre deux étapes et ne se limite pas à réclamer une réponse rapide.", targetLanguageFeature: "calendrier dépendant d'une décision", tags: ["closing", "complete", "variant"] },
    ],
    [
      { subSkill: "abrupt-to-conditional-closing", prompt: "Reformulez : « Confirmez que vous acceptez, on lancera le projet. » L'accord dépend encore d'une validation interne du partenaire.", instructions: "Rédigez une clôture qui conditionne correctement la suite et respecte sa procédure.", options: [], correctAnswer: null, acceptedAnswers: ["Sous réserve de votre validation interne, pourriez-vous nous confirmer si le principe du projet est retenu ? Nous pourrions alors convenir ensemble du calendrier de lancement.", "Lorsque votre procédure interne aura abouti, nous vous serions reconnaissants de nous indiquer votre décision afin d'arrêter, si elle est favorable, les prochaines étapes."], explanation: "La clôture C2 ne force pas un accord et rend lisible l'enchaînement entre la décision attendue et l'action future.", targetLanguageFeature: "engagement conditionnel", tags: ["closing", "transform", "commitment"] },
      { subSkill: "abrupt-to-conditional-closing-alternative", prompt: "Reformulez : « Envoyez les documents jeudi, sinon on sera bloqués. » Les documents doivent d'abord être vérifiés par le partenaire.", instructions: "Gardez l'enjeu de calendrier, mais formulez une conclusion qui reconnaît la vérification nécessaire et prévoit une information en cas de retard.", options: [], correctAnswer: null, acceptedAnswers: ["Afin de préserver le calendrier, pourriez-vous nous transmettre les documents jeudi si votre vérification le permet, ou nous indiquer dès que possible le délai dont vous auriez besoin ?", "Sous réserve de votre contrôle final, nous vous serions reconnaissants de nous faire parvenir les documents jeudi ; si cette échéance ne peut être tenue, un retour sur le délai prévisible nous permettrait de nous organiser."], explanation: "Le C2 formule une échéance utile tout en distinguant la condition légitime et la nécessité d'être informé.", targetLanguageFeature: "échéance souple et actionnable", tags: ["closing", "transform", "variant"] },
    ],
    [
      { subSkill: "summary-condition-action-order", prompt: "Vous terminez un message après avoir proposé une adaptation dont le partenaire doit mesurer les incidences juridiques.", instructions: "Mettez les éléments dans l'ordre d'une clôture précise.", options: ["Sous réserve de cette vérification, nous pourrions ensuite formaliser l'adaptation et informer les équipes concernées.", "Vous avez indiqué devoir examiner les incidences juridiques de cette option.", "Nous vous remercions de nous faire savoir si ce point peut être validé avant le 20 juin, ou de nous préciser le délai nécessaire."], correctAnswer: ["Vous avez indiqué devoir examiner les incidences juridiques de cette option.", "Nous vous remercions de nous faire savoir si ce point peut être validé avant le 20 juin, ou de nous préciser le délai nécessaire.", "Sous réserve de cette vérification, nous pourrions ensuite formaliser l'adaptation et informer les équipes concernées."], acceptedAnswers: [], explanation: "La clôture rappelle la condition, demande un repère réaliste, puis situe clairement ce qui dépendra de la réponse.", targetLanguageFeature: "condition → calendrier → suite", tags: ["closing", "organization", "commitment"] },
      { subSkill: "summary-condition-action-order-alternative", prompt: "Vous terminez un échange avec un partenaire qui a accepté d'examiner une demande de modification de calendrier.", instructions: "Organisez la clôture de manière à ne pas confondre examen, accord et mise en œuvre.", options: ["Si cette modification est retenue, nous pourrons mettre à jour les engagements de chaque équipe.", "Nous vous remercions de nous indiquer, après examen, si cette modification peut être acceptée et à quelles conditions.", "Vous avez accepté d'examiner l'incidence du nouveau calendrier sur vos propres engagements."], correctAnswer: ["Vous avez accepté d'examiner l'incidence du nouveau calendrier sur vos propres engagements.", "Nous vous remercions de nous indiquer, après examen, si cette modification peut être acceptée et à quelles conditions.", "Si cette modification est retenue, nous pourrons mettre à jour les engagements de chaque équipe."], acceptedAnswers: [], explanation: "La progression préserve les statuts distincts : examen en cours, décision attendue, puis action éventuelle.", targetLanguageFeature: "statuts décisionnels distincts", tags: ["closing", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-high-stakes-closing", prompt: "Vous terminez un message à un financeur après avoir demandé une adaptation du projet. La réponse est nécessaire avant une date, mais le financeur doit d'abord vérifier qu'elle reste compatible avec la convention.", instructions: "Rédigez 3 ou 4 phrases : récapitulez l'objet de la décision, formulez l'échéance sans la rendre impérative, reconnaissez la vérification nécessaire et précisez la suite selon la réponse.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La clôture C2 rend une décision possible en distinguant ce qui doit être vérifié, le délai utile et les conséquences de chaque option.", targetLanguageFeature: "clôture à décision conditionnelle", tags: ["closing", "development", "institutional"], selfCheck: ["Je distingue clairement la demande, la vérification et la décision attendue.", "L'échéance est justifiée par une étape concrète du projet.", "Je précise une suite réaliste sans présenter l'accord comme acquis."] },
      { subSkill: "guided-high-stakes-closing-alternative", prompt: "Vous terminez un message à un partenaire après avoir signalé un écart dans une livraison. Une correction est nécessaire, mais sa date dépend de la disponibilité de ses équipes.", instructions: "Rédigez 3 ou 4 phrases : rappelez l'action attendue, demandez un calendrier ou une information en cas de difficulté, puis indiquez ce que votre équipe pourra faire dès réception de sa réponse.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Le C2 ferme une demande exigeante en la rendant praticable pour le destinataire et prévisible pour toutes les équipes.", targetLanguageFeature: "clôture de suivi coopératif", tags: ["closing", "development", "variant"], selfCheck: ["L'action attendue et son objet sont précis.", "Je prévois une réponse utile si l'échéance initiale ne peut être tenue.", "La suite de mon équipe dépend clairement de l'information reçue."] },
    ],
    [
      { subSkill: "independent-governance-closing", prompt: "Vous terminez un message à une administration partenaire après avoir demandé une concertation sur une décision qui affecte votre public. Vous devez proposer un calendrier de réponse sans mettre en cause son autorité de décision.", instructions: "Rédigez 90 à 110 mots : résumez exactement l'objet de la concertation, demandez un repère de calendrier ou une modalité d'échange, indiquez ce que vous ferez selon la réponse et concluez dans un registre institutionnel mesuré.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La production C2 clôt une demande sensible en rendant la procédure, les rôles et les étapes futures explicites.", targetLanguageFeature: "clôture autonome de concertation", tags: ["closing", "production", "institutional"], selfCheck: ["Je résume l'objet limité de la concertation sans répéter tout le message.", "Je demande un calendrier ou une modalité d'échange concrète et proportionnée.", "Je respecte l'autorité du destinataire tout en rendant la suite nécessaire et lisible."] },
      { subSkill: "independent-governance-closing-alternative", prompt: "Vous terminez un échange avec un partenaire financier après avoir proposé une modification limitée de programme. Vous devez conserver une trace claire de ce qui doit être validé avant toute mise en œuvre.", instructions: "Rédigez 90 à 110 mots : récapitulez la validation attendue, distinguez les conditions restantes, proposez un échéancier réaliste et indiquez l'action qui suivra un accord.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une clôture C2 protège la coopération en distinguant avec précision l'intention, la validation et l'exécution.", targetLanguageFeature: "clôture autonome de validation", tags: ["closing", "production", "variant"], selfCheck: ["Je sépare explicitement ce qui est proposé de ce qui reste à valider.", "L'échéancier demandé est lié à une action concrète.", "Je formule l'action future comme conditionnelle à l'accord."] },
    ],
  ]),
];
