import type { PracticeExercise } from "./practice-curriculum";

/**
 * Fixed, editor-reviewed Task 3 C1 data, authored in its own module to avoid
 * touching practice-curriculum.ts while other agents edit it concurrently.
 * The helper only attaches the deterministic six-stage metadata; all
 * learning content is static below. justifying-position and
 * counterarguments already ship from practice-curriculum.ts directly.
 */
type AuthoredVariant = Omit<
  PracticeExercise,
  "id" | "task" | "level" | "skill" | "exerciseType" | "difficulty" | "sequenceOrder" | "prerequisiteExerciseId"
>;

const STAGES: readonly PracticeExercise["exerciseType"][] = [
  "recognize",
  "complete",
  "transform",
  "organize",
  "develop",
  "produce",
];

const taskThreeC1Path = (
  prefix: string,
  skill: string,
  stages: readonly (readonly [AuthoredVariant, AuthoredVariant])[],
): readonly PracticeExercise[] =>
  stages.flatMap(([primary, alternative], index) => {
    const sequenceOrder = (index + 1) as 1 | 2 | 3 | 4 | 5 | 6;
    const shared = {
      task: "TASK_3" as const,
      level: "C1" as const,
      skill,
      exerciseType: STAGES[index]!,
      difficulty: sequenceOrder,
      sequenceOrder,
      prerequisiteExerciseId: index === 0 ? null : `${prefix}-${index}`,
    };
    return [
      { id: `${prefix}-${sequenceOrder}`, ...shared, ...primary },
      { id: `${prefix}-a${sequenceOrder}`, ...shared, ...alternative },
    ];
  });

export const TASK_3_C1_EXERCISES: readonly PracticeExercise[] = [
  ...taskThreeC1Path("t3-c1-introducing-topic", "introducing-topic", [
    [
      { subSkill: "problematize-tension", prompt: "Deux documents portent sur l'instauration d'un jour de télétravail obligatoire : l'un souligne les gains de productivité, l'autre les risques pour la cohésion d'équipe.", instructions: "Choisissez la phrase qui pose une véritable problématique, plutôt que de seulement présenter le thème.", options: ["Le télétravail est de plus en plus répandu dans les entreprises.", "La question se pose de savoir si un jour de télétravail imposé peut renforcer l'efficacité individuelle sans fragiliser le collectif.", "Le télétravail obligatoire divise les salariés.", "Il existe plusieurs avis sur le télétravail."], correctAnswer: "La question se pose de savoir si un jour de télétravail imposé peut renforcer l'efficacité individuelle sans fragiliser le collectif.", acceptedAnswers: [], explanation: "Cette phrase formule une véritable problématique : elle met en tension deux enjeux identifiés par les sources, plutôt que d'annoncer un thème ou une opposition brute.", targetLanguageFeature: "problématique articulée en tension", tags: ["introduction", "synthesis", "recognize"] },
      { subSkill: "problematize-tension-alternative", prompt: "Deux documents portent sur l'encadrement de l'intelligence artificielle dans le recrutement : l'un souligne les gains d'efficacité, l'autre les risques de biais.", instructions: "Choisissez la phrase qui pose une véritable problématique.", options: ["L'intelligence artificielle est utilisée dans le recrutement.", "La question se pose de savoir si l'automatisation du tri des candidatures peut gagner en efficacité sans reproduire les biais qu'elle prétend corriger.", "L'IA dans le recrutement fait débat.", "Plusieurs entreprises utilisent l'IA."], correctAnswer: "La question se pose de savoir si l'automatisation du tri des candidatures peut gagner en efficacité sans reproduire les biais qu'elle prétend corriger.", acceptedAnswers: [], explanation: "La phrase met en tension deux enjeux réels, au lieu de simplement constater l'usage de l'IA.", targetLanguageFeature: "problématique articulée en tension", tags: ["introduction", "recognize", "variant"] },
    ],
    [
      { subSkill: "problematizing-verb", prompt: "Vous formulez la problématique du débat sur le télétravail imposé.", instructions: "Complétez : « La question ______ de savoir si un jour de télétravail obligatoire peut concilier efficacité individuelle et cohésion d'équipe. »", options: [], correctAnswer: "se pose", acceptedAnswers: ["se trouve posée"], explanation: "Cette formule introduit une problématique ouverte, sans trancher d'avance.", targetLanguageFeature: "formulation d'une problématique", tags: ["introduction", "complete", "question"] },
      { subSkill: "problematizing-verb-alternative", prompt: "Vous formulez la problématique du débat sur l'IA dans le recrutement.", instructions: "Complétez : « La question ______ de savoir si l'automatisation du recrutement peut gagner en efficacité sans reproduire des biais. »", options: [], correctAnswer: "se pose", acceptedAnswers: ["se trouve posée"], explanation: "La même formule reste utile pour introduire une problématique ouverte.", targetLanguageFeature: "formulation d'une problématique", tags: ["introduction", "complete", "variant"] },
    ],
    [
      { subSkill: "opinion-to-problematic", prompt: "Transformez cette présentation neutre mais plate en une véritable problématique : « Le télétravail obligatoire a des avantages et des inconvénients. »", instructions: "Reformulez pour poser une problématique qui met les enjeux en tension.", options: [], correctAnswer: null, acceptedAnswers: ["La question est de savoir si un jour de télétravail imposé peut réellement améliorer l'efficacité sans nuire à la cohésion des équipes.", "Un jour de télétravail obligatoire peut-il gagner en efficacité ce qu'il risque de perdre en esprit d'équipe ?"], explanation: "La problématique nomme explicitement la tension entre les deux enjeux, plutôt que de juxtaposer des avantages et des inconvénients.", targetLanguageFeature: "passage d'un constat plat à une problématique", tags: ["introduction", "transform", "neutrality"] },
      { subSkill: "opinion-to-problematic-alternative", prompt: "Transformez : « L'IA dans le recrutement a des avantages et des inconvénients. »", instructions: "Reformulez pour poser une problématique qui met les enjeux en tension.", options: [], correctAnswer: null, acceptedAnswers: ["La question est de savoir si l'automatisation du recrutement peut réellement gagner en efficacité sans reproduire les biais qu'elle prétend éliminer.", "L'IA dans le recrutement peut-elle gagner en objectivité ce qu'elle risque de perdre en discernement humain ?"], explanation: "La problématique met en tension deux enjeux précis plutôt que de les juxtaposer.", targetLanguageFeature: "passage d'un constat plat à une problématique", tags: ["introduction", "transform", "variant"] },
    ],
    [
      { subSkill: "problematic-intro-order", prompt: "Vous construisez une introduction qui pose une problématique sur le télétravail imposé.", instructions: "Remettez ces éléments dans l'ordre.", options: ["Le télétravail imposé un jour par semaine se généralise dans de nombreuses entreprises.", "La question est de savoir si cette mesure améliore réellement l'efficacité sans fragiliser la cohésion des équipes.", "C'est ce que les deux documents permettent d'examiner."], correctAnswer: ["Le télétravail imposé un jour par semaine se généralise dans de nombreuses entreprises.", "La question est de savoir si cette mesure améliore réellement l'efficacité sans fragiliser la cohésion des équipes.", "C'est ce que les deux documents permettent d'examiner."], acceptedAnswers: [], explanation: "L'introduction va du constat général à la problématique précise, puis annonce l'analyse des sources.", targetLanguageFeature: "constat → problématique → annonce", tags: ["introduction", "organization", "synthesis"] },
      { subSkill: "problematic-intro-order-alternative", prompt: "Vous construisez une introduction qui pose une problématique sur l'IA dans le recrutement.", instructions: "Remettez ces éléments dans l'ordre.", options: ["L'IA occupe une place croissante dans les processus de recrutement.", "La question est de savoir si cette automatisation gagne en efficacité sans reproduire les biais qu'elle prétend corriger.", "C'est ce que les deux documents permettent d'examiner."], correctAnswer: ["L'IA occupe une place croissante dans les processus de recrutement.", "La question est de savoir si cette automatisation gagne en efficacité sans reproduire les biais qu'elle prétend corriger.", "C'est ce que les deux documents permettent d'examiner."], acceptedAnswers: [], explanation: "Même structure : constat, puis problématique, puis annonce de l'analyse.", targetLanguageFeature: "constat → problématique → annonce", tags: ["introduction", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-problematic-intro", prompt: "Idée de départ : vous introduisez un débat sur l'instauration d'une taxe carbone aux frontières.", instructions: "Rédigez 2 à 3 phrases qui posent une véritable problématique (une tension, pas seulement un thème).", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La problématique doit exprimer une tension réelle entre deux enjeux, sans prise de position.", targetLanguageFeature: "problématique articulée", tags: ["introduction", "development"], selfCheck: ["La problématique formule une tension réelle, pas seulement un thème.", "La formulation reste neutre, sans prise de position.", "Le lien avec le débat des sources est clair."] },
      { subSkill: "guided-problematic-intro-alternative", prompt: "Idée de départ : vous introduisez un débat sur la limitation du temps d'écran des enfants à l'école.", instructions: "Rédigez 2 à 3 phrases qui posent une véritable problématique.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "La problématique doit exprimer une tension réelle, sans prise de position.", targetLanguageFeature: "problématique articulée", tags: ["introduction", "development", "variant"], selfCheck: ["La problématique formule une tension réelle, pas seulement un thème.", "La formulation reste neutre, sans prise de position.", "Le lien avec le débat des sources est clair."] },
    ],
    [
      { subSkill: "independent-problematic-intro", prompt: "Vous introduisez un débat sur l'obligation du service civique pour les jeunes.", instructions: "Rédigez 2 à 3 phrases qui posent une problématique claire, sans prise de position.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une introduction C1 réussie pose une problématique précise, en tension, avant toute analyse.", targetLanguageFeature: "problématique autonome", tags: ["introduction", "production"], selfCheck: ["La problématique formule une tension réelle.", "Aucune position personnelle n'apparaît encore.", "L'introduction annonce l'examen des sources."] },
      { subSkill: "independent-problematic-intro-alternative", prompt: "Vous introduisez un débat sur la suppression des notes à l'école primaire.", instructions: "Rédigez 2 à 3 phrases qui posent une problématique claire, sans prise de position.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une introduction C1 réussie pose une problématique précise, en tension, avant toute analyse.", targetLanguageFeature: "problématique autonome", tags: ["introduction", "production", "variant"], selfCheck: ["La problématique formule une tension réelle.", "Aucune position personnelle n'apparaît encore.", "L'introduction annonce l'examen des sources."] },
    ],
  ]),

  ...taskThreeC1Path("t3-c1-reformulating-sources", "reformulating-sources", [
    [
      { subSkill: "faithful-distinct-reformulation", prompt: "Deux sources s'opposent sur les écrans à l'école : la première affirme qu'ils réduisent la capacité d'attention ; la seconde soutient qu'ils favorisent le travail collaboratif.", instructions: "Choisissez la reformulation la plus fidèle, qui distingue clairement les deux points de vue.", options: ["Les écrans sont mauvais pour l'attention mais bons pour le travail en groupe.", "Selon la première source, les écrans nuiraient à la concentration, tandis que la seconde y voit un outil au service du travail collaboratif.", "Les deux sources pensent la même chose sur les écrans.", "Les écrans sont un sujet débattu."], correctAnswer: "Selon la première source, les écrans nuiraient à la concentration, tandis que la seconde y voit un outil au service du travail collaboratif.", acceptedAnswers: [], explanation: "Cette reformulation attribue chaque idée à sa source et reste fidèle à la nuance de chacune.", targetLanguageFeature: "reformulation fidèle et attribuée", tags: ["sources", "recognize"] },
      { subSkill: "faithful-distinct-reformulation-alternative", prompt: "Deux sources s'opposent sur les compléments alimentaires : la première signale des risques sanitaires mal contrôlés, la seconde met en avant des bénéfices nutritionnels validés par des études.", instructions: "Choisissez la reformulation la plus fidèle, qui distingue clairement les deux points de vue.", options: ["Les compléments alimentaires sont dangereux mais utiles.", "Selon la première source, ces produits présenteraient des risques insuffisamment encadrés, tandis que la seconde souligne des bénéfices confirmés par la recherche.", "Les deux sources pensent la même chose.", "Les compléments alimentaires sont un sujet débattu."], correctAnswer: "Selon la première source, ces produits présenteraient des risques insuffisamment encadrés, tandis que la seconde souligne des bénéfices confirmés par la recherche.", acceptedAnswers: [], explanation: "Chaque idée reste attribuée à sa source, sans confusion ni déformation.", targetLanguageFeature: "reformulation fidèle et attribuée", tags: ["sources", "recognize", "variant"] },
    ],
    [
      { subSkill: "attribution-verb", prompt: "Vous reformulez fidèlement deux points de vue opposés.", instructions: "Complétez : « Alors que la première source ______ un effet négatif sur l'attention, la seconde met en avant un bénéfice pour la coopération. »", options: [], correctAnswer: "pointe", acceptedAnswers: ["souligne", "dénonce"], explanation: "Ce verbe attribue clairement l'idée à la première source, sans la mêler à la seconde.", targetLanguageFeature: "verbe d'attribution", tags: ["sources", "complete"] },
      { subSkill: "attribution-verb-alternative", prompt: "Vous reformulez fidèlement deux points de vue opposés.", instructions: "Complétez : « Alors que la première source ______ des risques sanitaires, la seconde met en avant des bénéfices validés par la recherche. »", options: [], correctAnswer: "pointe", acceptedAnswers: ["souligne", "dénonce"], explanation: "Le même type de verbe d'attribution reste utile ici.", targetLanguageFeature: "verbe d'attribution", tags: ["sources", "complete", "variant"] },
    ],
    [
      { subSkill: "unmix-sources", prompt: "Reformulez fidèlement, en distinguant les deux sources, ce résumé qui les confond : « Les écrans à l'école, c'est compliqué, il y a du bon et du mauvais. »", instructions: "Réécrivez en attribuant clairement chaque idée à sa source.", options: [], correctAnswer: null, acceptedAnswers: ["La première source met en garde contre une baisse de concentration, tandis que la seconde souligne un potentiel pour le travail en équipe.", "D'un côté, une source signale un risque pour l'attention ; de l'autre, une seconde y voit un levier pour la collaboration."], explanation: "La reformulation distingue nettement les deux sources au lieu de les fondre en un jugement général.", targetLanguageFeature: "distinction des sources", tags: ["sources", "transform"] },
      { subSkill: "unmix-sources-alternative", prompt: "Reformulez fidèlement, en distinguant les deux sources, ce résumé qui les confond : « Les compléments alimentaires, c'est compliqué, il y a du bon et du mauvais. »", instructions: "Réécrivez en attribuant clairement chaque idée à sa source.", options: [], correctAnswer: null, acceptedAnswers: ["La première source met en garde contre des risques sanitaires insuffisamment encadrés, tandis que la seconde souligne des bénéfices reconnus par la recherche.", "D'un côté, une source alerte sur des risques mal maîtrisés ; de l'autre, une seconde souligne des bénéfices validés scientifiquement."], explanation: "La reformulation distingue nettement les deux sources.", targetLanguageFeature: "distinction des sources", tags: ["sources", "transform", "variant"] },
    ],
    [
      { subSkill: "distinct-reformulation-order", prompt: "Vous reformulez fidèlement deux sources sur le télétravail des enseignants.", instructions: "Remettez ces éléments dans l'ordre.", options: ["La première source estime que le télétravail des enseignants complique le suivi des élèves en difficulté.", "La seconde, à l'inverse, souligne le gain de temps qu'il permet pour la préparation des cours.", "Ces deux points de vue restent difficiles à concilier."], correctAnswer: ["La première source estime que le télétravail des enseignants complique le suivi des élèves en difficulté.", "La seconde, à l'inverse, souligne le gain de temps qu'il permet pour la préparation des cours.", "Ces deux points de vue restent difficiles à concilier."], acceptedAnswers: [], explanation: "Chaque source est présentée avant le constat final de tension entre les deux.", targetLanguageFeature: "organisation d'une reformulation distinguée", tags: ["sources", "organization"] },
      { subSkill: "distinct-reformulation-order-alternative", prompt: "Vous reformulez fidèlement deux sources sur la vidéosurveillance dans les lycées.", instructions: "Remettez ces éléments dans l'ordre.", options: ["La première source estime que la vidéosurveillance dans les lycées dissuade les incidents.", "La seconde, à l'inverse, souligne le climat de méfiance qu'elle peut installer.", "Ces deux points de vue restent difficiles à concilier."], correctAnswer: ["La première source estime que la vidéosurveillance dans les lycées dissuade les incidents.", "La seconde, à l'inverse, souligne le climat de méfiance qu'elle peut installer.", "Ces deux points de vue restent difficiles à concilier."], acceptedAnswers: [], explanation: "Même organisation : chaque source, puis le constat de tension.", targetLanguageFeature: "organisation d'une reformulation distinguée", tags: ["sources", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-distinct-reformulation", prompt: "Idée de départ : deux sources sur la suppression des devoirs à la maison, l'une soulignant un allègement de la charge mentale des élèves, l'autre un risque de creuser les inégalités entre familles.", instructions: "Rédigez 2 à 3 phrases qui reformulent fidèlement chaque source, en les distinguant clairement.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Chaque source doit rester identifiable et la reformulation ne doit pas déformer ses propos.", targetLanguageFeature: "reformulation fidèle et distinguée", tags: ["sources", "development"], selfCheck: ["Chaque source est clairement identifiée et distinguée.", "La reformulation reste fidèle, sans déformer les propos.", "Aucun jugement personnel ne s'ajoute aux deux points de vue."] },
      { subSkill: "guided-distinct-reformulation-alternative", prompt: "Idée de départ : deux sources sur la généralisation des menus végétariens dans les cantines, l'une soulignant un bénéfice environnemental, l'autre un risque de carences si mal encadré.", instructions: "Rédigez 2 à 3 phrases qui reformulent fidèlement chaque source, en les distinguant clairement.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Chaque source doit rester identifiable et la reformulation ne doit pas déformer ses propos.", targetLanguageFeature: "reformulation fidèle et distinguée", tags: ["sources", "development", "variant"], selfCheck: ["Chaque source est clairement identifiée et distinguée.", "La reformulation reste fidèle, sans déformer les propos.", "Aucun jugement personnel ne s'ajoute aux deux points de vue."] },
    ],
    [
      { subSkill: "independent-distinct-reformulation", prompt: "Vous reformulez fidèlement deux sources sur l'usage des drones de livraison en ville, l'une insistant sur le gain de temps, l'autre sur les nuisances sonores.", instructions: "Rédigez 2 à 3 phrases qui reformulent fidèlement chaque source, en les distinguant clairement.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une reformulation C1 réussie attribue chaque idée à sa source sans les mélanger.", targetLanguageFeature: "reformulation fidèle et distinguée, autonome", tags: ["sources", "production"], selfCheck: ["Chaque source est clairement identifiée.", "La reformulation reste fidèle à chaque propos.", "Aucun jugement personnel ne s'ajoute."] },
      { subSkill: "independent-distinct-reformulation-alternative", prompt: "Vous reformulez fidèlement deux sources sur l'usage obligatoire du casque à vélo en ville, l'une insistant sur la sécurité, l'autre sur la liberté individuelle réduite.", instructions: "Rédigez 2 à 3 phrases qui reformulent fidèlement chaque source, en les distinguant clairement.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une reformulation C1 réussie attribue chaque idée à sa source sans les mélanger.", targetLanguageFeature: "reformulation fidèle et distinguée, autonome", tags: ["sources", "production", "variant"], selfCheck: ["Chaque source est clairement identifiée.", "La reformulation reste fidèle à chaque propos.", "Aucun jugement personnel ne s'ajoute."] },
    ],
  ]),

  ...taskThreeC1Path("t3-c1-identifying-arguments", "identifying-arguments", [
    [
      { subSkill: "distinguish-argument-justification", prompt: "Dans un texte défendant la semaine de 4 jours à l'école, on trouve : « La semaine de 4 jours améliore la concentration des élèves, car elle réduit la fatigue accumulée en fin de semaine. »", instructions: "Choisissez la phrase qui identifie correctement l'argument et sa justification.", options: ["L'argument est que la semaine dure 4 jours.", "L'argument est que la concentration s'améliore ; la justification est la réduction de la fatigue en fin de semaine.", "La justification est que les élèves aiment avoir un jour de repos.", "L'argument et la justification sont la même chose ici."], correctAnswer: "L'argument est que la concentration s'améliore ; la justification est la réduction de la fatigue en fin de semaine.", acceptedAnswers: [], explanation: "L'argument est l'affirmation défendue ; la justification est la raison qui la soutient. Ici, elles sont distinctes.", targetLanguageFeature: "distinction argument / justification", tags: ["argumentation", "recognize"] },
      { subSkill: "distinguish-argument-justification-alternative", prompt: "Dans un texte défendant le revenu universel, on trouve : « Le revenu universel réduirait la précarité, car il garantit un socle financier indépendant de l'emploi. »", instructions: "Choisissez la phrase qui identifie correctement l'argument et sa justification.", options: ["L'argument est que le revenu universel existe.", "L'argument est une réduction de la précarité ; la justification est la garantie d'un socle financier indépendant de l'emploi.", "La justification est que tout le monde touche de l'argent.", "L'argument et la justification sont la même chose ici."], correctAnswer: "L'argument est une réduction de la précarité ; la justification est la garantie d'un socle financier indépendant de l'emploi.", acceptedAnswers: [], explanation: "L'argument (réduction de la précarité) reste distinct de sa justification (le socle garanti).", targetLanguageFeature: "distinction argument / justification", tags: ["argumentation", "recognize", "variant"] },
    ],
    [
      { subSkill: "justification-verb", prompt: "Vous distinguez un argument de sa justification.", instructions: "Complétez : « L'argument avancé est une amélioration de la concentration ; il ______ par la baisse de fatigue en fin de semaine. »", options: [], correctAnswer: "se justifie", acceptedAnswers: ["s'explique"], explanation: "Ce verbe relie explicitement l'argument à sa justification sans les confondre.", targetLanguageFeature: "verbe de mise en relation argument/justification", tags: ["argumentation", "complete"] },
      { subSkill: "justification-verb-alternative", prompt: "Vous distinguez un argument de sa justification.", instructions: "Complétez : « L'argument avancé est une réduction de la précarité ; il ______ par la garantie d'un revenu indépendant de l'emploi. »", options: [], correctAnswer: "se justifie", acceptedAnswers: ["s'explique"], explanation: "Le même verbe relie ici l'argument à sa justification.", targetLanguageFeature: "verbe de mise en relation argument/justification", tags: ["argumentation", "complete", "variant"] },
    ],
    [
      { subSkill: "separate-argument-justification", prompt: "Ce passage mélange argument et justification sans les distinguer : « La semaine de 4 jours, c'est bien parce que les élèves sont moins fatigués et donc plus concentrés. »", instructions: "Réécrivez en séparant clairement l'argument (l'affirmation) de sa justification (la raison).", options: [], correctAnswer: null, acceptedAnswers: ["La semaine de 4 jours améliorerait la concentration des élèves ; cet effet s'expliquerait par une fatigue réduite en fin de semaine.", "L'argument central est celui d'une meilleure concentration, justifié par la diminution de la fatigue accumulée."], explanation: "La réécriture rend visible la structure argument puis justification, au lieu de les fondre en une seule affirmation.", targetLanguageFeature: "séparation argument / justification", tags: ["argumentation", "transform"] },
      { subSkill: "separate-argument-justification-alternative", prompt: "Ce passage mélange argument et justification : « Le revenu universel, c'est bien parce que les gens ont un filet de sécurité et donc moins de précarité. »", instructions: "Réécrivez en séparant clairement l'argument de sa justification.", options: [], correctAnswer: null, acceptedAnswers: ["Le revenu universel réduirait la précarité ; cet effet s'expliquerait par la garantie d'un socle financier indépendant de l'emploi.", "L'argument central est celui d'une précarité réduite, justifié par la garantie d'un revenu de base."], explanation: "La structure argument puis justification devient explicite.", targetLanguageFeature: "séparation argument / justification", tags: ["argumentation", "transform", "variant"] },
    ],
    [
      { subSkill: "argument-justification-order", prompt: "Vous distinguez argument et justification dans un texte sur le vote obligatoire.", instructions: "Remettez ces éléments dans l'ordre.", options: ["L'argument central est que le vote obligatoire renforcerait la légitimité des élus.", "Cette affirmation se justifie par une participation plus représentative de l'ensemble de la population.", "Ce lien entre argument et justification mérite d'être examiné avec attention."], correctAnswer: ["L'argument central est que le vote obligatoire renforcerait la légitimité des élus.", "Cette affirmation se justifie par une participation plus représentative de l'ensemble de la population.", "Ce lien entre argument et justification mérite d'être examiné avec attention."], acceptedAnswers: [], explanation: "L'argument est posé avant sa justification, puis vient un recul critique sur ce lien.", targetLanguageFeature: "organisation argument → justification", tags: ["argumentation", "organization"] },
      { subSkill: "argument-justification-order-alternative", prompt: "Vous distinguez argument et justification dans un texte sur l'allongement du congé parental.", instructions: "Remettez ces éléments dans l'ordre.", options: ["L'argument central est que l'allongement du congé parental favoriserait le développement de l'enfant.", "Cette affirmation se justifie par un temps de présence parentale prolongé durant les premiers mois.", "Ce lien entre argument et justification mérite d'être examiné avec attention."], correctAnswer: ["L'argument central est que l'allongement du congé parental favoriserait le développement de l'enfant.", "Cette affirmation se justifie par un temps de présence parentale prolongé durant les premiers mois.", "Ce lien entre argument et justification mérite d'être examiné avec attention."], acceptedAnswers: [], explanation: "Même organisation : argument, puis justification, puis recul critique.", targetLanguageFeature: "organisation argument → justification", tags: ["argumentation", "organization", "variant"] },
    ],
    [
      { subSkill: "guided-argument-justification", prompt: "Idée de départ : un texte affirme que l'interdiction des sacs plastiques réduit la pollution des océans.", instructions: "Rédigez 2 à 3 phrases qui distinguent clairement cet argument de sa justification (la raison qui le soutient).", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "L'argument (l'affirmation) doit rester distinct de sa justification (la raison).", targetLanguageFeature: "distinction argument / justification", tags: ["argumentation", "development"], selfCheck: ["L'argument (l'affirmation) est clairement identifié.", "La justification (la raison) est distincte de l'argument.", "Le lien logique entre les deux est explicite."] },
      { subSkill: "guided-argument-justification-alternative", prompt: "Idée de départ : un texte affirme que la taxation des produits ultra-transformés améliorerait la santé publique.", instructions: "Rédigez 2 à 3 phrases qui distinguent clairement cet argument de sa justification.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "L'argument doit rester distinct de sa justification.", targetLanguageFeature: "distinction argument / justification", tags: ["argumentation", "development", "variant"], selfCheck: ["L'argument (l'affirmation) est clairement identifié.", "La justification (la raison) est distincte de l'argument.", "Le lien logique entre les deux est explicite."] },
    ],
    [
      { subSkill: "independent-argument-justification", prompt: "Vous analysez un texte qui affirme que la généralisation du covoiturage réduirait les embouteillages urbains.", instructions: "Rédigez 2 à 3 phrases qui distinguent clairement cet argument de sa justification.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une analyse C1 réussie distingue nettement l'argument de sa justification.", targetLanguageFeature: "distinction argument / justification, autonome", tags: ["argumentation", "production"], selfCheck: ["L'argument est clairement identifié.", "La justification est distincte de l'argument.", "Le lien logique entre les deux est explicite."] },
      { subSkill: "independent-argument-justification-alternative", prompt: "Vous analysez un texte qui affirme que la généralisation du vélo électrique en libre-service réduirait la pollution urbaine.", instructions: "Rédigez 2 à 3 phrases qui distinguent clairement cet argument de sa justification.", options: [], correctAnswer: null, acceptedAnswers: [], explanation: "Une analyse C1 réussie distingue nettement l'argument de sa justification.", targetLanguageFeature: "distinction argument / justification, autonome", tags: ["argumentation", "production", "variant"], selfCheck: ["L'argument est clairement identifié.", "La justification est distincte de l'argument.", "Le lien logique entre les deux est explicite."] },
    ],
  ]),
];
