import { NextResponse } from "next/server";
import { z } from "zod";
import { AppUserProvisioningError, getCurrentAppUser } from "@/lib/app-user";
import { isHubspotConfigured } from "@/lib/hubspot";
import { prisma } from "@/lib/prisma";
import { syncSupportRequestToHubspot } from "@/lib/support-hubspot-sync";
import {
  SUPPORT_ATTACHMENT_MAX_BYTES,
  SUPPORT_DESCRIPTION_MAX_CHARS,
  isAcceptedSupportAttachment,
  isSupportCategory,
  normalizeSupportAttachmentMimeType,
} from "@/lib/support-request";

const NO_STORE_HEADERS = { "Cache-Control": "private, no-store" };
const EXPECTED_FORM_FIELDS = new Set(["category", "details", "attachment"]);

const supportRequestSchema = z
  .object({
    category: z.string().refine(isSupportCategory),
    details: z
      .string()
      .max(SUPPORT_DESCRIPTION_MAX_CHARS)
      .refine((details) => details.trim().length > 0),
  })
  .strict();

function response(body: Record<string, unknown>, status = 200) {
  return NextResponse.json(body, { status, headers: NO_STORE_HEADERS });
}

function oneStringValue(formData: FormData, name: string) {
  const values = formData.getAll(name);
  return values.length === 1 && typeof values[0] === "string" ? values[0] : null;
}

// `instanceof File` is fragile in unit tests and across runtime realms. The
// route only needs the browser File contract, so validate that small surface
// before reading the byte stream.
function isFileValue(value: FormDataEntryValue): value is File {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof (value as File).name === "string" &&
    typeof (value as File).type === "string" &&
    typeof (value as File).size === "number" &&
    typeof (value as File).arrayBuffer === "function"
  );
}

function sanitizeAttachmentName(name: string) {
  return name.replace(/[\\/\0]/g, "_").trim().slice(0, 255);
}

export async function POST(request: Request) {
  let user: Awaited<ReturnType<typeof getCurrentAppUser>>;
  try {
    user = await getCurrentAppUser();
  } catch (error) {
    if (error instanceof AppUserProvisioningError) {
      return response(
        {
          error: "Your account is still being set up. Please try again.",
          code: "ACCOUNT_PROVISIONING_UNAVAILABLE",
        },
        503,
      );
    }
    throw error;
  }

  if (!user) return response({ error: "Unauthorized" }, 401);

  const formData = await request.formData().catch(() => null);
  if (!formData || Array.from(formData.keys()).some((key) => !EXPECTED_FORM_FIELDS.has(key))) {
    return response({ error: "Invalid support request." }, 400);
  }

  const parsed = supportRequestSchema.safeParse({
    category: oneStringValue(formData, "category"),
    details: oneStringValue(formData, "details"),
  });
  if (!parsed.success) return response({ error: "Invalid support request." }, 400);

  const attachmentValues = formData.getAll("attachment");
  if (attachmentValues.length > 1) return response({ error: "Invalid support request." }, 400);

  const attachmentValue = attachmentValues[0];
  if (attachmentValue !== undefined && !isFileValue(attachmentValue)) {
    return response({ error: "Invalid support request." }, 400);
  }

  let attachment:
    | {
        originalName: string;
        mimeType: string;
        byteSize: number;
        data: Uint8Array<ArrayBuffer>;
      }
    | undefined;

  if (attachmentValue) {
    const originalName = sanitizeAttachmentName(attachmentValue.name);
    const mimeType = normalizeSupportAttachmentMimeType({ name: originalName, type: attachmentValue.type });
    if (
      !originalName ||
      attachmentValue.size <= 0 ||
      attachmentValue.size > SUPPORT_ATTACHMENT_MAX_BYTES ||
      !isAcceptedSupportAttachment({ name: originalName, type: attachmentValue.type }) ||
      !mimeType
    ) {
      return response({ error: "Invalid attachment." }, 400);
    }

    // File.arrayBuffer() always resolves to a real (non-shared) ArrayBuffer at
    // runtime, but TypeScript's typed-array generics infer the wider
    // ArrayBufferLike here; Prisma's generated Bytes input specifically wants
    // Uint8Array<ArrayBuffer>, so this narrows back to what is already true.
    const data = new Uint8Array(await attachmentValue.arrayBuffer()) as Uint8Array<ArrayBuffer>;
    // File.size is caller supplied metadata; use the actual stream length for
    // the durable bound and the saved value.
    if (data.byteLength === 0 || data.byteLength > SUPPORT_ATTACHMENT_MAX_BYTES) {
      return response({ error: "Invalid attachment." }, 400);
    }

    attachment = {
      originalName,
      mimeType,
      byteSize: data.byteLength,
      data,
    };
  }

  try {
    const created = await prisma.supportRequest.create({
      data: {
        userId: user.id,
        // Never accept a browser-provided sender address. The form’s read-only
        // field is just the visible representation of this authenticated value.
        senderEmail: user.email,
        category: parsed.data.category,
        details: parsed.data.details.trim(),
        ...(attachment ? { attachment: { create: attachment } } : {}),
      },
      select: { id: true },
    });

    if (isHubspotConfigured()) {
      // The learner's request is already durably stored above, so a HubSpot
      // outage or misconfiguration must never turn into a failed submission.
      // syncSupportRequestToHubspot itself records the attempt/error on the
      // row; the retry cron (/api/cron/hubspot-support-sync-retry) picks up
      // anything that doesn't succeed here.
      try {
        await syncSupportRequestToHubspot({
          id: created.id,
          senderEmail: user.email,
          senderName: user.name,
          category: parsed.data.category,
          details: parsed.data.details.trim(),
          hubspotTicketId: null,
          hubspotAttachmentFileId: null,
          hubspotAttachmentSyncedAt: null,
          attachment: attachment ?? null,
        });
      } catch (error) {
        console.error("HubSpot support sync failed", error instanceof Error ? error.message : error);
      }
    }

    return response({ id: created.id }, 201);
  } catch {
    // A support message can contain sensitive free-form text and files, so do
    // not include the request body or storage error in logs or the response.
    console.error("Support request persistence failed");
    return response({ error: "Support is temporarily unavailable. Please try again." }, 503);
  }
}
